### ISSUE TITLE
Question: how do I use the proxy after starting it?

### ISSUE THREAD

**Issue by r0fls** [nadoo/glider#1]
I started the proxy with `glider -l :8443 -v`. How do I make requests via the proxy? It would be nice if the readme demonstrated how to use this and get an anonymous IP.

**Comment by nadoo** [comment]
Hi Raphael，the default schema of glider is "mixed", which means to serve as http and socks5 proxy server at the same port, so you can use it in any condition that needs a http or socks5 proxy server.

Besides, glider is not intend to provide any anonymous IP, you can just give it several upstream proxy servers, using the "-f" parameter. 

eg: 
glider -l :8443 -f http://host1:port -f http://host2:port -f socks5://host3:port -s rr
this command will set up a local http and socks5 server listen at port 8443, and all requests will be sent to upstream proxy servers host1, host2, host3 in round robin mode, so your ip address will change every time, but just change in host1,host2,host3's ip address.

If you need anonymous IP, maybe you can tye the Tor project: https://www.torproject.org

**Comment by nadoo** [comment]
update, according the latest commit, the flag name changed:
-l --> -listen
-f --> -forward
-s --> -strategy
