### ISSUE TITLE
error: dial: unknown network 

### ISSUE THREAD

**Issue by cutemanworking** [nadoo/glider#10]
i tried to forward to a proxy in same machine with below config:
forward=socks5://127.0.0.1:1090

got below error msg,  what i did wrong?
2017/09/04 10:51:55 dial to 127.0.0.1:1090 error: dial: unknown network 
2017/09/04 10:51:55 failed to dial: dial: unknown network

**Comment by nadoo** [comment]
Hi @cutemanworking , please have a try with v0.4.1: https://github.com/nadoo/glider/releases/tag/v0.4.1 , I think this bug will be fixed.

**Comment by cutemanworking** [comment]
confirmed that the single forward is fixed, but the multiple forward is not ok with below configure and no err msg display.
forward=socks5://127.0.0.1:1099,socks5://127.0.0.1:1090

**Comment by nadoo** [comment]
![image](https://user-images.githubusercontent.com/287492/30045210-61ed64be-9235-11e7-99af-82a6a31a6748.png)

Works fine here. which os do you use?

**Comment by cutemanworking** [comment]
glider is runing on deiban 8.8 , browser on win10 with SwitchyOmega

**Comment by nadoo** [comment]
```-forward=socks5://127.0.0.1:1099,socks5://127.0.0.1:1090```
This command means a forward chain, which will first connect to :1099, then :1090, then the target. why do you need to chain 2 local proxies? Maybe you need 2 forward flag like this:
```-forward=socks5://127.0.0.1:1099 -forward=socks5://127.0.0.1:1090```? 

Besides that, can you please check the followings:
1. Whether socks5://127.0.0.1:1099 and socks5://127.0.0.1:1090 both worked individually?
2. Whether glider received the requests from your browser?

And if possible, can you please paste the glider log here so I can find some more details?

**Comment by cutemanworking** [comment]
Yep.  I misunderstood the function of forward chain.  actually i just need multiple forwarders.  sorry to bother you and many thanks for your great code!

**Comment by nadoo** [comment]
Feel free to discuss anything about glider here, you're welcome!  :)
