### ISSUE TITLE
Is glider multi-core ready?

### ISSUE THREAD

**Issue by xlighting2017** [nadoo/glider#101]
Hi @nadoo, is the current glider multi-core ready? 

I mean if I run it on a multi-core system, can I have more throughput than a single-core system?  

this may help me choose the optimal hardware -- a Celeron J with 4 cores or a 2-cores i3-xxxxU

thanks in advance

**Comment by nadoo** [comment]
Yes, glider is written in Go, which was designed for multi-core computers. 

In my environment, glider runs on a soft router(n3710/2GB/debian9) serving more than 100 clients.

**Comment by xlighting2017** [comment]
Thanks a lot!
