### ISSUE TITLE
[BUG]Http Proxy over tls client get error code: 400

### ISSUE THREAD

**Issue by bit3725** [nadoo/glider#102]
Hi, I'm using https proxy provided by 3rd service provider. when use this proxy as a forwarder like below, it always return error code: 400
```
forward=tls://xxx.com:443?skipVerify=true,http://xx:xx@
```

the log looks like:
```
error in dial: [http] can not connect remote address: www.bing.com:443. error code: 400
```

I add code in http.go file to log the response and see:
```
Server: nghttpx nghttp2/1.14.0-DEV
```

I tried with another two similar tools(clash & gost) written with go language also, this https proxy works well with them, so seems it's a bug of glider.

**Comment by nadoo** [comment]
I tested glider with a gost https server, it works.

gost: 
`./gost -L https://:443`

glider:
`glider -verbose -listen :8443 -forward tls://domain:443?skipVerify=true,http://`

For nginx, maybe we should send a Host header in the request, I'll test it later when I have time.

**Comment by bit3725** [comment]
Thanks! if you need a https proxy that will return 400 with glider, feel free to let me know, I can share with you for test.

**Comment by nadoo** [comment]
Thank you very much! I saw your server's response looks like it's a http2 proxy, glider does not support http2 because it uses a customized and simple http [implementation](https://github.com/nadoo/glider/blob/master/proxy/http/http.go),  is http2 proxy being widely used? 

If http2 is necessary, maybe I'll switch to the standard http lib to support both http/http2, but the compiled binary file will be much larger.

**Comment by bit3725** [comment]
I think http2's adoption rate is increasing, there is a reference page [here](https://w3techs.com/technologies/details/ce-http2/all/all)
If you will compile a http2 enabled binary file, feel free to send to me and I will help to test if it works with my server.

**Comment by nadoo** [comment]
Hi @bit3725 , that page shows the http2 websites, not http2 proxy. 
glider can use `http CONNECT` to serve http2 (and any other tcp) requests without problem(so does clash).

I think maybe your proxy server check's the `Host` header in http request, you can try the attachment to see whether it works.
[glider.zip](https://github.com/nadoo/glider/files/3721655/glider.zip)

**Comment by bit3725** [comment]
Hi @nadoo , I tested this version. it works well! Thanks for your hard work!

**Comment by nadoo** [comment]
Glad to hear that, so it was solved by the commit: https://github.com/nadoo/glider/commit/d9189e6212d1ecd3cd88a6344fcfda125d416ccc. I'll release a new version soon.
