### ISSUE TITLE
listen tls scheme doesn't work

### ISSUE THREAD

**Issue by GorgeousJ** [nadoo/glider#105]
@nadoo  listen tls scheme doesn't work? 
![image](https://user-images.githubusercontent.com/16712625/60879470-4475fd00-a274-11e9-9419-f561854db8e5.png)

**Comment by nadoo** [comment]
You should use it like:

https(http over tls) proxy server:
`glider -verbose -listen tls://:443?cert=crtFilePath&key=keyFilePath,http://`

ss over tls proxy server:
`glider -verbose -listen "tls://:443?cert=crtFilePath&key=keyFilePath,ss://method:pass@"`
