### ISSUE TITLE
Requirement of add "none" encypt method of ss

### ISSUE THREAD

**Issue by huangdog** [nadoo/glider#106]
Requirement of add "none" encypt method of ss

I use glider make  socks5  to shadowsocks for my other lan pc. It is unnecessary encrypc.
Could you add  "none" encypt method supported for ss?Thanks.
Sorry for my bad English.

**Comment by xlighting2017** [comment]
does SS support NONE as an encryption method?

**Comment by nadoo** [comment]
Try `dummy` method like: `ss://DUMMY@:8443`

**Comment by huangdog** [comment]
> Try `dummy` method like: `ss://DUMMY@:8443`

Thanks! It works! I use koolss client in lede mod by koolshare  and  some ss client with none encryption method such as ssr in windows  ,give any password( because password should be given in ssr/koolss,  although it would be ignore by ssr/koolss).
