### ISSUE TITLE
Transparent proxy doesn't work with IPv6

### ISSUE THREAD

**Issue by phantomcraft** [nadoo/glider#108]
This issue is easy to reproduce with a network namespace:

```
ip netns add nsx
ip link add vethx type veth peer name peerx netns nsx
ip link set vethx up                                                                                                                                                                                
ip addr add 10.0.0.1/24 dev vethx
ip addr add fd00::1/64 dev vethx                                                                                                                                                                   
ip netns exec nsx ip link set peerx up                                                                                                                                                              
ip netns exec nsx ip addr add 10.0.0.2/24 dev peerx
ip netns exec nsx ip addr add fd00::2/64 dev peerx                                                                                                                                                 
ip netns exec nsx ip route add default via 10.0.0.1
ip netns exec nsx ip route add default via fd00::1
                                                                                                                                                                                                     
ip link add br0 type bridge                                                                                                                                                                         
ip link set br0 up                                                                                                                                                                                  
ip addr add 10.0.1.1/24 dev br0                                                                                                                                                                     
ip addr add fd01::1/64 dev br0

iptables -t nat -A PREROUTING -i vethx -p tcp --syn -j DNAT --to-destination 10.0.0.1:11111
ip6tables -t nat -A PREROUTING -i vethx -p tcp --syn -j DNAT --to-destination [fd00::1]:11111
```

Now a SOCKS5 server with IPv6 support is started (github.com/rofl0r/microsocks):

`microsocks -i :: -p 22222`

A testing program is started, here is the performance testing tool iperf3 found in any linux repository:

`iperf3 -s -B ::`

Now glider is fired up, it's listening on all local IPv4/6 addresses and having as an upstream proxy the local SOCKS5 server.

`glider -verbose -listen redir://[::]:11111 -forward socks5://[fd01::1]:22222`

When invoking iperf3 inside the network namespace using the IPv4 address of bridge (10.0.1.1) everything runs fine:

`ip netns exec nsx iperf3 -c 10.0.1.1 -t 2`
> Connecting to host 10.0.1.1, port 5201
> [  5] local 10.0.0.2 port 60200 connected to 10.0.1.1 port 5201
> [ ID] Interval           Transfer     Bitrate         Retr  Cwnd
> [  5]   0.00-1.00   sec   323 MBytes  2.71 Gbits/sec    0    246 KBytes       
> [  5]   1.00-2.00   sec   423 MBytes  3.55 Gbits/sec    0    238 KBytes       
> - - - - - - - - - - - - - - - - - - - - - - - - -
> [ ID] Interval           Transfer     Bitrate         Retr
> [  5]   0.00-2.00   sec   745 MBytes  3.13 Gbits/sec    0             sender
> [  5]   0.00-2.03   sec   736 MBytes  3.05 Gbits/sec                  receiver
> 
> iperf Done.

But when tested with IPv6 address, I got an error:

`ip netns exec nsx iperf3 -c fd01::1 -t 2`
> iperf3: error - unable to receive control message: Connection reset by peer

Glider shows this:

```
2019/08/09 21:07:46 [redir] failed to get target address: no such file or directory
```

The same error persists when changing SOCKS5 address to IPv4 address of bridge: `-forward socks5://10.0.1.1:22222`

I also tested with a local HTTP proxy server and the same thing, when testing with other transparent forwarders such as moproxy and transocks, everything works ok.

**Comment by nadoo** [comment]
Yes, ipv6 hasn't been supported and tested yet, I think it will be the main feature of the next version.

**Comment by phantomcraft** [comment]
I use a SSH proxy which has IPv6 support within, but in my side my ISP has only IPv4, should be very useful in this scenario.

Thanks.

**Comment by nadoo** [comment]
I don't have ipv6 network environment...

**Comment by phantomcraft** [comment]
@nadoo

Use a tunnel broker: https://wiki.archlinux.org/index.php/IPv6_tunnel_broker_setup

**Comment by phantomcraft** [comment]
Hey @nadoo, I tested the new option "redir6" and it's working well, thank you very much.

Also, socks5:// and http:// listening schemes are working with IPv6 connections.

**Comment by phantomcraft** [comment]
\o/

**Comment by phantomcraft** [comment]
@nadoo 

I use 2 SSH proxies which have IPv6 support in their side.

I want to share with you for helping the project, if you can provide any e-mail contact I can send the logins and passwords of them to you.

**Comment by nadoo** [comment]
Hi @phantomcraft , I really appreciate that you gave so much help to this project, may I know which part is not working under ipv6 environment first?

**Comment by phantomcraft** [comment]
@nadoo 

You already implemented IPv6 (with redir6) and IPv6 is working with mixed://, socks5:// and http://, that's why I closed this topic, for me the IPv6 support in Glider is now complete.

I just asked an e-mail for helping with SSH proxies which I use that have IPv6 in their side for helping the project.

There are some free SSH proxies in the Internet, some services have IPv6, I'll post the links of two ones that have IPv6 in their side (I'm not spamming):

https://www.vpnjantit.com/create-free-account.html?server=nl2&type=SSH&negara=Netherlands

https://cyberssh.com/ssh/create/ssh-germany-1-month

Create an account in one of these and connect with this scheme:

`ssh -v -C -N -D 0.0.0.0:1080 -p 22 <username>@<hostname>`

Test it:
```

user@localhost:~$ curl --socks5 127.0.0.1:1080 [2620:12e:1000::a00:f]
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
</body></html>
```

**Comment by nadoo** [comment]
Thank you very much for these useful information! 😃
