### ISSUE TITLE
Whether to consider supporting intranet penetration, reverse proxy and speed limit？

### ISSUE THREAD

**Issue by ansoda** [nadoo/glider#109]
I studied the source code and thought that the architecture is very good. I hope the author can continue to develop.
I hope to provide more effective features, such as projects: https://github.com/snail007/goproxy 
thanks!

**Comment by qqqqqqrrrrhh123a** [comment]
你可以将frp和glider二者源码结合开发，稍微修改一下就行了，记得开源，支持你i
