### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by dimqua** [nadoo/glider#112]
I can't run a binary from `glider-v0.7.0-linux-mipsle.tar.gz` archive, I get this error.
```
$ ./glider
./glider: line 1: syntax error: unexpected "("
```
I'm using openwrt on netgear [r6100](https://openwrt.org/toh/hwdata/netgear/netgear_r6100) router.

**Comment by nadoo** [comment]
Maybe you can try building glider yourself by:
`GOOS=linux GOARCH=mips GOMIPS=softfloat go build`

ref: https://stackoverflow.com/questions/55154143/golang-binary-not-running-on-mips
