### ISSUE TITLE
chacha20 github or gitlab?

### ISSUE THREAD

**Issue by berney** [nadoo/glider#115]
`docker run --rm -it golang:1.12-alpine3.9`
`go get github.com/nadoo/glider`

```
package github.com/Yawning/chacha20: code in directory /go/src/github.com/Yawning/chacha20 expects import "gitlab.com/yawning/chacha20.git"
```

**Comment by nadoo** [comment]
It's used by the 3rd party [ssr](https://github.com/sun8911879/shadowsocksR) lib, and moved to gitlab recently. I'm considering to drop ssr support later because it was not maintained anymore.

**Comment by imrehg** [comment]
So the code currently cannot be built? Or is there a workaround for this?

**Comment by nadoo** [comment]
It can be built, you can see the CI info of the latest commit.

**Comment by nadoo** [comment]
Hi @berney & @imrehg, there's a PR #124 from @felixonmars, you can try whether it worked.

**Comment by imrehg** [comment]
@nadoo tested it out (the `dev` branch were the PR was merged to, build is successful with this (with `GO111MODULE=on` to use the settings from `go.mod` I believe). So that looks good to me, cheers!
