### ISSUE TITLE
It's not clear how to turn off periodical proxy checking

### ISSUE THREAD

**Issue by aeroxy** [nadoo/glider#117]
There should be an additional setting such as `proxycheck` default true and when it is false the periodical proxy checking should turn off.

**Comment by nadoo** [comment]
[glider-v0.10.0-linux-x86_64.zip](https://github.com/nadoo/glider/files/4567843/glider-v0.10.0-linux-x86_64.zip)

now we have a new option `checkdisabledonly` to let glider check disabled forwarders only, if it is set to `true`, glider will check all forwarders at startup and will never check them again if they're always available.

you can check the attachment to see whether it meets your requirements.

_Originally posted by @nadoo in https://github.com/nadoo/glider/pull/138#issuecomment-622947433_

**Comment by nadoo** [comment]
new version(v0.10.0) released, please feel free to reopen this issue if you still have any questions about it.
