### ISSUE TITLE
unknown scheme 'ssr'

### ISSUE THREAD

**Issue by bcookatpcsd** [nadoo/glider#119]
(great app btw) 

I'm using haproxy as a front end with squid and glider as a backend.. working really good so far.. 

I use a different ssr app for home, and would like to replace it with glider (if possible). The other app is very hard to read.

 glider -listen ss://AES-128-CFB:"P@ssw0rd!"@:8388 -verbose
 
works, and in the logs shows as [ss]

glider -listen ssr://AES-128-CFB:"P@ssw0rd!"@:8443 -verbose

unknown scheme 'ssr'

I saw issue #113 where the comment was about the upstream author of your ssr module.. 

is ssr disabled for the time being? or does my above command just get an encrypted shadowsocks?

Thanks in advance.

**Comment by nadoo** [comment]
You can only use ssr in forward parameters:
```
Available schemes for different modes:
  listen: mixed ss socks5 http redir redir6 tcptun udptun uottun tls unix kcp
  forward: reject ss socks5 http ssr vmess tls ws unix kcp simple-obfs
```
That means you can only use glider as ssr client, not server.

**Comment by foxconndmd** [comment]
> 
> 
> You can only use ssr in forward parameters:
> 
> ```
> Available schemes for different modes:
>   listen: mixed ss socks5 http redir redir6 tcptun udptun uottun tls unix kcp
>   forward: reject ss socks5 http ssr vmess tls ws unix kcp simple-obfs
> ```
> 
> That means you can only use glider as ssr client, not server.

有点不理解这个限制，转发不应该配对吗，如果客户端使用ws+tls转发，服务器不能监听ws，要使用别的软件做服务端？

**Comment by nadoo** [comment]
Because the 3rd party ssr package only supports running as client.
