### ISSUE TITLE
SSR forward doesn't support protocol=origin

### ISSUE THREAD

**Issue by aeroxy** [nadoo/glider#126]
When protocol=origin glider forward agent won't work.

**Comment by nadoo** [comment]
There may be some bug in the 3rd party [ssr lib](https://github.com/sun8911879/shadowsocksR), `protocol=origin` means use the ss protocol, can you use ss proxy instead?

**Comment by aeroxy** [comment]
SS protocol also won't work because the obfs setting is http_simple.

**Comment by aeroxy** [comment]
Turns out some of the protocol=origin would work with ss protocol. The one with nginx in front usually won't work because those would check the host in the header.

**Comment by nadoo** [comment]
Thanks for your feedback, as there are problems when nginx in front, do you use glider with that? Maybe we need to improve glider's implementation (e.g. add host header)?

**Comment by aeroxy** [comment]
Technically speaking SS protocol + host is just SSR with origin protocol + http_simple / http_post / similar obfs. I don't know why glider wouldn't work while the original SSR does. You can try to set up a similar nginx + ss server and see what I mean.
