### ISSUE TITLE
http proxy auth not working

### ISSUE THREAD

**Issue by whoizit** [nadoo/glider#127]
glider 0.9 
glider -verbose -listen http://proxy:password@:10616

2019/10/21 01:58:57 server.go:76: [http] auth failed from [200:c9:d951:8509:78b:6010:d760:ae53]:34304, auth info: :
2019/10/21 01:58:58 server.go:76: [http] auth failed from [200:c9:d951:8509:78b:6010:d760:ae53]:34306, auth info: :
2019/10/21 01:58:58 server.go:76: [http] auth failed from [200:c9:d951:8509:78b:6010:d760:ae53]:34308, auth info: :

**Comment by nadoo** [comment]
tested with gost and it worked, what http proxy client do you use?

**Comment by nadoo** [comment]
I use wireshark to capture the request, and I don't see any auth info in http request header.

**Comment by whoizit** [comment]
works with curl -x, but not works if using firefox internal proxy settings and also over SwitchyOmega firefox plugin

**Comment by nadoo** [comment]
So maybe it's bug of SwitchyOmega.

**Comment by whoizit** [comment]
```
2019/10/21 03:00:43 server.go:76: [http] auth failed from [200:c9:d951:8509:78b:6010:d760:ae53]:44340, auth info: :
2019/10/21 03:01:20 server.go:76: [http] auth failed from [200:c9:d951:8509:78b:6010:d760:ae53]:44390, auth info: :
2019/10/21 03:01:23 server.go:76: [http] auth failed from [200:c9:d951:8509:78b:6010:d760:ae53]:44396, auth info: :
2019/10/21 03:03:09 server.go:100: [http] [200:c9:d951:8509:78b:6010:d760:ae53]:44592 <-> iplocation.net:443 [c] via DIRECT
2019/10/21 03:03:14 server.go:160: [http] [200:c9:d951:8509:78b:6010:d760:ae53]:44598 <-> iplocation.net:80
```

**Comment by whoizit** [comment]
so maybe it's Firefox bug too?

**Comment by whoizit** [comment]
Same in telegram-desktop

**Comment by nadoo** [comment]
This issue was closed by the last commit automatically, you can test and reopen it if there're still bugs in http auth.

**Comment by nadoo** [comment]
Yes, some http proxy clients have different behaviors, they send all requests with no auth info first, and when the proxy server asked them to be authorized, they send request the second time including the auth info. so there will be a lot of logs like you post. I'll try to optimize it later.
