### ISSUE TITLE
help message in stderr

### ISSUE THREAD

**Issue by whoizit** [nadoo/glider#129]
I've just trying to get help message in `less` but I can't, cause glider posting it in `stderr`, not in `stdout`
so I can't do this
`glider -h | less`
but I can do that
`glider -h 2> /dev/stdout | less`

this is absolutely incorrect behaviour. Help|usage messages should be posted in stdout

**Comment by nadoo** [comment]
The default output of flag package is os.Stderr: https://golang.org/src/flag/flag.go#L570

I can change it if we should use stdout instead, what about other programs?

**Comment by whoizit** [comment]
I'm not understand what do you mean. You have no experience using Linux/Mac?
Any program receives input from stdin, draws output to stdout, and prints all errors to stderr.
Glider for some reason prints help message in stderr when it should print it in stdout

https://www.howtogeek.com/435903/what-are-stdin-stdout-and-stderr-on-linux/

**Comment by nadoo** [comment]
glider uses Go's standard flag package as its command interface, which print help message to stderr by default, that was did by the Go's author, I haven't change the default behavior yet.

**Comment by nadoo** [comment]
I tested some programs written by Go, e.g.: [so-shadowsocks2](https://github.com/shadowsocks/go-shadowsocks2/releases)

```
./go-shadowsocks2 -h 1> 1.txt
./go-shadowsocks2 -h 2> 2.txt
```

```
ll
-rw-r--r-- 1 root root    0 Oct 21 19:59 1.txt
-rw-r--r-- 1 root root 1.1K Oct 21 20:00 2.txt
```

it also prints help message to stderr, because that is the default behavior of Golang's standard package.

anyway, it can be changed if we want.

**Comment by whoizit** [comment]
print help in stdout https://github.com/txthinking/brook
print help in stdout https://github.com/docker/docker-ce

**Comment by whoizit** [comment]
print help in stdout https://github.com/syncthing/syncthing

**Comment by whoizit** [comment]
print help in stdout https://github.com/gohugoio/hugo

**Comment by whoizit** [comment]
print help in stdout https://github.com/ipfs/go-ipfs

**Comment by nadoo** [comment]
ok, I’ll change it later.

**Comment by whoizit** [comment]
any ever linux program do it into stdout
