### ISSUE TITLE
concurrent map writes problem

### ISSUE THREAD

**Issue by nodarret** [nadoo/glider#13]
Have some problems with multiple rr strategies, below stack trace. Using latest 0.4.1 version.
```
fatal error: concurrent map writes

goroutine 6 [running]:
runtime.throw(0x5a3ca8, 0x15)
	D:/go/src/runtime/panic.go:605 +0x95 fp=0xc420055df0 sp=0xc420055dd0 pc=0x429085
runtime.mapassign_fast64(0x570c00, 0xc42000e960, 0x0, 0xc4200c6000)
	D:/go/src/runtime/hashmap_fast.go:592 +0x3b7 fp=0xc420055e50 sp=0xc420055df0 pc=0x40c0e7
main.(*rrDialer).checkDialer(0xc420064b00, 0x0)
	E:/work/codes/go/src/github.com/nadoo/glider/strategy.go:125 +0x7b9 fp=0xc420055fd0 sp=0xc420055e50 pc=0x545579
runtime.goexit()
	D:/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420055fd8 sp=0xc420055fd0 pc=0x4569e1
created by main.newRRDialer
	E:/work/codes/go/src/github.com/nadoo/glider/strategy.go:57 +0x138
```
Full stack: [glider_stacktrace.log](https://github.com/nadoo/glider/files/1438213/glider_stacktrace.log)

**Comment by nadoo** [comment]
Hi @nodarret , sorry for the late response. 

Could you please paste your config file here(hide server info), and tell me how to reproduce this bug? My glider works well with about 20 upstream proxy servers for several months, and I think there's no concurrent checking on a specified proxy instance. so it's a little weird... :p

**Comment by nodarret** [comment]
Hi @nadoo ,

My configuration was something like below, where forward proxies A-D were same in both rules (bypass rare limit).
Problem occurs after few days of working, so it was hard to reproduce. Can't find log, but i remember that problem occurs when one of check fails (for example timeout) and checkDialer for specific idx go sleep for retry. After some checks probably (my assumption) newRRDialer was fired when that timeouted check thread was awaking what results multiple thread access to rr.status. 
If im right problem is in shared map in goroutine. After fix with sync.Map problem never occures.

```
#glider.conf
listen=localhost:8443
rulefile=ipify.rule
rulefile=ipinfo.rule

#ipify.rule
forward=ss:/A
forward=ss:/B
forward=ss:/C
forward=ss:/D
strategy=rr
checkwebsite=google.com
checkduration=30
domain=api.ipify.org

#ipinfo.rule
forward=ss:/A
forward=ss:/B
forward=ss:/C
forward=ss:/D
strategy=rr
checkwebsite=google.com
checkduration=30
domain=ipinfo.io
```

**Comment by nadoo** [comment]
Hi @nodarret , confirmed this bug, my stupid mistake: write a map in multiple goroutines.

Thanks for your info and PR.
