### ISSUE TITLE
SSR forward:error in dial: Unsupported encryption method: none

### ISSUE THREAD

**Issue by chenxinxing** [nadoo/glider#136]
when connect to SSR server with method: none, then get error.  pls check what is the problem??

**Comment by nadoo** [comment]
sorry, the 3rd party [ssr](https://github.com/nadoo/glider/blob/c4cebdd1d8f4e2708018fb6c9aae28957a15dc35/proxy/ssr/ssr.go#L10) packate does not support `none` method now.
