### ISSUE TITLE
There should be explanation for the forward strategies

### ISSUE THREAD

**Issue by aeroxy** [nadoo/glider#137]
Forward strategies:
  rr: Round Robin mode
  ha: High Availability mode
  lha: Latency based High Availability mode
  dh: Destination Hashing mode

It's not very clear to me what these mode do under the hood. And shouldn't there be a completely random mode to maximize my invisibility from the host?

**Comment by xlighting2017** [comment]
see [here](https://github.com/nadoo/glider/issues/64#issuecomment-423146818)

**Comment by nadoo** [comment]
Thanks @xlighting2017

**Comment by tobwen** [comment]
+1 for the "random mode"
