### ISSUE TITLE
kcp listen and client (where is the readme?)

### ISSUE THREAD

**Issue by huffery** [nadoo/glider#146]
I cannot find any example of kcp.
So 
the following listen on server seems works:
glider -listen kcp://aes:key@:443,socks5:// -verbose
2020/01/02 01:43:52 strategy.go:82: [strategy] forward to remote servers in round robin mode.
2020/01/02 01:43:52 kcp.go:164: [kcp] listening on :443

But I cannot find a way to make client end to work. The following does not work.

>glider -listen :888 -forward kcp://aes:key@<IP>:443,socks5:// -verbose
2020/01/02 01:46:39 strategy.go:149: [strategy] no available forwarders, just use: <IP>:443, please check your settings or network
2020/01/02 01:46:39 strategy.go:82: [strategy] forward to remote servers in round robin mode.
2020/01/02 01:46:39 mixed.go:69: [mixed] listening TCP on :888
2020/01/02 01:46:39 socks5.go:165: [socks5-udp] listening UDP on :888

**Comment by huffery** [comment]
what my input is something like:
 glider -listen :888 -forward kcp://aes:key@1.1.1.1:443,socks5:// -verbose
github hid my IP. just in case you wonder why I do not input my server IP.

**Comment by nadoo** [comment]
server:
```
glider -verbose -listen "kcp://none:key@127.0.0.1:8444?dataShards=10&parityShards=3,http://"
```

client:
```
glider -verbose -listen :8443 -forward "kcp://none:key@127.0.0.1:8444?dataShards=10&parityShards=3,http://"
```

**Comment by nadoo** [comment]
Feel free to reopen this issue if you still have any problem
