### ISSUE TITLE
ssr forward does not support . and / in password

### ISSUE THREAD

**Issue by aeroxy** [nadoo/glider#147]
for example, if I have a setting:

```
forward=ssr://aes-256-ctr:t.me/SSRSUB@v11.ssrsub.xyz:9000?protocol=auth_aes128_md5&protocol_param=&obfs=tls1.2_ticket_auth&obfs_param=
```

here the `t.me/SSRSUB` is the password in plaintext

glider outputs: `2020/01/17 14:08:18 log.go:19: parse ssr://aes-256-ctr:t.me/SSRSUB@v11.ssrsub.xyz:9000?protocol=auth_aes128_md5&protocol_param=&obfs=tls1.2_ticket_auth&obfs_param=: invalid port ":t.me" after host`

**Comment by nadoo** [comment]
You should encode special characters in your url:
https://www.w3schools.com/tags/ref_urlencode.ASP
- `.` -> `%2E`
- `/`->`%2F`
```
forward=ssr://aes-256-ctr:t%2Eme%2FSSRSUB@v11.ssrsub.xyz:9000?protocol=auth_aes128_md5&protocol_param=&obfs=tls1.2_ticket_auth&obfs_param=
```
