### ISSUE TITLE
vmess forward doesn't support kcp

### ISSUE THREAD

**Issue by aeroxy** [nadoo/glider#152]
I've tried:

```
forward=kcp://${add}:${port},vmess://${id}@?alterID=${aid}
```

This will result at: `no available forwarders, just use: ${add}:${port}, please check your settings or network`

**Comment by nadoo** [comment]
Do you use v2ray on the server side? v2ray's builtin transport is `mKCP`, not `kcp`, so it's not compatible.

may be you should use kcptun together with v2ray on the server side, and use glider as client like:
```
glider -verbose -listen :8443 -forward "kcp://none:key@IP:PORT?dataShards=10&parityShards=3,vmess://UUID@?alterID=2"
```
