### ISSUE TITLE
can not run on windows xp

### ISSUE THREAD

**Issue by fyhong** [nadoo/glider#153]
无论https://github.com/nadoo/glider/releases这里下载的386还是自己用go编辑386的版本，都不能在32位xp系统下运行。
都会显示不是有效的32位应用程序

**Comment by nadoo** [comment]
https://golang.org/doc/go1.10#ports
`Go 1.10 is the last release that will run on Windows XP or Windows Vista. Go 1.11 will require Windows 7 or later.`
