### ISSUE TITLE
Does glider support SOCKS5 forward to SSR?

### ISSUE THREAD

**Issue by tmxd09887** [nadoo/glider#154]
Does glider support SOCKS5 forward to SSR?

Thanks!

**Comment by NomadJohn** [comment]
glider -listen socks5://:1080 -forward ssr://method:pass@host:port?protocol=xxx&protocol_param=yyy&obfs=zzz&obfs_param=xyz

**Comment by NomadJohn** [comment]
> glider -listen socks5://:1080 -forward ssr://method:pass@host:port?protocol=xxx&protocol_param=yyy&obfs=zzz&obfs_param=xyz

But it doesn't seem to support UDP forward to ssr

**Comment by tmxd09887** [comment]
@NomadJohn Have you tested it? thanks

so,tcp works?

**Comment by NomadJohn** [comment]
> @NomadJohn Have you tested it? thanks
> 
> 
> 
> so,tcp works?

yes, It's working on my server, tcp only.

**Comment by nadoo** [comment]
Feel free to reopen this issue if there's any problem you find again.
