### ISSUE TITLE
Can we support vmess ws `headers Host` parameter ?

### ISSUE THREAD

**Issue by rampageX** [nadoo/glider#157]
glider do not support `requestHost` now, it will be support in the future？

**Comment by nadoo** [comment]
Can not find a `requestHost` parameter in[vmess](https://www.v2ray.com/en/configuration/protocols/vmess.html) config, did you mean `Headers-Host` parameter in [websocket](https://www.v2ray.com/en/configuration/transport/websocket.html)?

**Comment by rampageX** [comment]
V2rayN GUI：
![2020-04-05_111656](https://user-images.githubusercontent.com/994081/78466311-4c46cd00-7732-11ea-9dd2-4ee133e5d6ee.png)

Name `Host` in v2ray's config file:
![config_json](https://user-images.githubusercontent.com/994081/78466344-b2cbeb00-7732-11ea-9471-7f28b5e8eb66.png)

Name `requestHost` in v2rayN's server list:
![guiNConfig_json](https://user-images.githubusercontent.com/994081/78466359-d0995000-7732-11ea-9d36-938d582b4d95.png)

**Comment by rampageX** [comment]
> Can not find a `requestHost` parameter in [vmess](https://www.v2ray.com/en/configuration/protocols/vmess.html) config, did you mean `Headers-Host` parameter in [websocket](https://www.v2ray.com/en/configuration/transport/websocket.html)?

Yes!

**Comment by nadoo** [comment]
build the latest commit and test it like:
```forward=ws://DOMAIN:PORT/PATH?host=HOST,vmess://UUID@?alterID=0```

**Comment by rampageX** [comment]
![2020-04-05_124850](https://user-images.githubusercontent.com/994081/78467120-f7a84f80-773b-11ea-85d7-d5ccdc9208c5.png)


`./glider 0.10.0 usage:`

`./glider -listen :7777 -forward ws://a.b.c.d:80/user?host=jp-1.test.com,vmess://cccc1111-aaaa-bbbb-cccc-dddddddddddd@?alterID=0 -verbose`

> socks5.go:135: [socks5] 192.168.2.1:47228 <-> 140.82.113.4:443 via 122.190.3.7:80, error in dial: [ws] error in ws handshake parseFirstLine

**Comment by nadoo** [comment]
git checkout dev

**Comment by rampageX** [comment]
> git checkout dev

It's working now, thanks!

**Comment by qqqqqqrrrrhh123a** [comment]
what is this going on? https://github.com/nadoo/glider/issues/270
