### ISSUE TITLE
forward=socks5 TO http

### ISSUE THREAD

**Issue by nuoyan001** [nadoo/glider#158]
forward=socks5:/USER:PWD@IP:PORT
LOGO

2020/04/11 16:14:53 server.go:103: [http] 127.0.0.1:52815 <-> www.youtube.com:443 [c] via IP:PORT
2020/04/11 16:14:53 server.go:110: [http] relay error: read tcp 192.168.1.100:52816->IP:PORT: wsarecv: An existing connection was forcibly closed by the remote host.
2020/04/11 16:14:54 server.go:103: [http] 127.0.0.1:52819 <-> www.youtube.com:443 [c] via IP:PORT

**Comment by nuoyan001** [comment]
2020/04/11 16:23:38 server.go:103: [http] 127.0.0.1:53521 <-> www.facebook.com:443 [c] via  IP:PORT
2020/04/11 16:23:39 server.go:110: [http] relay error: read tcp 192.168.1.100:53522-> IP:PORT: wsarecv: An existing connection was forcibly closed by the remote host.

**Comment by nadoo** [comment]
Hi @nuoyan001 , what is the problem here? 
1. the forwarding always failed?
2. the forwarding works fine but sometimes print some error?

**Comment by nuoyan001** [comment]
I can access GOOGLE normally, but I cannot access YOUTUBE and FACEBOOK

**Comment by nadoo** [comment]
I'm afraid I can't help here, maybe you should check your dns settings on the socks5 server.
