### ISSUE TITLE
some times checktimeout not work

### ISSUE THREAD

**Issue by luomoxu** [nadoo/glider#159]
glider version 0.9.3
my conf
`checkwebsite=clients3.google.com
checkinterval=5
checktimeout=3`
but I get this logs
`2020/04/15 17:31:56 strategy.go:240: [check] trojan-1:15000(200) -> clients3.google.com:80, DISABLED. check timeout: 3m7.777332353s,`

and an feature I want to use http://clients3.google.com/generate_204 to check network
Use this website will Use minimal network consumption

**Comment by nadoo** [comment]
trojan has not been supported in v0.9.3...

**Comment by nadoo** [comment]
checktimeout means if the check time larger than it, the forwarder will be set to disabled.

**Comment by luomoxu** [comment]
> checktimeout means if the check time larger than it, the forwarder will be set to disabled.

I use trojan with socks5 forward

**Comment by nadoo** [comment]
Good suggestion, but it needs to change the whole process to support timeout and canceling, I'd prefer not to change at this time to keep it simple.
