### ISSUE TITLE
Forwarder set to disable, permanently or temporary?

### ISSUE THREAD

**Issue by huffery** [nadoo/glider#16]
I noticed when one forwarder is not able to connect, glider will not try to verify it  again. Is it Disabled permanently? Most of the time, the remote ss or socks proxy is only temporarily disabled.

**Comment by nadoo** [comment]
Hi @huffery ，it's temporary, glider will double the 'checkduration' when a proxy is disabled. you can check the log, I think it will try again later.

see https://github.com/nadoo/glider/blob/5893cf0d3ad22b9b17db0449fa845b2ebb1ed7b6/strategy.go#L102
and
https://github.com/nadoo/glider/blob/5893cf0d3ad22b9b17db0449fa845b2ebb1ed7b6/strategy.go#L126
for more details.
