### ISSUE TITLE
Load balancing not work

### ISSUE THREAD

**Issue by luomoxu** [nadoo/glider#160]
use glider 0.9.3
This is my config file
```
verbose=True

checkwebsite=clients3.google.com
checkinterval=5
checktimeout=3

listen=:15000

forward=socks5://192.168.158.21:15000#priority=200
forward=socks5://192.168.158.22:15000#priority=100
forward=socks5://192.168.158.23:15000#priority=100
forward=socks5://192.168.158.24:15000#priority=100
forward=socks5://192.168.158.25:15000#priority=100
forward=socks5://192.168.158.26:15000
forward=socks5://192.168.158.27:15000
forward=socks5://192.168.158.28:15000

strategy=rr
```
but after sometime from the log 
I only see use 192.168.158.21:15000
no other no check log

**Comment by nadoo** [comment]
You set `#priority=200` to `192.168.158.21:15000`, so if it's available, it will be chosen.

**Comment by luomoxu** [comment]
> You set `#priority=200` to `192.168.158.21:15000`, so if it's available, it will be chosen.

the other set priority=100 won't be use?

**Comment by nadoo** [comment]
forwarders with priority 100 will only be used when all forwarders with higher priority are unavailable.

**Comment by luomoxu** [comment]
> forwarders with priority 100 will only be used when all forwarders with higher priority are unavailable.

I used to think priority is weights
