### ISSUE TITLE
proxy based on authentication

### ISSUE THREAD

**Issue by blacklat** [nadoo/glider#161]
is it possible to make a proxy based on authentication as in the scenario?
I wrote a code based on the idea of rsockstun, I was able to do what I need but not with authentication. when I read the buffer to get the user I can no longer copy the connection to the other end. can your code do that?
![cenario](https://user-images.githubusercontent.com/56522998/80854266-0421aa00-8c0d-11ea-8524-6f3ec8bb4cf4.png)

**Comment by nadoo** [comment]
Sorry I don't catch your question clearly, you can look into the source code and may find some useful stuff.

**Comment by blacklat** [comment]
didn't you understand the drawing? more clear that it does not exist. I asked just not to have to do an extensive search on your code, which is large and interconnected with various dependencies and structures, since it was you who made you know the exact point. But anyway thanks for nothing, thanks for your enthusiasm in answering a simple question. You are a great collaborator!
