### ISSUE TITLE
v2ray-plugin support

### ISSUE THREAD

**Issue by bytew021** [nadoo/glider#164]
simple-obfs is deprecated
https://github.com/nadoo/glider/issues/90#issue-419022254

Whether it can support  https://github.com/shadowsocks/v2ray-plugin

https://github.com/nadoo/glider/issues/90#issuecomment-471176426
```
forward=tls://host:port,ws://,ss://method:pass@
```
This cannot support v2ray-plugin

**Comment by nadoo** [comment]
```
forward=tls://host:port,ws://,ss://method:pass@
```
It should support, except that `mux` not supported now, you can disable mux on the server side.

what is your server's config now?

**Comment by bytew021** [comment]
mux is not turned on
server's config
```
shadowsocks2-linux -s ss://AEAD_CHACHA20_POLY1305:pass@:443 -plugin v2ray-plugin -plugin-opts server;tls;host=xxx
```

**Comment by nadoo** [comment]
Thanks for feedback, I see there's a `host` setting in your server config, is this `host` used in websocket header or tls sni?

if the following settings not worked, what is the output?
```
-forward=tls://host:port,ws://@?host=xxx,ss://AEAD_CHACHA20_POLY1305:pass@
```

**Comment by bytew021** [comment]
> 
> 
> Thanks for feedback, I see there's a `host` setting in your server config, is this `host` used in websocket header or tls sni?
> 
> if the following settings not worked, what is the output?
> 
> ```
> -forward=tls://host:port,ws://@?host=xxx,ss://AEAD_CHACHA20_POLY1305:pass@
> ```

```
2020/05/08 16:15:00 ss.go:258: [ss] dial to  error: x509: cannot validate certificate for xxx-ip because it doesn't contain any IP SANs
2020/05/08 16:15:00 forward.go:118: [forwarder] xxx-ip:443 recorded 12 failures, maxfailures: 3
2020/05/08 16:15:00 socks5.go:137: [socks5] 127.0.0.1:49453 <-> www.google.com.hk:443 via xxx-ip:443, error in dial: x509: cannot validate certificate for xxx-ip because it doesn't contain any IP SANs
```

**Comment by nadoo** [comment]
if we add `?skipVerify=true` to tls like:
```
-forward=tls://host:port?skipVerify=true,ws://@?host=xxx,ss://AEAD_CHACHA20_POLY1305:pass@
```
what will be the result?

**Comment by bytew021** [comment]
> 
> 
> if we add `?skipVerify=true` to tls like:
> 
> ```
> -forward=tls://host:port?skipVerify=true,ws://@?host=xxx,ss://AEAD_CHACHA20_POLY1305:pass@
> ```
> 
> what will be the result?

```
2020/05/08 19:26:59 socks5.go:142: [socks5] 127.0.0.1:52914 <-> www.google.com.hk:443 via xxx-ip:443
2020/05/08 19:26:59 socks5.go:149: [socks5] relay error: read tcp 192.168.11.101:52915->xxx-ip:443: wsarecv: An existing connection was forcibly closed by the remote host.
2020/05/08 19:26:59 forward.go:118: [forwarder] xxx-ip:443 recorded 1 failures, maxfailures: 3
2020/05/08 19:26:59 socks5.go:142: [socks5] 127.0.0.1:52916 <-> www.google.com.hk:443 via xxx-ip:443
2020/05/08 19:26:59 socks5.go:149: [socks5] relay error: read tcp 192.168.11.101:52917->xxx-ip:443: wsarecv: An existing connection was forcibly closed by the remote host.
2020/05/08 19:26:59 forward.go:118: [forwarder] xxx-ip:443 recorded 2 failures, maxfailures: 3
```

**Comment by nadoo** [comment]
Looks like we are closer to success, what is the error log of the server side?

**Comment by bytew021** [comment]
> 
> 
> if we add `?skipVerify=true` to tls like:
> 
> ```
> -forward=tls://host:port?skipVerify=true,ws://@?host=xxx,ss://AEAD_CHACHA20_POLY1305:pass@
> ```
> 
> what will be the result?



> 
> 
> Looks like we are closer to success, what is the error log of the server side?

Logs on the server side
```
2020/05/08 23:08:31 log.go:23: [v2ray-plugin]: 2020/05/08 23:08:31 [Error] [3507188600] v2ray.com/core/common/mux: unexpected EOF > v2ray.com/core/common/mux: failed to read metadata > v2ray.com/core/common/mux: invalid metalen 11478
```

**Comment by nadoo** [comment]
you should add mux=0 config on your server cuz glider doesn't support it.

**Comment by nadoo** [comment]
I tested simple mode of v2ray-plugin server and it worked:
server:
```
./shadowsocks2-linux  -s 'ss://AEAD_CHACHA20_POLY1305:pass@:443' -verbose --plugin v2ray-plugin -plugin-opts "server;mux=0"
```
client:
```
forward=ws://host:port,ss://AEAD_CHACHA20_POLY1305:pass@
```

for tls mode, I need to know what exactly the v2ray-plugin did, it needs more time to test.

**Comment by bytew021** [comment]
> 
> 
> you should add mux=0 config on your server cuz glider doesn't support it.

Err ...😅
configure mux = 0 is ok
Thought the default was mux = 0

**Comment by nadoo** [comment]
glad to hear that! 

btw. I don't like the design of v2ray-plugin, it's not clearly how the protocols chained.

In glider, we can set up a `ss over tls` proxy server like:
```
listen=tls://:443?cert=crtFilePath&key=keyFilePath,ss://method:pass@
```
and on the client side, we can simply change `listen` to `forward` and add host port info in it url like:
```
forward=tls://DOMAIN:PORT,ss://method:pass@
```

Unfortunately, the `ws` protocol in glider only supports client mode now, because I wrote it for simplification, and haven't write code for server mode yet: https://github.com/nadoo/glider/tree/master/proxy/ws

Mybe I'll add server mode to ws protocol later, then we don't need ss&v2ray-plugin anymore.

**Comment by qqqqqqrrrrhh123a** [comment]
https://github.com/nadoo/glider/issues/270. what is this going on
