### ISSUE TITLE
how do make socks5-udp via remote

### ISSUE THREAD

**Issue by adventurer** [nadoo/glider#166]
no:1 socks5.go:142: [socks5] 127.0.0.1:56917 <-> 54.190.26.134:443 via 47.90.62.113:1080
no:2 socks5.go:200: [socks5-udp] 127.0.0.1:55507 <-> 104.155.80.155:37015
make no:2 like this:
socks5.go:200: [socks5-udp] 127.0.0.1:55507 <-> 104.155.80.155:37015 via 47.90.62.113:1080

**Comment by adventurer** [comment]
[socks5-udp] 127.0.0.1:55298 <-> 8.8.8.8:53 via 172.31.26.164:1080
when the server in the back of a nat,can not get the corect ip adress but a private ip.

**Comment by nadoo** [comment]
Dunno your environment so I can't locate the problem you faced, maybe you can test directly on your server and see whether you can get correct result.
