### ISSUE TITLE
SOCKS 5 UDP Associate Request

### ISSUE THREAD

**Issue by jayqizone** [nadoo/glider#168]
When a UDP packet forward to a socks5 server, It seems like the request is not formed as expected

> The DST.ADDR and DST.PORT fields contain the address and port that the client expects to use to send UDP datagrams on for the association.
The server MAY use this information to limit access to the association.
If the client is not in possesion of the information at the time of the UDP ASSOCIATE, the client MUST use a port number and address of all zeros.

[SOCKS Protocol Version 5](https://tools.ietf.org/html/rfc1928)

But I captured this:
![image](https://user-images.githubusercontent.com/8263369/83220343-4c4cd180-a1a5-11ea-9dd8-d8ebc248bfd2.png)

Socks5 server may just ignore DST.ADDR:DST.PORT in the UDP associated request, and simply reply the UDP datagram to the client actual source addr & port, so this problem may not matter at all, just a little confused

Did I miss something?

FYI, my config is like:
listen=ss://
forward=socks5://

**Comment by nadoo** [comment]
Yes, the socks5 server was implemented for simplicity, so we doesn't follow all the specs in rfc document.
