### ISSUE TITLE
remote dial error: vmess client does not support udp now

### ISSUE THREAD

**Issue by CoolCollin** [nadoo/glider#171]
I confronted this error when using v2rayNG as a socks5 client to glider:

 "...socks5.go:187: [socks5-udp] remote dial error: vmess client does not support udp now"

But, when using swichyomega in chrome directly with glider and the same conf, there was no such error.
To my understanding, wasn't glider suppposed to convert udp to tcp and forward to forwarder automatically?

How could I resolve this error when using v2rayNG?
Pls excuse me as a rookie, I really cannot understand what was going on since I had already googled a lot as there is not so much pages on glider at this time on the internet.

Here is the conf:

verbose=True
listen=:1080

strategy=ha
checkwebsite=www.apple.com:80
checkinterval=60

listen=uottun://:53=10.0.0.1:53
dnsalwaystcp=true

forward=tls://www.abc.com.de:443?skipVerify=true,ws://@/abc?host=www.abc.com.de,vmess://none:uudi@?alterID=8

Thanks in advance!

**Comment by nadoo** [comment]
udp is not supported in vmess client now, cuz I think it's inefficient and useless.

**Comment by qqqqqqrrrrhh123a** [comment]
i have same ws issues,help me https://github.com/nadoo/glider/issues/270
