### ISSUE TITLE
Version 0.10.1 SSR error

### ISSUE THREAD

**Issue by rampageX** [nadoo/glider#176]
All SSR servers worked fine on self build dev branch commit `382f9cc`, but failed with new 0.10.1 release version, all check show this error:

`error in read: auth_aes128_* post decrypt incorrect checksum`

Roll back to `382f9cc` all fine.

**Comment by nadoo** [comment]
That may be caused by the latest commit of ssr lib: https://github.com/mzz2017/shadowsocksR/pull/8 , unfortunately the lib doesn't have any tagged versions. I'll update the dependency version and make a new release later.

**Comment by nadoo** [comment]
It should be solved in v0.10.2, feel free to reopen this issue if there's still any problem.
