### ISSUE TITLE
How to not use connect method when forward HTTP

### ISSUE THREAD

**Issue by aruku7230** [nadoo/glider#177]
I use glider as a http proxy forwarder to forward http to another http proxy. The configuration is:

    listen=http://127.0.0.1:8500
    forward=<username>:<password>@proxyserver.com

glider works well when connecting to HTTPS site like `curl --proxy "http://127.0.0.1:8500 https://google.com`.
However it fails to forward an http request like `curl --proxy "http://127.0.0.1:8500 http://google.com`, the 
error message is:

> client.go:69: [http] 'CONNECT' to ports other than 443 are not allowed by proxy proxyserver.com

The reason is that proxyserver.com not allow 'CONNECT' method to port other than 443 and glider uses
'CONNECT' method to forward the HTTP and HTTPS request. 

https://github.com/nadoo/glider/blob/2d71facf9b8ec0f3482bff3b46992732228a4f43/proxy/http/client.go#L36-L39

From [this wikipedia](https://en.wikipedia.org/wiki/HTTP_tunnel#HTTP_CONNECT_method), it is common proxy servers may limit connections by only allowing connections to the default HTTPS port 443. So could you @nadoo  consider only use connect method when proxy https, but use the normal way (see curl behavious below) to proxy http?

``` shell
$ curl --proxy http://username:password@proxyserver.com:8080 -vv http://ifconfig.me
* Rebuilt URL to: http://ifconfig.me/
*   Trying 192.168.1.11...
* TCP_NODELAY set
* Connected to proxyserver.com (192.168.1.11) port 8080 (#0)
* Proxy auth using Basic with user 'username'
> GET http://ifconfig.me/ HTTP/1.1
> Host: ifconfig.me
> Proxy-Authorization: Basic xxxxxxxxxxxxxxxx
> User-Agent: curl/7.55.1
> Accept: */*
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 OK
< Date: Fri, 25 Sep 2020 08:17:57 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 13
< X-Powered-By: Express
< Access-Control-Allow-Origin: *
< X-BlueCoat-Authorization: xxxxxxxxx
< Age: 0
< X-Cache: MISS from 1.mobile.local
< Via: 1.1 google, 1.1 1.mobile.local (squid/3.2.6)
< Connection: keep-alive
<
* Connection #0 to host proxyserver.com left intact
```

**Comment by nadoo** [comment]
Hi @aruku7230 , sorry for late response.
glider uses `CONNECT` to request remote http proxy server because of the following reasons:
1. glider is a general purpose forward proxy that can chain different proxy protocols, so just `CONNECT` and returns a tcp connection is the simplest way to do it.
2. in forward mode,  glider doesn't modify any incoming request, it just forward it.

we can keep this issue open and I'll think about how to implement it later.
