### ISSUE TITLE
How Glider listens using Unix Sockets?

### ISSUE THREAD

**Issue by phantomcraft** [nadoo/glider#179]
When I type:

```
user@localhost:~$ glider -help | grep "unix"
  listen: mixed ss socks5 http redir redir6 tcptun udptun uottun tls unix kcp
  forward: reject ss socks4 socks5 http ssr ssh vmess trojan tls ws unix kcp simple-obfs
  unix://path
```

It says that it listens on unix sockets, I tried to do that but it shows:

```
user@localhost:~$ glider -verbose -listen unix:///dev/shm/test -forward socks5://127.0.0.1:1080
2020/09/05 20:30:33 strategy.go:86: [strategy] default: forward in round robin mode.
2020/09/05 20:30:33 log.go:19: [unix] malformd listener:unix:///dev/shm/test
```

How can I make Glider listens on Unix Sockets?

**Comment by bnuhero** [comment]
Glider doesn't support to listen unix domain socket only. Try this:
`glider -verbose -listen unix:///dev/shm/test,sock5:// -forward socks5://127.0.0.1:1080`

See https://github.com/nadoo/glider/blob/d6d706b5ee5600f3fdb0bbe9c6a28f8ff5dfa862/proxy/unix/unix.go#L56 for more information.

**Comment by phantomcraft** [comment]
Thanks @bnuhero 

It worked for me.

**Comment by nadoo** [comment]
Thans @bnuhero !

It must be used combine with other proxy protocols.
