### ISSUE TITLE
X-Forwarded-For header is not added

### ISSUE THREAD

**Issue by motleycrew** [nadoo/glider#18]
in mixed mode X-Forwarded-For header is not added which causes IP address to be the same for all requests in mix mode. What is the best way to add X-Forwarded-For header?

**Comment by nadoo** [comment]
Hi @motleycrew , I've add this feature in commit https://github.com/nadoo/glider/commit/84b47cbf1d60d3f4f0ac67abb95a2c43b34c3060, you can enable it by adding  params to the listen url, 
e.g: `glider -verbose -listen :8443?xff=true` or `glider -verbose -listen http://:8443?xff=true`

**Comment by motleycrew** [comment]
Thanks @nadoo for the quick turn around.

I don't see X-Forwarded-For header in response headers.  Please see headers below for digg.com.
![proxy](https://user-images.githubusercontent.com/9128579/34907701-7929c7a4-f837-11e7-9f78-ab948ef93b19.PNG)

In FireFox network tab I see:

```
Proxy-Connection: close
Content-Type: text/html; charset=UTF-8
Etag: "1907202523c978da3318f29984e553d9df52b4c7"
Set-Cookie: frontend.ts=1515858687; expires=Thu, 12 Jul 2018 15:51:26 GMT; Path=/frontend.ts.hp=1515858687; expires=Thu, 12 Jul 2018 15:51:26 GMT; Path=/
Transfer-Encoding: chunked
Connection: close
Content-Encoding: gzip
Date: Sat, 13 Jan 2018 15:51:26 GMT
Server: TornadoServer/2.3
Vary: Accept-Encoding
X-Frame-Options: SAMEORIGIN
```

I did following steps
git clone https://github.com/nadoo/glider.git
go build
./glider -verbose -listen :8443?xff=true


Am I missing something?

**Comment by nadoo** [comment]
This header will be sent by glider to remote server, so you can't see it in server's response, you can use wireshark to capture the http request sent to digg.com and see it.

**Comment by motleycrew** [comment]
Thanks @nadoo this works.
