### ISSUE TITLE
When 2 or more DNS listen points are used, only the last is activated

### ISSUE THREAD

**Issue by phantomcraft** [nadoo/glider#181]
Easy to reproduce:

```
user@localhost:~$ glider -verbose -dns=127.0.0.1:1053 -dns=[::1]:1053 -dnsserver=1.1.1.1:53
2020/09/09 19:51:40 strategy.go:86: [strategy] default: forward in round robin mode.
2020/09/09 19:51:40 server.go:60: [dns] listening UDP on [::1]:1053
2020/09/09 19:51:40 server.go:114: [dns-tcp] listening TCP on [::1]:1053
2020/09/09 19:52:07 client.go:99: [dns] [::1]:56984 <-> 1.1.1.1:53(udp) via DIRECT, type: 1, t.co: 104.244.42.197
```

```
user@localhost:~$ dig @127.0.0.1 -p 1053 t.co

; <<>> DiG 9.16.6-Debian <<>> @127.0.0.1 -p 1053 t.co
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

```
user@localhost:~$ dig @::1 -p 1053 t.co

; <<>> DiG 9.16.6-Debian <<>> @::1 -p 1053 t.co
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54970
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;t.co.				IN	A

;; ANSWER SECTION:
t.co.			4	IN	A	104.244.42.197

;; Query time: 22 msec
;; SERVER: ::1#1053(::1)
;; WHEN: Wed Sep 09 19:52:07 EDT 2020
;; MSG SIZE  rcvd: 53
```

It also happens when a forwarder is used.

**Comment by nadoo** [comment]
Now glider supports only 1 local dns server, you can try:
1. listen to `:1053`, and use iptables to restrict access to none local addresses;
2. listen to `localhost:1053`, access it by using ip `127.0.0.1` or `::ffff:127.0.0.1`;
```
glider -verbose -dns localhost:1053 -dnsserver 1.1.1.1:53
dig www.apple.com @127.0.0.1 -p 1053
dig www.apple.com @::ffff:127.0.0.1 -p 1053
```

**Comment by phantomcraft** [comment]
More than 2 addresses would be very useful, you should implement it.

Here I use a sandbox to forward Tor/SSH traffic to a virtual machine, the addresses of virtual interface (bridge) are 192.168.1.1 and [fd00::1], when I try -dns=[::]:1053 causes errors when using the [fd00::1]:53 resolver (192.168.1.1 goes normally).

```
root@localhost:/home/user# dig @fd00::1 t.co
;; reply from unexpected source: fd00::380f:81ff:fe18:751e#10053, expected fd00::1#53

;; reply from unexpected source: fd00::380f:81ff:fe18:751e#10053, expected fd00::1#53

;; reply from unexpected source: fd00::380f:81ff:fe18:751e#10053, expected fd00::1#53


; <<>> DiG 9.16.4-Debian <<>> @fd00::1 t.co
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```
/\ Glider listens on -dns=[::]:10053 and the port 10053 is forwarded to 53 port on the virtualization bridge with iptables:

`ip6tables -t nat -A PREROUTING -i virbr0 -p udp -d fd00::1 --dport 53 -j DNAT --to-destination [fd00::1]:10053`

**Comment by phantomcraft** [comment]
@nadoo 

Will you implement support for multiple DNS listeners?

I really need this feature in Glider.

**Comment by nadoo** [comment]
why not listen to :10053 ?

**Comment by phantomcraft** [comment]
@nadoo 

:10053 and [::]:10053 are the same, they will make 192.168.1.1:10053 and [fd00::1]:10053 work, but when [fd00::1]:10053 is forwarded to [fd00::1]:53 with ip6tables, errors happens in the virtual machine when the [fd00::1]:53 is invoked.

I also tried 0.0.0.0:10053 and a forwarding scheme as this:

`ip6tables -t nat -A PREROUTING -i virbr0 -p udp -d fd00::1 --dport 53 -j DNAT --to-destination [::ffff:192.168.1.1]:10053`

ip6tables can't forward a IPv4 converted address.

That's why multiple DNS listen points are useful, one can serve IPv4 to a virtual interface and the second IPv6.

This feature is really needed for traffic forwarding to virtual machines.

**Comment by nadoo** [comment]
Listen to :10053 will listen on all local interfaces, which includes the interface you want to listen separately, maybe you should check your iptables rules to meet your requirements? or you can setup 2 glider processes?

**Comment by phantomcraft** [comment]
@nadoo 

iptables rules are ok.

Unfortunately I will have to setup 2 glider processes.

I hope Glider in next release supports multiple DNS listeners.

**Comment by nadoo** [comment]
listen on `:10053` equals to listen on `127.0.0.1:10053` & `[::1]:10053` & in your environment `192.168.1.1:10053` & `[fd00::1]:10053` at the same time. which equals to multiple listeners with same port and different ip.

**Comment by phantomcraft** [comment]
@nadoo 

[::1]:10053 means [fd00::1]:10053 too, but when forwarded to a virtual interface causes error in the virtual machine.

**Comment by nadoo** [comment]
`glider -dns :10053` equals to multiple listener `glider -dns 127.0.0.1:10053 -dns [::1]:10053 -dns 192.168.1.1:53 -dns [fd00:1]:10053`, so there would be no different.

**Comment by phantomcraft** [comment]
@nadoo 

Yes, but :10053 when forwarded to [fd00::1]:53 causes this error in the virtual machine:

```
root@localhost:/home/user# dig @fd00::1 t.co
;; reply from unexpected source: fd00::380f:81ff:fe18:751e#10053, expected fd00::1#53

;; reply from unexpected source: fd00::380f:81ff:fe18:751e#10053, expected fd00::1#53

;; reply from unexpected source: fd00::380f:81ff:fe18:751e#10053, expected fd00::1#53


; <<>> DiG 9.16.4-Debian <<>> @fd00::1 t.co
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

Changing the address from :10053 to [fd00::1]:10053 makes it work with [fd00::1]:53.

That's why I request this feature.

**Comment by nadoo** [comment]
Maybe you need SNAT to reach your goal:
https://unix.stackexchange.com/questions/492937/redirecting-udp-to-local-port-the-reply-packet-isnt-snated-w-iptables
https://stackoverflow.com/questions/41574846/kubernetes-pods-replying-with-unexpected-source-for-dns-queries
https://superuser.com/questions/1323458/reply-from-unexpected-source-when-dns-server-is-running-as-docker-container-in

**Comment by phantomcraft** [comment]
@nadoo 

SNAT is used to forward to an external network, what I'm doing is forwarding to an internal one.

Here is the script that I use to access the Internet (outside my country): https://pastebin.com/NCt2wpzx

/\ iptables and ip6tables rules are ok,

**Comment by phantomcraft** [comment]
@nadoo 

Could you please implement support for more than one DNS listener now?
