### ISSUE TITLE
Internal dns resolver

### ISSUE THREAD

**Issue by p0we7** [nadoo/glider#184]
Is it possible to add an internal dns resolver, the current version of glider's dns service doesn't seem to resolve connections from the listener.

Because I can't get the right dns answer when I use dns to unblock a streaming site (e.g. Netflix). And i can't change the dns configuration on my system, I need to specify a specific dns server via glider.

shadowsocks-libev has a similar implementation, which is what i'm using now.

<details>
<summary>ss-server config</summary>

```
-d <addr>
Setup name servers for internal DNS resolver (libc-ares). The default server is fetched from /etc/resolv.conf.
```

| Command Line | JSON |
|--|--|
|-d "8.8.8.8"| "nameserver": "8.8.8.8"|
</details>

But I'd like to be able to implement this in glider and support custom dns records(`dnsrecord=www.example.com/1.2.3.4`).

**Comment by nadoo** [comment]
[glider-v0.11.0-dev.zip](https://github.com/nadoo/glider/files/5273773/glider-v0.11.0-dev.zip)

If you get some time, you can try the attachment to see whether it meets your requirement. :p

**Comment by p0we7** [comment]
how to config the internal dns？

**Comment by nadoo** [comment]
enable the builtin dns server

dns=:5353

**Comment by nadoo** [comment]
If what you want is local resolving, not support now, ss & socks5 uses remote resolving to avoid dns pollution

**Comment by p0we7** [comment]
Now that it's working well, I can use glider instead of ss-server!

**Comment by p0we7** [comment]
I included a dnsrecord file, but the remote dns of ss won't use it, instead requesting `dnsserver`.

If I use smartdns dns server as a `dnsserver` then I can get the correct records, but I want to implement the whole process in one program through glider, not sure if you will have implemented this, I can continue to use smartdns if you think it is bad.

<details>
<summary> glider.conf </summary>

```
verbose=True

listen=ss://AEAD_AES_256_GCM:xxxxyyyyzzzz@:888

dns=127.0.0.1:5353

dnsserver=45.90.28.56:53
dnsserver=45.90.30.56:53

include=unlock.inc.conf
```
</details>

<details>
<summary> unlock.inc.conf </summary>

```
dnsrecord=netflix.com/103.xxx.xxx.xxx
dnsrecord=netflix.net/103.xxx.xxx.xxx
dnsrecord=nflximg.net/103.xxx.xxx.xxx
dnsrecord=nflxvideo.net/103.xxx.xxx.xxx
dnsrecord=nflxso.net/103.xxx.xxx.xxx
dnsrecord=nflxext.com/103.xxx.xxx.xxx
```
</details>

<details>
<summary> glider log </summary>

```
2020/09/27 10:12:27 client.go:99: [dns] 127.0.0.1:43767 <-> 45.90.30.56:53(udp) via DIRECT, type: 1, www.netflix.com: 34.208.14.211,52.32.11.65,34.223.232.157,54.68.124.197,52.35.217.11,52.42.196.217,34.216.27.122,54.148.159.121
2020/09/27 10:12:27 client.go:99: [dns] 127.0.0.1:45429 <-> 45.90.30.56:53(udp) via DIRECT, type: 28, www.netflix.com: 2620:108:700f::3419:c8b1,2620:108:700f::3420:5550,2620:108:700f::3694:9f79,2620:108:700f::3423:f741,2620:108:700f::3427:3079,2620:108:700f::3459:d6d6,2620:108:700f::3419:f331,2620:108:700f::36bb:1d97
2020/09/27 10:12:27 ss.go:161: [ss] 14.xxx.xxx.xxx:54905 <-> www.netflix.com:443 via DIRECT
```
</details>

<details>
<summary> dig result </summary>

```
[root@server ~]# dig @127.0.0.1 -p 5353 nflximg.net

; <<>> DiG 9.11.13-RedHat-9.11.13-5.el8_2 <<>> @127.0.0.1 -p 5353 nflximg.net
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49962
;; flags: qr; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;nflximg.net.			IN	A

;; ANSWER SECTION:
nflximg.net.		0	IN	A	103.xxx.xxx.xxx

;; Query time: 0 msec
;; SERVER: 127.0.0.1#5353(127.0.0.1)
;; WHEN: 日 9月 27 10:13:53 CST 2020
;; MSG SIZE  rcvd: 56
```
</details>

**Comment by nadoo** [comment]
you set `netflix.com` in dnsrecord, but in glider log, the domain you request is `www.netflix.com`? so that will not match.

**Comment by p0we7** [comment]
Does glider not support matching domain suffix? Can only the entire domain match?

**Comment by nadoo** [comment]
Yes, now it does entire matching. If it matches domain suffix, when we want to resolve abc.netflix.com via upstream dns server instead of return 103.11.11.11, how can we achieve that?

**Comment by p0we7** [comment]
Since 103.11.11.11 is a sniproxy, i need to resolve all *.netflix.com domains to this IP.

Maybe i shouldn't use that and just use forwarder to forward all the traffic to the 103.11.11.11.

**Comment by nadoo** [comment]
If you can control 103.11.11.11, you can setup a ss proxy server on it, and use a rule file like:

glider.conf
```
verbose=True

listen=ss://AEAD_AES_256_GCM:xxxxyyyyzzzz@:888

rules-dir=rules.d
```

rules.d/netflix.rule
```
domain=fast.com
domain=netflix.com
domain=netflix.net
domain=nflxext.com
domain=nflximg.com
domain=nflximg.net
domain=nflxso.net
domain=nflxvideo.net

forward=ss://method:pass@103.11.11.11:port
```

**Comment by p0we7** [comment]
Thank you, that is a very good solution, and the glider match domain suffix.
