### ISSUE TITLE
panic: runtime error: slice bounds out of range [:-5]

### ISSUE THREAD

**Issue by pcmid** [nadoo/glider#188]
this function `ReadFrom` returned `-5` with nil error
https://github.com/nadoo/glider/blob/6eda2b79c8342eb3393879b310b78458fc5d2c29/proxy/ss/packet.go#L32 
```bash
goroutine 39480 [running]:
github.com/nadoo/glider/proxy.RelayUDP(0x838960, 0xc000192840, 0x833ea0, 0xc0000b1080, 0x838960, 0xc0001920c0, 0x1bf08eb000, 0x0, 0x0)                                                       
        /home/runner/work/glider/glider/proxy/conn.go:175 +0x245
github.com/nadoo/glider/proxy/ss.(*SS).ListenAndServeUDP.func1(0xc000192840, 0x833ea0, 0xc0000b1080, 0xc00000e268, 0xc00001f020)                                                             
        /home/runner/work/glider/glider/proxy/ss/server.go:159 +0x73
created by github.com/nadoo/glider/proxy/ss.(*SS).ListenAndServeUDP
        /home/runner/work/glider/glider/proxy/ss/server.go:158 +0x79b
```

**Comment by nadoo** [comment]
Can this panic be reproduced every time? did you use any forwarder? or only listens as a ss server?

**Comment by pcmid** [comment]
I used it as a forwarder. it both as a ss server and as a ss clinet.

**Comment by nadoo** [comment]
I can't reproduce here. what os/arch do you use? I can build a new binary and upload it here for you to test whether it solved.

**Comment by pcmid** [comment]
I'm running it on debian/amd64.I think I can help you to test it, with
pleasure😋

nadoo <notifications@github.com>于2020年10月10日 周六下午6:10写道：

**Comment by nadoo** [comment]
[glider-linux.zip](https://github.com/nadoo/glider/files/5359276/glider-linux.zip)

You can give it a try, thank you very much! 😄

**Comment by pcmid** [comment]
It seems that has been solved.

**Comment by nadoo** [comment]
Thanks!
