### ISSUE TITLE
[Suggestion] New service, Simple port forwarding

### ISSUE THREAD

**Issue by phantomcraft** [nadoo/glider#189]
This feature would be useful.

The syntax could be:

_**service=portforward,PROTOCOL,LISTEN_ADDRESS:LISTEN_PORT,REMOTE_ADDRESS:REMOTE_PORT**_

==============================================

`glider -service=portforward,tcp,127.0.0.1:1853,1.0.0.1:853`

/\ Listen on TCP 127.0.0.1:1853, forward to 1.0.0.1:853

====================

`glider -service=portforward,tcp,127.0.0.1:1853,1.0.0.1:853 -service=portforward,udp,127.0.0.1:1053,1.1.1.1:53`

/\ Listen on TCP 127.0.0.1:1853, forward to 1.0.0.1:853, listen on UDP 127.0.0.1:1053, forward to 1.1.1.1:53

**Comment by nadoo** [comment]
same with tcptun and udptun?
```
glider -listen tcptun://127.0.0.1:1853=1.0.0.1:853
```

**Comment by phantomcraft** [comment]
Glider doesn't accept multiple udptun, tcptun and dns listening points. I tested it here.

**Comment by nadoo** [comment]
You can run multiple udptun or tcptun like:
`
glider -verbose -listen udptun://:53=8.8.8.8:53 -listen udptun://:53535=8.8.4.4:53
`

And we can benefit from the current architecture like remote forwarding like:
`
glider -listen udptun://:53=8.8.8.8:53 -forward ss://method:pass@host:port
`
it will forward all udp requests to 8.8.8.8:53 via remote ss server.

**Comment by phantomcraft** [comment]
Sorry, I thought that udptun/tcptun only worked with parent forwarder, I didn't know that it works with DIRECT connection.

Thank you.
