### ISSUE TITLE
How to get the origin ip of the remote server on the client side?

### ISSUE THREAD

**Issue by motleycrew** [nadoo/glider#19]
In mixed mode or socks v5 proxy mode we see ip adddress of the proxy for all requests instead of the remote server. See screenshot below.

This is with  glider proxy on my local network. See remote address for digg.com is 192.168.0.200:8443
![image](https://user-images.githubusercontent.com/9128579/34908948-a3feb7d0-f84d-11e7-9c44-1d6c1c2d9561.png)

Without glider proxy remote address of digg.com is: 184.72.55.130:80. 

![image](https://user-images.githubusercontent.com/9128579/34908968-feaabe18-f84d-11e7-9369-417a7e8dda66.png)

How do I get remote Address on client side?

Thanks.

**Comment by nadoo** [comment]
Hi @motleycrew , the 'X-Forwarded-For' is used in http request headers, I don't think there is a  equivalent in http response. https://stackoverflow.com/questions/20404741/x-forwarded-for-response-equivalent

I simply add this header to the http response,  afb5f246acff2432ff780e986c65fff9288d56c8.  you can check it out. not sure whether it's right or not, maybe I'll delete it later.

**Comment by motleycrew** [comment]
I came across this https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Via . This seems something we might be looking for.

**Comment by nadoo** [comment]
I'm afraid that the 'Via' header only adds proxy info, not the destination site.

**Comment by motleycrew** [comment]
Thanks @nadoo  for the update. This commit afb5f24. looks good for http sites.

For https sites. I  do not see X-forwarded-for header in the response header. Try: https://www.citibank.com

We scan thousands of malicious websites and we need to know their IP address for threat intelligence purposes but we do not want to give our actual IP address to these guys. Is it possible to conditionally added X-forwarded-for header to either request,response or both.

**Comment by nadoo** [comment]
Hi @motleycrew , in this commit: ecdd33f0ed75de1f9954aaaf478a22783845c7d2 I've add a new header `X-Server-IP`, you can enable it by using `glider -verbose -listen http://:8443?xsi=true`

I think there are 2 better choices to achieve your purpose:
1. use squid: higher performance, and support MITM mode so we can modify the https packets(headers).
2. or if you use glider on a linux gateway, you can use transparent mode of glider: 
`glider -verbose -listen redir://:1081`
with iptables redirect
`iptables -t nat -A PREROUTING -p tcp -m multiport --dports 80,4443 -j REDIRECT --to-ports 1081`
then the proxy will be transparent so your client can get remote server's ip directly in socket.

**Comment by nadoo** [comment]
Removed the ```xsi``` and ```xfi``` params in the latest version. Please fire an issue when sombody needs these features.
