### ISSUE TITLE
[Feature request] -dnsalwaysudp

### ISSUE THREAD

**Issue by phantomcraft** [nadoo/glider#190]
Glider listens on two protocols when used with -dns=x.x.x.x:yy option, both TCP and UDP, but when the upstream DNS address (-dnsserver=x.x.x.x:yy) only supports UDP, it can't be resolved on Glider DNS-TCP port since it sends the request always in TCP format.

This is easy to reproduce, here I need to convert the DNS port of Tor (which only supports UDP on it) to a DNS-TCP port for forwarding to a container with haproxy:

```
user@localhost:~$ glider -verbose -dns=[::1]:1053 -dnsserver=[::1]:9053
2020/11/02 18:43:00 server.go:60: [dns] listening UDP on [::1]:1053
2020/11/02 18:43:00 server.go:104: [dns-tcp] listening TCP on [::1]:1053
2020/11/02 18:43:13 client.go:172: [dns] error in resolving goo.gl, failed to connect to server [::1]:9053 via DIRECT: dial tcp :0->[::1]:9053: connect: connection refused, next server: [::1]:9053
2020/11/02 18:43:13 server.go:140: [dns-tcp] error in exchange: dial tcp :0->[::1]:9053: connect: connection refused
2020/11/02 18:43:13 client.go:172: [dns] error in resolving goo.gl, failed to connect to server [::1]:9053 via DIRECT: dial tcp :0->[::1]:9053: connect: connection refused, next server: [::1]:9053
2020/11/02 18:43:13 server.go:140: [dns-tcp] error in exchange: dial tcp :0->[::1]:9053: connect: connection refused
```

```
user@localhost:~$ dig +tcp @::1 -p 1053 goo.gl
;; communications error to ::1#1053: end of file

;; communications error to ::1#1053: end of file
```

/\ When Glider TCP port is invoked with **dig** app, makes the program send the DNS query to the upstream address in TCP mode, but the upstream DNS address only have UDP support, which produces an error.

This option would be really useful for converting DNS-UDP to DNS-TCP and forwarding TCP to a sandbox or a container.

**Comment by nadoo** [comment]
Yes, that was by design:
If a client sends dns request to glider via UDP, and there's no forwarder specified, glider will query the upstream dns server via UDP, otherwise, glider will use TCP because:
1. if a client sends dns request to glider by TCP, it may larger than a UDP dns message, so query the upstream by TCP is the right choice.
2. if there's any forwarder specified, cuz most of them do not support UDP, TCP is the best choice.

**Comment by phantomcraft** [comment]
Will you implement this feature?

**Comment by nadoo** [comment]
a client will query glider's dns server via TCP only when it needed, `e.g.: the dns message size larger than 512`, so glider should follow the client's request and use TCP to query upstream servers, or there may be some problems.

**Comment by phantomcraft** [comment]
I found and tested a program that converts TCP-DNS to UDP-DNS: https://github.com/shawn1m/overture

Perhaps it could serve as a basis if you decide to implement this feature in Glider.
