### ISSUE TITLE
[Feature request] More options for the VLESS scheme

### ISSUE THREAD

**Issue by rampageX** [nadoo/glider#191]
For example: flow control flow, transmission protocol network, underlying transmission protocol tls/xtls, etc. . .

**Comment by nadoo** [comment]
glider supports protocol chains like:
`glider -verbose listen "tls://:1234?cert=/path/to/cert&key=/path/to/key,vless://UUID@?fallback=127.0.0.1:80"`
`glider -verbose -listen "ws://:1234/ws?host=127.0.0.1,vless://UUID@?fallback=127.0.0.1:80"`
`glider -verbose listen "tls://:1234?cert=/path/to/cert&key=/path/to/key,ws://@/ws?host=127.0.0.1,,vless://UUID@?fallback=127.0.0.1:80"`
it equals to the transmission protocol network you need.

As this protocol is still in preview state(version 0), we can follow up these enhancements when the version 1 released.

**Comment by rampageX** [comment]
thnaks.
