### ISSUE TITLE
[Feature suggestion] Unix Sockets as listening points in tcptun and udptun

### ISSUE THREAD

**Issue by phantomcraft** [nadoo/glider#194]
I use this scheme to turn a Unix Socket in a listening port:

`glider  -listen tcptun://127.0.0.1:9051=0.0.0.0:0 -forward unix:///var/run/tor/control`

or

`glider  -listen tcptun://[::1]:9051=[::]:0 -forward unix:///var/run/tor/control`

But the inverse is not possible, if listening points in tcptun and udptun could be Unix Sockets, it would allow ports to be forwarded to containers, sandboxes and network namespaces.

The scheme could be:

`glider -listen tcptun:///var/lib/lxc/container/rootfs/tmp/socket=127.0.0.1:9050`

/\ In this way it would be possible to forward a listening port in the main network namespace to a container:

`nsenter -n -t "$(lxc-info -p -n container | awk '{ print $2 }')" glider -listen tcptun://127.0.0.1:9050=0.0.0.0:0 -forward unix://var/lib/lxc/container/rootfs/tmp/socket`

**Comment by nadoo** [comment]
Thanks! I was thinking about change the tcptun(and other transport protocols) scheme like this:
old:
`glider -listen tcptun://127.0.0.1:80=1.1.1.1:80`
new:
`glider -listen tcptun://127.0.0.1:9051 -forward tcptun://1.1.1.1:80`

old:
`glider -listen tcptun://127.0.0.1:80=1.1.1.1:80 -forward socks5://2.2.2.2:1080`
new:
`glider -listen tcptun://127.0.0.1:80 -forward socks5://2.2.2.2:1080,tcptun://1.1.1.1:80`

old:
`glider -listen tcptun://127.0.0.1:9051=0.0.0.0:0 -forward unix:///var/run/tor/control`
new:
`glider -listen tcptun://127.0.0.1:9051 -forward unix:///var/run/tor/control`

then you can use `glider -listen unix:///var/run/tor/control -forward tcptun://127.0.0.1:9050` to meet your requirement.

will it better than current scheme?

**Comment by phantomcraft** [comment]
@nadoo 

Sure, it will be better.

Unix sockets as listening points in udptun would allow DNS to be forwarded to containers and network namespaces.

**Comment by nadoo** [comment]
ok, it also needs to make some changes to the current check mechanism, because we can not check a website via a transport only forwarder. we should take some time to think about it.

**Comment by nadoo** [comment]
with the latest commit: `docker pull nadoo/glider:dev`

you can use glider as below:

listen on local tcp port 5353 and forward to a unix socket:
`./glider -verbose -listen tcp://:5353 -forward unix:///tmp/test.sock`

listen on unix socket and forward to tcp://8.8.8.8:53:
`./glider -verbose -listen unix:///tmp/test.sock -forward tcp://8.8.8.8:53`

test it:
`dig @127.0.0.1 -p 5353 +tcp www.google.com`

**Comment by phantomcraft** [comment]
@nadoo

Does it work with udptun? I will wait for the next stable release to include in my scripts and system.

**Comment by nadoo** [comment]
`./glider -verbose -listen udp://:5353 -forward unix:///tmp/test.sock`
`./glider -verbose -listen unix:///tmp/test.sock -forward udp://8.8.8.8:53`
`dig @127.0.0.1 -p 5353 www.google.com`

**Comment by phantomcraft** [comment]
Great work, now it's possible to forward DNS to network namespaces, containers and sandboxes.

**Comment by phantomcraft** [comment]
@nadoo 

I tested here and there is a bug:

```
user@localhost:~$ go/bin/glider -verbose -listen unix:///dev/shm/uds -forward udp://127.0.0.1:9053
2020/12/02 00:50:32 group.go:182: [group] only 1 forwarder found, disable health checking
2020/12/02 00:50:32 server.go:53: [unix] listening on /dev/shm/uds
2020/12/02 00:50:32 server.go:104: [unix] ListenPacket on /dev/shm/udsu
2020/12/02 00:50:44 server.go:146: [unix] /dev/shm/udsu <-> 127.0.0.1:9053
2020/12/02 00:50:49 server.go:142: [unix] remote write error: write udp [::]:48519: invalid argument
```

```
user@localhost:~$ go/bin/glider -verbose -listen udp://127.0.0.1:1053 -forward unix:///dev/shm/uds
2020/12/02 00:50:35 group.go:182: [group] only 1 forwarder found, disable health checking
2020/12/02 00:50:35 udp.go:62: [udp] listening UDP on 127.0.0.1:1053
2020/12/02 00:50:44 udp.go:106: [udp] 127.0.0.1:53429 <-> /dev/shm/uds
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x70ac45]
goroutine 15 [running]:
github.com/nadoo/glider/proxy/udp.(*UDP).ListenAndServe(0xc000108e40)
	/home/user/go/src/github.com/nadoo/glider/proxy/udp/udp.go:106 +0x465
created by main.main
	/home/user/go/src/github.com/nadoo/glider/main.go:76 +0x1fe
```

```
user@localhost:~$ dig @127.0.0.1 -p 1053 duckduckgo.com
; <<>> DiG 9.16.6-Debian <<>> @127.0.0.1 -p 1053 duckduckgo.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

**Comment by nadoo** [comment]
has been fixed in my env (not committed). 

BTW: you haven't specify a dns server, so you can't dig it.

**Comment by phantomcraft** [comment]
/\ 9053 is the DNS port of Tor, it returns a mapped address for .onion sites, so I can dig when offline.

**Comment by nadoo** [comment]
[glider.zip](https://github.com/nadoo/glider/files/5627884/glider.zip)

you can test the attachment

**Comment by phantomcraft** [comment]
I tested, it works.

I perceived that this new Glider creates many files in the same path of unix socket file and doesn't clean them after its finalization (CTRL+C).

**Comment by nadoo** [comment]
Yes, there are 2 types unix socket files created:
1. the main socket file specified in `unix://path`: it will not be deleted as glider used to be.
2. the socket file for udp sessions: will be deleted 2 minutes later automatically. but if the process is terminated, they will not be deleted.

**Comment by phantomcraft** [comment]
I made a script that forwards the Tor DNS port (here is 19053) to a sandbox and a virtual machine, is basically:

`/opt/glider/glider -listen unix:///dev/shm/tor-fortress-xTtNsLexCIP/dnssock -forward udp://[fd44:7ea1:3dfd:7a67:3fd2:778e:126d:6f15]:19053`

and

`/opt/glider/glider -listen udp://192.168.1.1:19053 -listen udp://[fd00::1]:19053 -forward unix:///dev/shm/tor-fortress-xTtNsLexCIP/dnssock`

The DNS lookup made by the browser (Firefox) needs some seconds (~15) to be performed (should be in 1 second), I believe Glider needs some optimization in this part.

Many files like "dnssocku_blablablah" are created, they are deleted automatically in some seconds, until they last, the DNS lookups are made normally, when all of them are deleted, the lookups are delayed again and this ends until new files are created.

Strangely, lokups made by $dig are made in 1 second.

**Comment by phantomcraft** [comment]
I tested Glider with unix sockets + UDP and perceived that there are problems.

Tor is listening at 127.0.0.1:9053 with its UDP/DNS port ready to receive lookups, I forwarded it to an unix socket and so the unix socket to a UDP port at 127.0.0.1:53 (my DNS port of system) and started browsing with Firefox in some sites, the output log of Glider is long (again the time to enter in any site is 15 seconds...).

Here are they:

===========================

root@localhost:/home/user# glider -verbose -listen unix:///dev/shm/uds -forward udp://127.0.0.1:9053

/\ Log output: https://paste.ee/p/CNf0M

===========================

root@localhost:/home/user# glider -verbose -listen udp://127.0.0.1:53 -forward unix:///dev/shm/uds

/\ Log output: https://paste.ee/p/LqtuV

**Comment by nadoo** [comment]
Will it be better when forwarding to udp://8.8.8.8:53 instead of Tor?

**Comment by phantomcraft** [comment]
My country is a dictatorship that spies DNS queries, that's why I use Tor, but I tested with 8.8.8.8:53

https://paste.ee/p/qvYkT
https://paste.ee/p/lPtFJ

/\ The same problem.

**Comment by nadoo** [comment]
Can't reproduce here...

**Comment by nadoo** [comment]
You can test with specified `interface` to see if it helped:
```
glider -verbose -listen unix:///dev/shm/uds -forward udp://127.0.0.1:9053#interface=127.0.0.1
```

**Comment by phantomcraft** [comment]
I tested with **interface**, it doesn't work too.

I tested the github.com/nadoo/glider/tree/dev and the attachment that you posted above.

**Comment by nadoo** [comment]
I tested with the following commands on debian10:
```
./glider -verbose -listen udp://:5353 -forward unix:///tmp/test.sock
./glider -verbose -listen unix:///tmp/test.sock -forward udp://8.8.8.8:53
```
and `dig @127.0.0.1 -p 5353 www.google.com` several times, no problem here.

**Comment by nadoo** [comment]
The difference between our environments may be ipv6, 

so when you specify the output ip with **#interface=127.0.0.1**:
`-forward udp://127.0.0.1:9053#interface=127.0.0.1`

or **#interface=::1**
`-forward udp://127.0.0.1:9053#interface=::1`

It may have some difference.

**Comment by phantomcraft** [comment]
My system has IPv6 support, but my tyrant ISP doesn't.

I know that **dig** works with this scheme, but the problem is when you use your browser to surf in sites.

Stop your DNS daemon (if you use it), point your /etc/resolv.conf at 127.0.0.1 and put this commands:

```
./glider -verbose -listen udp://127.0.0.1:53 -forward unix:///tmp/test.sock
./glider -verbose -listen unix:///tmp/test.sock -forward udp://8.8.8.8:53
```

Now open your browser and start to open some sites, you'll see the errors happening in the log output and will perceive that sites take ~15 seconds to open. You'll see what I'm talking about.

**Comment by phantomcraft** [comment]
[screencast.zip](https://github.com/nadoo/glider/files/5635902/screencast.zip)

/\ I recorded a screencast showing the problem.

**Comment by nadoo** [comment]
@phantomcraft I see, thank you very much, I'll look into and try to fix it.

**Comment by nadoo** [comment]
It should work now..

**Comment by phantomcraft** [comment]
@nadoo 

I tested and it works now, no errors are showed now. Thank you very much.

**Comment by phantomcraft** [comment]
My first idea was to forward TCP/UDP to unix sockets, now it's possible, that's why I'm closing this issue.

@nadoo

I'm waiting for the next release of Glider. Thank you very much.

**Comment by phantomcraft** [comment]
With tcp:// and udp:// instead of tcptun:// and udptun:// makes Glider a TCP/UDP load balancer if used with a configuration file with multiple forwarders (with Unix Socket support). I have been using haproxy for some time and I'm thinking in replacing it with Glider.

In haproxy there is a balancing strategy called leastconn, you could implement it in Glider. leastconn in haproxy makes the incoming connections use the proxy with least connections first.
