### ISSUE TITLE
[Feature request] full http URL health check

### ISSUE THREAD

**Issue by spinus** [nadoo/glider#195]
Would be great that healthcheck checks something more then only tcp, so you can have healthcheck on the same stack level as traffic.

**Comment by nadoo** [comment]
Hi @spinus , glider has only http health check now(there's a config named `checkwebsite`), and I'm considering to add tcp check ability to it.

**Comment by spinus** [comment]
@nadoo thank you for fast response. Sorry I was not precise in my first post. Big thanks for @kmrozek-shareablee who caught this issue and explained to me.

Here is the check, https://github.com/nadoo/glider/blob/32990ebf77a9222f17fae19b3c01866ed26408d3/rule/group.go#L224

First issue: https://github.com/nadoo/glider/blob/32990ebf77a9222f17fae19b3c01866ed26408d3/rule/group.go#L66 it adds `:80` it it's not present. I'm not sure in that case the string is domain only or actually all URL that I've put into the healthcheck. If it's full string, that the output would be strange.

Second thing is, it puts website into Host header so path is ignored.

If I use `https://example.com/my/path` and if I read the code correctly it produces
```
GET / HTTP/1.1
Host: https://example.com/my/path
```
instead of
```
GET /my/path HTTP/1.1
Host: example.com:443
```

**Comment by rampageX** [comment]
`check HTTP(NOT HTTPS) website address, format: HOST[:PORT], default port: 80`

**Comment by spinus** [comment]
@rampageX I guess that's why I opened the ticket, I would like to have check for full URL

**Comment by nadoo** [comment]
Hi @rampageX, thanks for your kindly help!

Hi @spinus, the health check feature is added at the beginning of this project 3 years ago, it's a good idea to add the ability of full url check.

Intend to keep glider simple and smaller, I use a simple package [conflag](https://github.com/nadoo/conflag) to parse command line and config files. Sometimes I feel it's hard to design the config file format(config key name), as it lack of some features and 
expressions compare to toml/yaml etc. 😢 

I'll look into and improve it later.

**Comment by spinus** [comment]
@nadoo thank you very much! I'm not especially good with coding in go, but I def can help with testing.

**Comment by nadoo** [comment]
You can test full url health check by building the latest commit or just use the dev version docker image `docker pull nadoo/glider:dev`

the config is like:
`check=http://fullurl`
`check=http://fullurl#expect=200`

the default value of check is `http://www.msftconnecttest.com/connecttest.txt#expect=200`

**Comment by spinus** [comment]
@nadoo cheers.

I tested and this seem to work. I didn't catch at first that `expect` doesn't work on body.

My test setup:
```
docker run -ti -v /home/tmp/glider/glider.conf:/app/glider.conf nadoo/glider:dev -listen http://:80 \                                  
  -verbose \
  -strategy rr \
  -check "http://ifconfig.io/host#expect=200" \
  -checkinterval 5 \
  -checkdisabledonly \
  -forward socks4://127.0.0.1:33600 \
  -forward http://192.168.48.1:9988

```
192.168.48.1 is docker host ip (on local machine).
I setup `mitmproxy` with `mitmproxy --listen-host 0.0.0.0 -p 9988` so I could inspect healtcheck

![image](https://user-images.githubusercontent.com/950799/99801786-7f599780-2b2e-11eb-9784-ca32cff61fa4.png)

I was thinking about `expect` feature, if you think some more advanced tests are needed I would consider delegating this check to script. I think haproxy did that approach, so instead of manually defining all scenarios you can pass check to script and react on exit code. Possibly it could be another type like `-check file://./script.bash` or what.

**Comment by nadoo** [comment]
Hi @spinus , thanks for your test. the `expect` only checks the response line `HTTP/1.1 200 OK` for performance reason.

I don't use haproxy, your suggestion of running a script file is very excellent, do we need some parameters to run the script? something like: `./script.bash {FORWARDER_ADDR}` ?

**Comment by spinus** [comment]
@nadoo good question. You can see what they provide http://cbonte.github.io/haproxy-dconv/1.6/configuration.html#4.2-external-check%20command, probably not all are valid/applicable to this case but some ideas worth to copy.

**Comment by nadoo** [comment]
just add some code to support it, we can use config:
`check=file://SCRIPT_PATH`
to run a check script, healthy when exitcode=0, environment variables: FORWARDER_ADDR

**Comment by spinus** [comment]
Works as expected (I used docker :dev again).
I have some setup for integration testing with this using docker-compose and `bats` package. Let me know if you would like me to extract that.

**Comment by spinus** [comment]
thanks for help with this one
