### ISSUE TITLE
[Question] How to use kcptun in ss:// protocol

### ISSUE THREAD

**Issue by TGSAN** [nadoo/glider#197]
I try to use `kcp://salsa20:somekey@server:port?dataShards=10&parityShards=3,ss://rc4-md5:Passw0rd@` to connect a ss-server with kcptun. but it not works. :(

**Comment by nadoo** [comment]
ss over kcp, server
`glider -verbose -listen "kcp://none:key@127.0.0.1:8444?dataShards=10&parityShards=3,ss://rc4-md5:Passw0rd@"`

ss over kcp, client
`glider -verbose -listen :8443 -forward "kcp://none:key@127.0.0.1:8444?dataShards=10&parityShards=3,ss://rc4-md5:Passw0rd@"`

tested and it worked. what is your server's config?

**Comment by TGSAN** [comment]
Server:
front: kcptun (https://github.com/xtaci/kcptun):
`./kcptun-server -c ./kcptun/config.json`
./kcptun/config.json:
```
{
    "target":"127.0.0.1:1081",
    "listen":":8444",
    "mode":"fast2",
    "crypt":"salsa20",
    "key":"somekey"
}
```
back: ss-server (https://github.com/shadowsocks/shadowsocks-libev):
`./ss-server -c ./shadowsocks/config.json`
./shadowsocks/config.json:
```
{
    "server":["[::0]","0.0.0.0"],
    "local_port":1080,
    "server_port":1081,
    "password":"Passw0rd",
    "timeout":60,
    "method":"rc4-md5",
    "fast_open" : true
}
```

**Comment by TGSAN** [comment]
> ss over kcp, server
> `glider -verbose -listen "kcp://none:key@127.0.0.1:8444?dataShards=10&parityShards=3,ss://rc4-md5:Passw0rd@"`
> 
> ss over kcp, client
> `glider -verbose -listen :8443 -forward "kcp://none:key@127.0.0.1:8444?dataShards=10&parityShards=3,ss://rc4-md5:Passw0rd@"`
> 
> tested and it worked. what is your server's config?

Server:
front: kcptun (https://github.com/xtaci/kcptun):
`./kcptun-server -c ./kcptun/config.json`
./kcptun/config.json:
```
{
    "target":"127.0.0.1:1081",
    "listen":":8444",
    "mode":"fast2",
    "crypt":"salsa20",
    "key":"somekey"
}
```
back: ss-server (https://github.com/shadowsocks/shadowsocks-libev):
`./ss-server -c ./shadowsocks/config.json`
./shadowsocks/config.json:
```
{
    "server":["[::0]","0.0.0.0"],
    "local_port":1080,
    "server_port":1081,
    "password":"Passw0rd",
    "timeout":60,
    "method":"rc4-md5",
    "fast_open" : true
}
```

**Comment by nadoo** [comment]
@TGSAN can you change the kcptun-server config `mode` from `fast2` to `fast` and see whether it helped?

**Comment by TGSAN** [comment]
> @TGSAN can you change the kcptun-server config `mode` from `fast2` to `fast` and see whether it helped?

Sadly, it didn't work :(
I got some logs from the server (kcptun-server) and the client (glider):

server: (`<MY CLIENT IP>` is my local client ip)
```
2020/12/01 18:40:18 io: read/write on closed pipe
2020/12/01 18:40:19 remote address: <MY CLIENT IP>:37192
2020/12/01 18:40:19 smux version: 1 on connection: [::]:8444 -> <MY CLIENT IP>:37192
2020/12/01 18:40:23 io: read/write on closed pipe
2020/12/01 18:40:24 remote address: <MY CLIENT IP>:39903
2020/12/01 18:40:24 smux version: 1 on connection: [::]:8444 -> <MY CLIENT IP>:39903
2020/12/01 18:40:29 io: read/write on closed pipe
2020/12/01 18:40:39 io: read/write on closed pipe
2020/12/01 18:40:39 remote address: <MY CLIENT IP>:38356
2020/12/01 18:40:39 smux version: 1 on connection: [::]:8444 -> <MY CLIENT IP>:38356
```

client: (`<MY SERVER IP>` is my remote server ip)
```
2020/12/02 02:51:29 server.go:72: [ss] 192.168.2.111:62142 <-> www.google.com:443 via <MY SERVER IP>:8444
2020/12/02 02:51:30 server.go:72: [ss] 192.168.2.111:62147 <-> www.google.com:443 via <MY SERVER IP>:8444
2020/12/02 02:51:33 server.go:75: [ss] 192.168.2.111:62061 <-> www.google.com:443 via <MY SERVER IP>:8444, relay error: timeout
2020/12/02 02:51:33 forward.go:122: [forwarder] <MY SERVER IP>:8444 recorded 1 failures, maxfailures: 3
2020/12/02 02:51:33 server.go:75: [ss] 192.168.2.111:62065 <-> www.google.com:443 via <MY SERVER IP>:8444, relay error: timeout
2020/12/02 02:51:33 forward.go:122: [forwarder] <MY SERVER IP>:8444 recorded 2 failures, maxfailures: 3
2020/12/02 02:51:34 server.go:75: [ss] 192.168.2.111:62070 <-> ims-prod06.adobelogin.com:443 via <MY SERVER IP>:8444, relay error: timeout
```

**Comment by nadoo** [comment]
Hi @TGSAN , sorry I didn't realize the difference between kcptun-server and kcp protocol, glider supports kcp protocol, but the kcptun-server combines kcp and smux which glider doesn't support currently. 

Do you think it's necessary for glider to compatible with kcptun-server? I'll look into it when I have more time.

**Comment by TGSAN** [comment]
Thanks, look forward to this!

**Comment by TGSAN** [comment]
waiting

**Comment by nadoo** [comment]
Hi @TGSAN , with the version v0.14.0, we can use glider with `kcptun` server like this:

kcptun server:
```bash
glider -verbose -listen :12948
server_linux_arm64 --crypt aes --key mykey --nocomp --target 127.0.0.1:12948
```

glider:
```bash
glider -verbose -listen :8443 -forward kcp://aes:mykey@KCPTUN_SERVER_IP:29900,smux://,http://
```

**Comment by nadoo** [comment]
Note for the flag `--nocomp`, compression is not supported in glider.

**Comment by TGSAN** [comment]
Thanks!
