### ISSUE TITLE
runtime panic / version 0.5.0

### ISSUE THREAD

**Issue by ColorFuzzy** [nadoo/glider#20]
2018/03/18 19:28:09 proxy-socks5 failed to connect to target: dial tcp 185.225.13.106:16212: getsockopt: connection refused
2018/03/18 20:28:14 proxy-mixed peek error: EOF
panic: runtime error: index out of range

goroutine 4 [running]:
main.Addr.String(0x0, 0x0, 0x0, 0x0, 0x0)
        E:/work/codes/go/src/github.com/nadoo/glider/socks5.go:470 +0x29e
main.(*SOCKS5).ListenAndServeUDP(0xc420086400)
        E:/work/codes/go/src/github.com/nadoo/glider/socks5.go:184 +0x686
created by main.(*MixedProxy).ListenAndServe
        E:/work/codes/go/src/github.com/nadoo/glider/mixed.go:45 +0x58

**Comment by nadoo** [comment]
Hi @ColorFuzzy , that because of a invalid udp socks5 request. you can try with the latest commit and see whether that fixed. 

I can compile a binary for you if you need. (need to know your os type)

**Comment by ColorFuzzy** [comment]
Thanks, just a small bug, current binary works good. It would be better if you recover from any panic instead of crashing the glider process.

**Comment by nadoo** [comment]
Thanks for your advice! :p
