### ISSUE TITLE
[Bug] Rule: cidr not working

### ISSUE THREAD

**Issue by LazyZhu** [nadoo/glider#209]
Rule file:

`include=chnroute.txt`

chnroute.txt
```
cidr=0.0.0.0/8
cidr=1.0.1.0/24
cidr=1.0.2.0/23
cidr=1.0.8.0/21
cidr=1.0.32.0/19
cidr=1.1.0.0/24
cidr=1.1.2.0/23
cidr=1.1.4.0/22
...
```

**Comment by nadoo** [comment]
works here without problem, more details please! what is your main config? glider runs as transparent proxy(redir) or not? if you use redir mode, you must config your ipset and iptables.

**Comment by LazyZhu** [comment]
Main config:
```
verbose=true

listen=http://127.0.0.1:8080
listen=socks5://127.0.0.1:1080

forward=ss-server

strategy=lha

maxfailures=3

check=http://www.msftconnecttest.com/connecttest.txt#expect=200
checkinterval=1800
checktimeout=20
checktolerance=20
checkdisabledonly=false

dnsserver=127.0.0.1:53

dnsalwaystcp=true

dnstimeout=5

dnsmaxttl=21600
dnsminttl=3600
dnscachesize=4096

include=rules.d/dnsrecord.conf

rulefile=rules.d/bypass.rule
```

**Comment by nadoo** [comment]
the http & socks5 proxy resolves domain remotely, so can't apply ip or cidr rule locally.

**Comment by LazyZhu** [comment]
I know, Clash and V2Ray can resolve the domains to IPs then apply the rules, which sacrificed speed for accuracy.
Since it looks like not a bug at all, i'll close the issue now.
