### ISSUE TITLE
usage of udp listener in trojan protocol 

### ISSUE THREAD

**Issue by isbzx** [nadoo/glider#213]
I would like to use GLIDER as proxy server to support both TCP and UDP -- which mentioned in protocol description table

I use command with this line
`glider -listen "trojan://Password@:10000?cert=/cert.pem&key=/key.pem&fallback=127.0.0.1"`

In my test the UDP request failed though the TCP server works well
[lsof -i] on server shows tcp port and udp port opened by glider.

already go through the help file and sample config but find nothing.
Is there any parameter I missed to use trojan protocol both on TCP and UDP ？

attach verbose output when using udp request 

> `Dec 17 21:25:01 Cloud glider[20728]: 2020/12/17 21:25:01 server.go:225: [trojan] ClientIP:62202 <-tcp-> ServerIP:10000 - [::]:36156 <-udp-> 0.0.0.0:0`
> `Dec 17 21:25:05 Cloud glider[20728]: 2020/12/17 21:25:05 server.go:225: [trojan] ClientIP:62204 <-tcp-> ServerIP:10000 - [::]:46888 <-udp-> 0.0.0.0:0`
> `Dec 17 21:25:09 Cloud glider[20728]: 2020/12/17 21:25:09 server.go:225: [trojan] ClientIP:62206 <-tcp-> ServerIP:10000 - [::]:45698 <-udp-> 0.0.0.0:0`
> `Dec 17 21:25:10 Cloud glider[20728]: 2020/12/17 21:25:10 server.go:225: [trojan] ClientIP:62208 <-tcp-> ServerIP:10000 - [::]:38554 <-udp-> 0.0.0.0:0`
> `Dec 17 21:25:12 Cloud glider[20728]: 2020/12/17 21:25:12 server.go:225: [trojan] ClientIP:62210 <-tcp-> ServerIP:10000 - [::]:40033 <-udp-> 0.0.0.0:0`

**Comment by nadoo** [comment]
Hi @isbzx , sorry for late response here, what client did you use for testing?
