### ISSUE TITLE
Direct routing whenever forwarder's down

### ISSUE THREAD

**Issue by n0ise9914** [nadoo/glider#214]
Is there any way to let the dns traffic route directly (outside the tunnel) whenever all forwarder server's are down?

**Comment by phantomcraft** [comment]
No, there is no way.

**Comment by phantomcraft** [comment]
If your forwarder doesn't support UDP, you can use the option -dnsalwaystcp to make the DNS requests use only TCP transport.

**Comment by n0ise9914** [comment]
I'm using glider as a always running deamen to bypass dns pollution (defined in network adapter) through a running sock5 tunnel on same machine, but turning down the tunnel causes the network to collapse, i've solved the problem via setting second public DNS server at adapter level, everything works fine (handled by os itself)
But i hink adding the feature to forward traffic thought a transparent (direct) forwarder on failover's will be fine.

Thank's for your response.
