### ISSUE TITLE
FQDN resolution - help request/possible "bug"

### ISSUE THREAD

**Issue by AsharLohmar** [nadoo/glider#217]
Hi 
let me first explain the setup/configuration:
 - I'm on Windows 10 using WSL (1),
 - I have a VirtualBox with Alpine 3.13, managed with vagrant, that I'm using as a docker machine
 - I'm using the latest glider in "alpine:latest" docker containers (which is actually the same 3.13) 
 - I have various of these containers in which I'm running different VPN client software along with a glider
       The scope is network isolation, some of the VPN fiddle with the "local" networking making everything pass through it.
       So, the VPN client (vpnc, openfortinet, openvpn, ...) runs  and connects allowing access to what ever, and in the background there's a glider running with just `/glider -listen :<some port>`. by connecting to it you get access to anything the VPN might've given you access to.
 - I have an another container running just a glider instance that has various `*.rule` files, basically one for each VPN network, with rules for IPs, CIDRs and domains and forwarding them to glider of the appropriate VPN container. I call this the "proxy container". 
 - on top of everything, I'm using a `proxy.pac` file (locally hosted) configured in the 'Internet Options' so the browsers would send the trafic for the needed destinations through the proxy container. Also, in the ~/.ssh/config ... for all the interested host I'm using `ProxyCommand` to make everything pass through the same proxy.
 - 
Everything works perfectly, and I thank you a lot for that, but here comes the little issue I have.
In one of these VPN the DNS resolution doesn't work, so I have some FQDN's locally defined in "/etc/hosts" (both Windows and WSL) and eventually even inside the VPN container of that network. When I'm trying to browse those FQDNs in my browser, looking at the gliders' logs ... I can see the request arriving to the proxy container and then correctly forwarded to the vpn container, but here it just fails with: `, error in dial: dial tcp: i/o timeout`. 

**proxy log**
```
2021/01/29 08:54:07 server.go:85: [socks5] 192.168.56.1:60846 <-> www.example.com:443 via vpn_container:2226
2021/01/29 08:54:15 server.go:88: [socks5] 192.168.56.1:60846 <-> www.example.com:443 via vpn_container:2226, relay error: readfrom tcp 192.168.253.2:8443->192.168.56.1:60846: splice: connection reset by peer
```
**vpn container**
```
2021/01/29 08:53:45 server.go:80: [socks5] 192.168.253.2:44327 <-> www.example.com:443 via DIRECT, error in dial: dial tcp: i/o timeout
```
I must add that:
 - browsing by using the IP address of that FQDN everything works correctly.
 - doing a `wget/curl` from inside the vpn container, without passing through glider, using the FQDN works. The ping also works ... for whatever it's worth.
 - also ... with other containers where DNS resolution works ... everything works

I wouldn't had written/reported this, but until recently this setup had worked ...  unfortunately there were multiple things that changed ... virtualbox version, docker version, glider version, alpine version ... 
I'm not even sure if it's an glider's issue (somehow not resolving the FQDN or something), maybe something changed and I might need to add some parameter to the running instance or maybe it's an "OS issue" some change in the alpine's configuration that doesn't allow the usage of FQDNs defined (only) in /etc/hosts ... or might be some change in the docker and or virtualbox ... I have no idea.

**Comment by AsharLohmar** [comment]
I've did some `strace` for the various named programs ... seems that (at least) `wget` and `ping` first read from `/etc/hosts`, and only afterwards, if no result came up, the read the `/etc/resolv.conf` and "talk" to the configured name servers, whilst glider only talks to the nameservers. 

I've attached the said `strace` outputs. 

[strace_wget.txt](https://github.com/nadoo/glider/files/5892948/strace_wget.txt)
[strace_ping.txt](https://github.com/nadoo/glider/files/5892949/strace_ping.txt)
[strace_glider.txt](https://github.com/nadoo/glider/files/5892950/strace_glider.txt)

**Comment by AsharLohmar** [comment]
I've managed to circumvent my problem, by enabling the `dns` in glider and adding `dnsrecord`s

```
dns=:5553
dnsrecord=www.example.com/1.2.3.4
```

**Comment by nadoo** [comment]
Hi @AsharLohmar , thanks for your report.

On linux, when glider's builtin in dns is enabled, it will use builtin dns to resolve domains, so your workaround worked.

Anyway, in your previous description, there's a `possible bug` that glider ignores `/etc/hosts`, I've found this issue of golang: https://github.com/golang/go/issues/22846 , does it matter?

**Comment by AsharLohmar** [comment]
Hi @nadoo,
my "solution" only worked for one/that container. I might've missed some other option, but on a second container where I needed both the records from the real DNS and "dirty records" ... this didn't work as expected.

The indications from the GO's issue page where on point ... the alpine container/image didn't have any "/etc/nsswitch.conf" file and, after I've added the `echo "hosts: files dns" > /etc/nsswitch.conf` to the list of commands I'm using to build my base image,  everything worked just fine. Most likely this might apply to other distros also.

So this was definitely not an "glider" issue, and not even of the GO language, but an issue of the underlying OS's configuration.
I think that adding some "advisory" or at least a "foot note" somewhere could be a nice idea.

Thanks again for all the work you've put in this project and into solving my issue.
