### ISSUE TITLE
[Feature request] Options for binding to specific address or network interface when using direct connections

### ISSUE THREAD

**Issue by phantomcraft** [nadoo/glider#218]
Binding to a specific IPv4/IPv6 address would be useful if someone has multiple network interfaces and want all of Glider's outgoing connection to use a single one. It could be two options, one for selecting a IPv4 address and other for selecting an IPv6 one.

Binding to a specific network interface would be useful if someone has different routes for destination reachable from different interfaces and someone do not want to setup a source routing for some reason. It requires root privileges.

These options are already implemented in a program called 3proxy, but there is a issue in this project which prevents access to loopback device (127.0.0.1 and ::1) when binding the program to a specific network interface.

==> https://github.com/z3APA3A/3proxy/blob/master/man/3proxy.cfg.3#L161

==> https://github.com/z3APA3A/3proxy/blob/master/man/3proxy.cfg.3#L158

**Comment by emptyteeth** [comment]
Hi there, you might want to try this one.  

https://github.com/nadoo/glider/blob/master/config/glider.conf.example#L245-L251

**Comment by phantomcraft** [comment]
Thanks @emptyteeth, I will try it.
