### ISSUE TITLE
If there is an @ symbol in my ss password, the glider cannot start

### ISSUE THREAD

**Issue by 669800** [nadoo/glider#222]
** ./glider -listen udp://:53 -forward ss://method:pa@s123@s@1.1.1.1:8443,udp://8.8.8.8:53**

**Comment by nadoo** [comment]
Hi @669800 , you can try url encoding `@->%40`, ref: https://www.w3schools.com/tags/ref_urlencode.asp

BTW, if you want a local dns server, you can also start glider like:
```
./glider -verbose -dns :53 -dnsserver 8.8.8.8:53 -forward ss://method:pa%40s123%40s@server:port
```

**Comment by 669800** [comment]
> Hi @669800 , you can try url encoding `@->%40`, ref: https://www.w3schools.com/tags/ref_urlencode.asp
> 
> BTW, if you want a local dns server, you can also start glider like:
> ```
> ./glider -verbose -dns :53 -dnsserver 8.8.8.8:53 -forward ss://method:pa%40s123%40s@server:port
> ```

    Thank you,mi hermano
