### ISSUE TITLE
about Trojan path

### ISSUE THREAD

**Issue by 669800** [nadoo/glider#225]
---**----bash: [key=/home/1.key]: No such file or directory
2021/02/12 10:07:29 [trojan] cert and key file path must be spcified--------

**Comment by nadoo** [comment]
`[key=/home/1.key]: No such file or directory`, the key file path does not exist.

**Comment by 669800** [comment]
> `[key=/home/1.key]: No such file or directory`, the key file path does not exist.

How can I contact you through social software?
