### ISSUE TITLE
 ./g -listen trojan://pass@0.0.0.0:444?cert=/home/q.cer&key=/home/q.key&fallback=1.1.1.1
[3] 19536
[4] 19537
[1]   Exit 1                  ./g -listen trojan://pass@0.0.0.0:444?cert=./home./1.cer
[2]   Done                    key=./home./1.key
[root@fityoiuyigt7i7g79979 ~]# 2021/02/12 15:06:23 [trojan] cert and key file path must be spcified

### ISSUE THREAD

**Issue by 669800** [nadoo/glider#226]
what is？ --------[trojan] cert and key file path must be spcified--------

**Comment by nadoo** [comment]
Please, make the issue tile more clear.

BTW, if you start glider with command line in bash shell, you should quote the parameters like:
```
./gliger -verbose -listen "trojan://pass@0.0.0.0:444?cert=/home/q.cer&key=/home/q.key&fallback=1.1.1.1"
```

**Comment by 669800** [comment]
> Please, make the issue tile more clear.
> 
> BTW, if you start glider with command line in bash shell, you should quote the parameters like:
> ```
> ./gliger -verbose -listen "trojan://pass@0.0.0.0:444?cert=/home/q.cer&key=/home/q.key&fallback=1.1.1.1"
> ```

Thank you,mi hermano.
