### ISSUE TITLE
Problem--About tun 

### ISSUE THREAD

**Issue by 669800** [nadoo/glider#227]
---------./gr -verbose -listen “ss://AEAD_CHACHA20_POLY1305:mypassword@127.0.0.1:8443,service=dhcpd,eth1,192.168.50.100,192.168.50.199”---------It not start.

**Comment by nadoo** [comment]
glider -verbose -listen="ss://AEAD_CHACHA20_POLY1305:mypassword@127.0.0.1:8443" -service="dhcpd,eth1,192.168.50.100,192.168.50.199"

**Comment by 669800** [comment]
> glider -verbose -listen="ss://AEAD_CHACHA20_POLY1305:mypassword@127.0.0.1:8443" -service="dhcpd,eth1,192.168.50.100,192.168.50.199"

Ok i try it,
