### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by 669800** [nadoo/glider#228]
server.go:33: [ss] listening TCP on :8443
2021/02/13 14:14:09 server.go:94: [ss] listening UDP on :8443
2021/02/13 14:14:09 dhcpd.go:40: [dhcpd] found existing dhcp server on interface eth0, service exiting

**Comment by nadoo** [comment]
what's the problem?

**Comment by 669800** [comment]
> what's the problem?

Cannot access server intranet ip from client
