### ISSUE TITLE
Shadowsocks proxy doesn't work with Android SS client v4.5.7

### ISSUE THREAD

**Issue by Stat1cV01D** [nadoo/glider#23]
When I try to connect to gilder via Android Shadowsocks client with these settings:
```
#changes from glider.conf.example
listen=socks5://:1080
listen=ss://AEAD_CHACHA20_POLY1305:pass@:8448
listen=dnstun://:5353=8.8.8.8:53
forward=socks5://user:pass@<ip>:1080
```
With DNS forwarding on glider then gives me:
```
2018/04/28 14:58:58 proxy-ss-udp remote dial error: EOF
2018/04/28 14:59:03 proxy-ss-udp remote dial error: EOF
```
How can I fix it?

**Comment by Stat1cV01D** [comment]
Ok, seems like "DNS Forwarding" feature in Android client is causing this issue. But how do I correctly set this up?

**Comment by nadoo** [comment]
Hi @Stat1cV01D , does your upstream socks5 server support udp forwarding?

**Comment by Stat1cV01D** [comment]
@nadoo I am not sure if I get it right, but it does support P2P services and Skype (I am not hosting the server). I think there might be some UDP shenanigans involved.

**Comment by nadoo** [comment]
Maybe you can use glider to serve dns request(listen on port
 53), and set dns server to 127.0.0.1 on android client.

**Comment by Stat1cV01D** [comment]
Thanks, I'll try. Although as I said it works fine with the aforementioned option turned off.
And thanks you for your work. I am looking forward to contributing to this or a connected project at some time in the future.
