### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by 669800** [nadoo/glider#232]
v2ray+ws Client customize Encryption?

E.g I want aes-128-gvm.
````
./glider -verbose -listen :10805 -forward "ws://1.1.1.1:80/downloads?host=microsoft.com,vmess://980a-50b-36a-ac6-caeb1@?alterID=2"
````

**Comment by nadoo** [comment]
please see the document or just see the help message:
`./glider -h`

```
VMess scheme:
  vmess://[security:]uuid@host:port?alterID=num
```

```
./glider -verbose -listen :10805 -forward "ws://1.1.1.1:80/downloads?host=microsoft.com,vmess://aes-128-gcm:980a-50b-36a-ac6-caeb1@?alterID=2"
```

BTW, please make the title more clearly to describe what is your problem, thanks!

**Comment by qqqqqqrrrrhh123a** [comment]
i have same ws issues,help me https://github.com/nadoo/glider/issues/270
