### ISSUE TITLE
About request forwarding

### ISSUE THREAD

**Issue by 669800** [nadoo/glider#233]
```
./glider -listen socks5://:1080 -forward ss://method:pass@server1:port1 -forward ss://method:pass@server2:port2
````
Can the traffic be forwarded in sequence?  server1 request to server2.

**Comment by 669800** [comment]
E.g
![68747470733a2f2f67696e7565727a682e6769746875622e696f2f696d616765732f676f73745f30332e706e67.jpg](https://user-images.githubusercontent.com/27992255/108392141-5f309600-724d-11eb-827a-2da9f5680ad3.jpg)

**Comment by nadoo** [comment]
Please see the document about proxy chain.

**Comment by nadoo** [comment]
'''
./glider -listen socks5://:1080 -forward ss://method:pass@server1:port1,ss://method:pass@server2:port2
'''
