### ISSUE TITLE
How to write Vless server and client ？

### ISSUE THREAD

**Issue by 669800** [nadoo/glider#236]

**Comment by emptyteeth** [comment]
Please DO read the [config examples](https://github.com/nadoo/glider/blob/master/config/glider.conf.example)

[vless server](https://github.com/nadoo/glider/blob/v0.13.1/config/glider.conf.example#L66-L73)
[vless client](https://github.com/nadoo/glider/blob/v0.13.1/config/glider.conf.example#L122-L123)
