### ISSUE TITLE
Create tcp/udp tunnel config file with V0.13.x

### ISSUE THREAD

**Issue by abitfun** [nadoo/glider#239]
in old version (e.g. V0.12.3), I used to wrote following in a config file to create tcp/udp tunnel:

listen=tcptun://:1234=remote:5678
listen=udptun://:1234=remote:5678

after update to V0.13.x, I can't find new rule for tcp/udp tunnel in the example, then tried with:

listen=tcp://:1234=remote:5678
listen=udp://:1234=remote:5678

or

listen=tcp://:1234 -forward tcp://remote:5678
listen=udp://:1234 -forward udp://remote:5678

however both cannot work. 
Is there new rule for tcp/udp tunnel ?
Thanks in advance!

**Comment by nadoo** [comment]
udp: 
`glider -verbose -listen udp://:53 -forward udp://8.8.8.8:53`
tcp:
`glider -verbose -listen tcp://:53 -forward tcp://8.8.8.8:53`

test:
`dig @127.0.0.1 www.google.com`
`dig @127.0.0.1 www.google.com +tcp`

works without problem.

**Comment by nadoo** [comment]
config file:
```
verbose
listen=udp://:53
forward=udp://8.8.8.8:53
```

**Comment by abitfun** [comment]
thanks for quick reply!
you are right, it works fine with 
glider -verbose -listen tcp://:1234 -forward tcp://remote:5678
glider -verbose -listen udp://:1234 -forward udp://remote:5678

but with a config file ,if I wrote tcp only:
listen=tcp://:1234
forward=tcp://remote:5678
it works fine.

but is I wore additional udp rules, as:
listen=tcp://:1234
forward=tcp://remote:5678
listen=udp://:1234
forward=udp://remote:5678
then both will not work.

**Comment by nadoo** [comment]
In current version, we should use multiple config files and run multiple instances to achieve the goal. Maybe I can add some features similar to the 'tcptun' later.

**Comment by abitfun** [comment]
Success with 2 instances, one deals with tcp, and another deals with udp.
much thanks!

**Comment by abitfun** [comment]
issue closed.
