### ISSUE TITLE
trojanc ws tls not work

### ISSUE THREAD

**Issue by 669800** [nadoo/glider#241]
`2021/03/06 14:51:56 client.go:60: [trojan]: dial to :443 error: [ws] error in ws handshake, got wrong response: HTTP/1.1 403 Forbidden                                                    2021/03/06 14:51:56 server.go:80: [socks5] 127.0.0.1:39106 <-> zen.yandex.com:443 via 1.0.0.1:443,nefed.com,:443, error in dial: [ws] error in ws handshake, got wrong response: HTTP/1.1 403 Forbidden                                                  2021/03/06 14:51:57 client.go:60: [trojan]: dial to :443 error: [ws] error in ws handshake, got wrong response: HTTP/1.1 403 Forbidden`

**Comment by 669800** [comment]
`2021/03/06 15:01:35 tls.go:182: [tls] dial to nefed.com:443 error: dial tcp: lookup nefed.com on [::1]:53: read udp [::1]:43943->[::1]:53: read: connection refused                         2021/03/06 15:01:35 client.go:60: [trojan]: dial to :443 error: dial tcp: lookup nefed.com on [::1]:53: read udp [::1]:43943->[::1]:53: read: connection refused                           2021/03/06 15:01:35 server.go:80: [socks5] 127.0.0.1:39982 <-> zen.yandex.com:443 via nefed.com:443,:443, error in dial: dial tcp: lookup nefed.com on [::1]:53: read udp [::1]:43943->[::1]:53: read: connection refused`

**Comment by qqqqqqrrrrhh123a** [comment]
i have same ws issues,help me https://github.com/nadoo/glider/issues/270
