### ISSUE TITLE
vmess can't run on glider while run well on x2rayN

### ISSUE THREAD

**Issue by iaston** [nadoo/glider#243]
log on same time:
![x2ray](https://user-images.githubusercontent.com/11807657/110413810-7e427b00-80c9-11eb-9f32-e8860d62afd6.png)
![glider](https://user-images.githubusercontent.com/11807657/110413814-7edb1180-80c9-11eb-97dc-0abfff5ea5c9.png)

**Comment by nadoo** [comment]
Do you use vmess aead(alertid=0)? try to set alterid >= 1.

**Comment by iaston** [comment]
Is this a bug? Will it be repaired in the future?

**Comment by nadoo** [comment]
No, it's not a bug. Since v2ray [v4.28.0](https://github.com/v2ray/v2ray-core/releases/tag/v4.27.0), VMess AEAD will be used when alterId=0, and it's not supported by glider. 

As you use tls and websocket as the transport layer, there's no need to use vmess aead, just set alterID>=1.
