### ISSUE TITLE
Shadowsocks run on etc0 in server how to use?

### ISSUE THREAD

**Issue by 669800** [nadoo/glider#245]
Client sent web request http://10.0.22.20 to shadowsocks server Nginx,

**Comment by nadoo** [comment]
Can not get your question..

**Comment by 669800** [comment]
> Can not get your question..

I have solved this problem, thank you.

**Comment by yuanjie-ai** [comment]
> > Can not get your question..
> 
> I have solved this problem, thank you.

老兄 咋搞的
