### ISSUE TITLE
ssh connection timed out 

### ISSUE THREAD

**Issue by 669800** [nadoo/glider#251]
After ssh is connected normally for a period of time, a timeout occurs and the ssh server does not respond!

**Comment by nadoo** [comment]
Closing as v0.16.0 released: https://github.com/nadoo/glider/releases/tag/v0.16.0

Feel free to reopen this issue if you need.

**Comment by 669800** [comment]
> Closing as v0.16.0 released: https://github.com/nadoo/glider/releases/tag/v0.16.0
> 
> 
> 
> Feel free to reopen this issue if you need.

I try
