### ISSUE TITLE
Socks5 not working ?

### ISSUE THREAD

**Issue by lemaitre-dev** [nadoo/glider#252]
I can make my http or socks5 proxy server work in http but not in socks5 with the same conf format. So I think the socks5 forwarder has a problem, can you confirm please ?

the message code is: 
 FAILED. error: proxy: SOCKS5 proxy at zproxy.lum-superproxy.io:22225 has unexpected version 72

and my configuration in format like this:
forward=socks5://lum-customer-hl_c19fed53-zone-static-ip-179.61.130.155:password@zproxy.lum-superproxy.io:22225

**Comment by nadoo** [comment]
You can test your socks5 server with other clients to see whether it worked, e.g.:
`
curl -x socks5://lum-customer-hl_c19fed53-zone-static-ip-179.61.130.155:password@zproxy.lum-superproxy.io:22225 www.apple.com
`
