### ISSUE TITLE
NAT type downgrade when glider as server

### ISSUE THREAD

**Issue by TGSAN** [nadoo/glider#253]
## Test A
ss-libev (server) --> ss-libev (client) : NAT TYPE B  

## Test B
glider (server) --> ss-libev (client) : NAT TYPE F  
  
The NAT type is known to degrade when glider is used as a server (clients uniformly use ss-libev), but haven't tested if the same result is achieved when Glider is the client.

**Comment by rampageX** [comment]
UDP

**Comment by TGSAN** [comment]
Thank you so much for your dedication, I can't wait to try it out! 👍
