### ISSUE TITLE
[Question] What is the command to simply start a SOCKS5 server with username:password so that, say, a browser can connect to it?

### ISSUE THREAD

**Issue by NightMachinary** [nadoo/glider#26]
What is the command to simply start a SOCKS5 server with username:password so that, say, a browser can connect to it?
I tried ` glider -listen socks5://:1080 -verbose`, but this didn't work. (I skipped the username and password part because I couldn't get the basic version running in the first place. :D)

**Comment by nadoo** [comment]
Hi @NightMachinary , `glider -listen socks5://:1080 -verbose` works well: 
![image](https://user-images.githubusercontent.com/287492/40459929-ba880bb4-5f36-11e8-93f7-73499951e227.png)
Test with glider-v0.5.2 & Chrome with SwitchyOmega extension.

BTW: username:password auth not implemented in socks5 server mode now, maybe I'll add this feature later.

**Comment by NightMachinary** [comment]
@nadoo Hmm strange ... Perhaps it's blocked by my Iranian ISP, though I think I tested it with another VPN connected as well ... Thanks!

**Comment by nadoo** [comment]
Maybe you can try ss protocol, it was designed to across the firewall.

**Comment by NightMachinary** [comment]
Yeah, ShadowsocksR works great. “SSH -D” works, too. Stunnel OpenVPN  ans
Cisco, as well. But SOCKS5 is easier to connect to in some situations.
