### ISSUE TITLE
http proxy not working

### ISSUE THREAD

**Issue by bretondeyonna** [nadoo/glider#261]
HTTP/1.1 502 ERROR
* no chunk, no close, no size. Assume close to signal end

**Comment by bretondeyonna** [comment]
curl -x 127.0.0.1:8443 --proxy-user test:test123 -v "http://lumtest.com/myip.json"

**Comment by nadoo** [comment]
Hi @bretondeyonna ,  how do you use glider here?  glider running as proxy server `127.0.0.1:8443` ?

**Comment by bretondeyonna** [comment]
hi,using glider as a proxy server access is normal, forwarding luminati proxy will result in 502 errors

**Comment by nadoo** [comment]
the upstream http proxy server must support http `CONNECT` method.

**Comment by bretondeyonna** [comment]
Thank you
