### ISSUE TITLE
Request tls ssh support

### ISSUE THREAD

**Issue by 669800** [nadoo/glider#262]
example:
-verbose -listen socks5://127.0.0.1:60000 -forward tls://103.253.24.42:443?skipVerify=true&serverName=www.amazon.com,ssh://fastssh.com-owjveve:ajwvrv@

**Comment by nadoo** [comment]
do you mean ssh over tls, I think it's already supported, any problems?

**Comment by 669800** [comment]
> do you mean ssh over tls, I think it's already supported, any problems?

```

./glider -verbose -listen socks5://127.0.0.1:60000 -forward tls://103.253.24.42:443?skipVerify=true&serverName=www.amazon.com,ssh://fastssh.com-owjveve:ajwvrv@

```

It is not working properly!


Please tell me the correct way of writing.

**Comment by nadoo** [comment]
server:
```bash
glider -verbose -listen "tls://:443?cert=YourCertFile&key=YourKeyFile" -forward "tcp://127.0.0.1:22"
```

client:
```bash
glider -verbose -listen socks5://:60000 -forward "tls://103.253.24.42:443?skipVerify=true&serverName=www.amazon.com,ssh://fastssh.com-owjveve:ajwvrv@"
```

**Comment by 669800** [comment]
> server, assuming your sshd is listening on port 22:
> 
> ```shell
> glider -verbose -listen "tls://:443?cert=YourCertFile&key=YourKeyFile" -forward "tcp://127.0.0.1:22"
> ```
> 
> client:
> 
> ```shell
> glider -verbose -listen socks5://:60000 -forward "tls://103.253.24.42:443?skipVerify=true&serverName=www.amazon.com,ssh://fastssh.com-owjveve:ajwvrv@"
> ```

I try to see if it works.
