### ISSUE TITLE
[Code Style] Use official package to split strings

### ISSUE THREAD

**Issue by fakeboboliu** [nadoo/glider#263]
https://github.com/nadoo/glider/commit/ceb8b82df83e7d85059522c8f3a1abf6625a995f#diff-657be1b1e48ca1e20ce6a6a3f2b67f37906c45c305ecade9a451f8d136149db0R147

You do not need:
```golang
if idx := strings.IndexByte(s, ','); idx != -1 {
    server, chain = s[:idx], s[idx+1:]
}
```

Use this instead:
```golang
- transport := strings.Split(s, ",")
+ transport := strings.SplitN(s, ",", 2)
```

**Comment by nadoo** [comment]
Hi @fakeboboliu , I didn't realize that before -_-, thanks for your kindly help!
