### ISSUE TITLE
ssh client have some bug

### ISSUE THREAD

**Issue by kaileung** [nadoo/glider#264]
panic: runtime error: invalid memory address or nil pointer dereference

golang.org/x/crypto/ssh.NewClient.func1
    /home/runner/go/pkg/mod/golang.org/x/crypto@v0.0.0-20210503195802-e9a32991a82e/ssh/client.go:62+0x30
created by golang.org/x/crypto/ssh.NewClient
    /home/runner/go/pkg/mod/golang.org/x/crypto@v0.0.0-20210503195802-e9a32991a82e/ssh/client.go:61+0xf3

window10/ glider0.14.0

**Comment by nadoo** [comment]
Hi @kaileung , may I know how to reproduce this bug?
