### ISSUE TITLE
can glider run on android device?

### ISSUE THREAD

**Issue by qqqqqqrrrrhh123a** [nadoo/glider#267]
can glider run on android device?

**Comment by nadoo** [comment]
Not officially supported, but I think it's not difficult, you can give it a try.

**Comment by quaggalinux** [comment]
@qqqqqqrrrrhh123a , I alreay installed termux in my android phone from play store, and then I use termux to install linux official distributions. In this case I installed Ubuntu (hirsute) . After that I wget glider_0.15.0_linux_arm64.tar.gz from github in my phone's ubuntu. So the glider works great. I think other android devices are the same when they can use play store as well.
https://wiki.termux.com/wiki/PRoot#Installing_Linux_distributions
