### ISSUE TITLE
"Too many open files" error for socks5 proxy

### ISSUE THREAD

**Issue by Stat1cV01D** [nadoo/glider#27]
Occasionally I receive the errors like this:
`proxy-socks5 failed to accept: accept tcp [::]:1080: accept4: too many open files`
I've read that this might be a result of poor timeout management for TCP connections.

You might wanna see the issues like these - containous/traefik#1322 , OpenBazaar/openbazaar-go#717 - to help get the idea of what to fix in code and/or Readme. I wish I could implement this myself but I'm afraid I don't have enough grasp of Go and the project.

**Comment by nadoo** [comment]
Hi @Stat1cV01D , could you please show me the result of command `ulimit -a`?

Try first execute `ulimit -n 102400` and then start glider in the same shell session.

And you can also follow the instruction from this article: https://easyengine.io/tutorials/linux/increase-open-files-limit/ and see whether that helps.

**Comment by Stat1cV01D** [comment]
@nadoo, yeah I did that as well (limit is now 500000 open files) but I also tried switching proxy servers back and forth so I can't reproduce the bug yet. Might tell in a day or two hopefully.
I suppose timeout options could be useful though.

**Comment by Stat1cV01D** [comment]
About that update: I didn't experience problems since then. I guess, the issue may be considered solved.
