### ISSUE TITLE
"ws,vmess" shows   relay error: unexpected EOF,ws path is /. ws+vmess 

### ISSUE THREAD

**Issue by qqqqqqrrrrhh123a** [nadoo/glider#270]
command is 
glider -rules-dir=rules.d -check=disabled -verbose -dnsserver=8.8.8.8:53 -listen=:10808 -forward="ws://52.199.19.113:80/,vmess://f830d6df-0a72-4fd4-c434-57a0fe1c811e@52.199.19.113:80?alterID=64"

shared url is:
vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogIj8iLA0KICAiYWRkIjogIjUyLjE5OS4xOS4xMTMiLA0KICAicG9ydCI6ICI4MCIsDQogICJpZCI6ICJmODMwZDZkZi0wYTcyLTRmZDQtYzQzNC01N2EwZmUxYzgxMWUiLA0KICAiYWlkIjogIjY0IiwNCiAgInNjeSI6ICJhdXRvIiwNCiAgIm5ldCI6ICJ3cyIsDQogICJ0eXBlIjogIm5vbmUiLA0KICAiaG9zdCI6ICIiLA0KICAicGF0aCI6ICIvIiwNCiAgInRscyI6ICIiLA0KICAic25pIjogIiINCn0=

server info:
{
  "v": "2",
  "ps": "?",
  "add": "52.199.19.113",
  "port": "80",
  "id": "f830d6df-0a72-4fd4-c434-57a0fe1c811e",
  "aid": "64",
  "scy": "auto",
  "net": "ws",
  "type": "none",
  "host": "",
  "path": "/",
  "tls": "",
  "sni": ""
}

shows bug:
relay error: unexpected EOF

i can use this config on v2rayn sucessfully but glider failed,anything wrong?

**Comment by qqqqqqrrrrhh123a** [comment]
> 
> 
> command is
> glider -rules-dir=rules.d -check=disabled -verbose -dnsserver=8.8.8.8:53 -listen=:8080 -forward="ws://52.199.19.113:80/,vmess://f830d6df-0a72-4fd4-c434-57a0fe1c811e@52.199.19.113:80?alterID=64"
> 
> shared url is:
> vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogIj8iLA0KICAiYWRkIjogIjUyLjE5OS4xOS4xMTMiLA0KICAicG9ydCI6ICI4MCIsDQogICJpZCI6ICJmODMwZDZkZi0wYTcyLTRmZDQtYzQzNC01N2EwZmUxYzgxMWUiLA0KICAiYWlkIjogIjY0IiwNCiAgInNjeSI6ICJhdXRvIiwNCiAgIm5ldCI6ICJ3cyIsDQogICJ0eXBlIjogIm5vbmUiLA0KICAiaG9zdCI6ICIiLA0KICAicGF0aCI6ICIvIiwNCiAgInRscyI6ICIiLA0KICAic25pIjogIiINCn0=
> 
> server info:
> {
> "v": "2",
> "ps": "?",
> "add": "52.199.19.113",
> "port": "80",
> "id": "f830d6df-0a72-4fd4-c434-57a0fe1c811e",
> "aid": "64",
> "scy": "auto",
> "net": "ws",
> "type": "none",
> "host": "",
> "path": "/",
> "tls": "",
> "sni": ""
> }
> 
> shows bug:
> relay error: unexpected EOF
> 
> i can use this config on v2rayn sucessfully but glider failed,anything wrong?

**Comment by emptyteeth** [comment]
try this:
```
ws://52.199.19.113:80/,vmess://f830d6df-0a72-4fd4-c434-57a0fe1c811e@?alterID=64
```

**Comment by qqqqqqrrrrhh123a** [comment]
glider -rules-dir=rules.d -check=disabled -verbose -dnsserver=8.8.8.8:53 -listen=:8080 -forward="ws://52.199.19.113:80/,vmess://f830d6df-0a72-4fd4-c434-57a0fe1c811e@?alterID=64"
2021/08/05 14:05:48 group.go:182: [group] only 1 forwarder found, disable health checking
2021/08/05 14:05:48 group.go:182: [group] only 1 forwarder found, disable health checking
2021/08/05 14:05:48 mixed.go:68: [mixed] listening TCP on :8080
2021/08/05 14:05:48 server.go:105: [socks5] listening UDP on :8080
2021/08/05 14:06:03 server.go:88: [socks5] 127.0.0.1:54605 <-> google.com:80 via 52.199.19.113:80, relay error: unexpected EOF

**Comment by qqqqqqrrrrhh123a** [comment]
> 
> 
> try this:
> 
> ```
> ws://52.199.19.113:80/,vmess://f830d6df-0a72-4fd4-c434-57a0fe1c811e@?alterID=64
> ```

still same error

**Comment by qqqqqqrrrrhh123a** [comment]
glider -rules-dir=rules.d -check=disabled -verbose -dnsserver=8.8.8.8:53 -listen=:8080 -forward=ws://52.199.19.113:80/,vmess://f830d6df-0a72-4fd4-c434-57a0fe1c811e@?alterID=64

this command is also too

**Comment by qqqqqqrrrrhh123a** [comment]
> 
> 
> try this:
> 
> ```
> ws://52.199.19.113:80/,vmess://f830d6df-0a72-4fd4-c434-57a0fe1c811e@?alterID=64
> ```

did you try run this command.,i failed

**Comment by nadoo** [comment]
What is the log of your server side?

**Comment by qqqqqqrrrrhh123a** [comment]
i didnt have server permission,because server is not mine.i can not see server log.

**Comment by qqqqqqrrrrhh123a** [comment]
vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogIj8iLA0KICAiYWRkIjogIjUyLjE5OS4xOS4xMTMiLA0KICAicG9ydCI6ICI4MCIsDQogICJpZCI6ICJmODMwZDZkZi0wYTcyLTRmZDQtYzQzNC01N2EwZmUxYzgxMWUiLA0KICAiYWlkIjogIjY0IiwNCiAgInNjeSI6ICJhdXRvIiwNCiAgIm5ldCI6ICJ3cyIsDQogICJ0eXBlIjogIm5vbmUiLA0KICAiaG9zdCI6ICIiLA0KICAicGF0aCI6ICIvIiwNCiAgInRscyI6ICIiLA0KICAic25pIjogIiINCn0=
vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogIj4/IiwNCiAgImFkZCI6ICI1Mi4xOTUuOS4xMTQiLA0KICAicG9ydCI6ICI4MCIsDQogICJpZCI6ICJhMWVhYTkyOS1hNWUyLTRmMTItZjZhYy1lYzlmNDUxZjBmYmUiLA0KICAiYWlkIjogIjY0IiwNCiAgInNjeSI6ICJhdXRvIiwNCiAgIm5ldCI6ICJ3cyIsDQogICJ0eXBlIjogIm5vbmUiLA0KICAiaG9zdCI6ICIiLA0KICAicGF0aCI6ICIvIiwNCiAgInRscyI6ICIiLA0KICAic25pIjogIiINCn0=
vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogIj8iLA0KICAiYWRkIjogImF1dG8uZnJlZXYyLnRvcCIsDQogICJwb3J0IjogIjE3ODc0IiwNCiAgImlkIjogImIzOTViNzg1LWM2NDEtNGQ1ZS1iZDY1LTMyOGU0ZWUwODM3NCIsDQogICJhaWQiOiAiMSIsDQogICJzY3kiOiAiYXV0byIsDQogICJuZXQiOiAidGNwIiwNCiAgInR5cGUiOiAibm9uZSIsDQogICJob3N0IjogIiIsDQogICJwYXRoIjogIiIsDQogICJ0bHMiOiAiIiwNCiAgInNuaSI6ICIiDQp9
vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogIj8iLA0KICAiYWRkIjogIjEzLjIzMC45LjE1NCIsDQogICJwb3J0IjogIjgwIiwNCiAgImlkIjogIjQxNTkyOTliLTIyZmEtNDUxYi04MGQ3LWZlZDU5NjA2OTBmOSIsDQogICJhaWQiOiAiNjQiLA0KICAic2N5IjogImF1dG8iLA0KICAibmV0IjogIndzIiwNCiAgInR5cGUiOiAibm9uZSIsDQogICJob3N0IjogIiIsDQogICJwYXRoIjogIi8iLA0KICAidGxzIjogIiIsDQogICJzbmkiOiAiIg0KfQ==

**Comment by qqqqqqrrrrhh123a** [comment]
all of this can be used  nowtime

**Comment by nadoo** [comment]
Maybe your server was configured to use VMessAEAD which is not supported in current version of glider.

**Comment by qqqqqqrrrrhh123a** [comment]
It's so frustrating

**Comment by qqqqqqrrrrhh123a** [comment]
can i change my glider config to support server and use them?or does it have alternative software or alternative  plan

**Comment by nadoo** [comment]
[glider-v0.15.0b1-linux64.zip](https://github.com/nadoo/glider/files/6937943/glider-v0.15.0b1-linux64.zip)

@qqqqqqrrrrhh123a , please try the attachment to see whether it worked.

Note: do not set the `alterID` parameter to enable VMessAEAD.
`
forward="ws://52.199.19.113:80/,vmess://f830d6df-0a72-4fd4-c434-57a0fe1c811e@"
`

**Comment by qqqqqqrrrrhh123a** [comment]
i use windows glider and try  not set the alterID parameter to enable VMessAEAD but failed too. i havent linux computer now

**Comment by nadoo** [comment]
[glider-v0.15.0b1-win64.zip](https://github.com/nadoo/glider/files/6939348/glider-v0.15.0b1-win64.zip)

windows version

**Comment by qqqqqqrrrrhh123a** [comment]
two of glider-v0.15.0b1 incluing windows and linux are not working. alterid change to 0 is same result
2021/08/06 20:56:37 server.go:90: [socks5] 127.0.0.1:49922 <-> google.com:80 via 52.195.9.114:80, relay error: unexpected EOF

**Comment by qqqqqqrrrrhh123a** [comment]
i think it is a bug of glider

**Comment by nadoo** [comment]
> i think it is a bug of glider

No! It's not bug as the `ws` and `vmess` implementation was tested with nginx and v2ray without any problem, It's hard to debug without server information. but after some research, I found some software supports websocket `early-data` feature but maybe not properly implemented, so I modified codes to be compatible with it. 

You can try the following version: 
[glider-v0.15.0b2-win64.zip](https://github.com/nadoo/glider/files/6951019/glider-v0.15.0b2-win64.zip)

**Comment by early860** [comment]
I had a simliar "unexpected EOF" client failure in tls+ws+vmess config with 0.14.0-win64. V2ray & clash client can connect correclty.
I tried "glider-v0.15.0b2-win64.zip" with the same config file, and it can connect correctly!
Sorry I can't help to provide the host info. Thank you for fixing my problem!
