### ISSUE TITLE
dns req from coredns error

### ISSUE THREAD

**Issue by ermazi** [nadoo/glider#272]
in glider error: unmarshal not enough data
in coredns: 
[ERROR] plugin/errors: 2 github.com. A: read udp 10.1.128.236:39213->192.168.224.1:53: i/o timeout
[INFO] 10.1.128.237:46453 - 10898 "AAAA IN github.com. udp 28 false 512" NOERROR - 0 2.000385907s
[ERROR] plugin/errors: 2 github.com. AAAA: read udp 10.1.128.236:49911->192.168.224.1:53: i/o timeout

**Comment by nadoo** [comment]
Hi @ermazi , sorry for late response. 

Do you use glider as the upstream dns server of coredns? sth like `dns client-> coredns -> glider -> dns server`?
