### ISSUE TITLE
PR_CONNECT_RESET_ERROR

### ISSUE THREAD

**Issue by scruel** [nadoo/glider#273]
Both works fine:
`glider -verbose -listen :1089 -forward socks5://127.0.0.1:7444`
`glider -verbose -listen :1089 -forward socks5://127.0.0.1:62323`
`glider -verbose -listen :1089 -forward socks5://x.x.x.x:24573`

But not together:
`glider -verbose -listen :1089 -forward socks5://127.0.0.1:7444,socks5://127.0.0.1:62323`
Will got error:
error in dial: proxy: failed to read greeting from SOCKS5 proxy at 127.0.0.1:62323: EOF

`glider -verbose -listen :1089 -forward socks5://x.x.x.x:24573,socks5://127.0.0.1:62323`
Will got error:
error in dial: proxy: SOCKS5 proxy at x.x.x.x:24573 failed to connect: connection refused

network chain:
Client => Server Proxy1(7444) => Local Proxy2(62323) => Web

**Comment by rampageX** [comment]
In my experience, the last proxy of the `glider` proxy chain must have a external network address.

so both:

```
glider -verbose -listen :1089 -forward socks5://127.0.0.1:7444,socks5://x.x.x.x:24573

glider -verbose -listen :1089 -forward socks5://127.0.0.1:62323,socks5://x.x.x.x:24573
```

will work(x.x.x.x not a private network), but not two `127.0.0.1` local proxy like u test.

**Comment by nadoo** [comment]
Hi @scruel , thanks for your report. 

`glider -verbose -listen :1080`
`glider -verbose -listen :1081`
`glider -verbose -listen :8443 -forward socks5://127.0.0.1:1080,socks5://127.0.0.1:1081`
`curl -x socks5://127.0.0.1:8443 apple.com`
works without problem.

do you know what it the socks5 server app in your environment?

**Comment by rampageX** [comment]
@nadoo Your example does not have practicality,Typically, the proxy on the proxy chain is not a simple local monitor, but will be connected to the remote server (because the protocol / client that is not supported by `glider`), for example,

```
socks5_client1 -listen :7575 -connect a.a.a.a:vps1
socks5_client2 -listen :7676 -connect b.b.b.b:vps2
glider -verbose -listen :8443 -forward socks5://127.0.0.1:7575,socks5://127.0.0.1:7676
```

run `curl -x` to test:

```
root@N1-U20:~/src# curl -I -x socks5://127.0.0.1:7575 apple.com
HTTP/1.1 301 Redirect
Date: Sun, 15 Aug 2021 02:54:50 GMT
Connection: keep-alive
Via: http/1.1 hkhkg1-edge-bx-012.ts.apple.com (ApacheTrafficServer/8.1.2)
Server: ATS/8.1.2
Cache-Control: no-store
Location: https://www.apple.com/
Content-Type: text/html
Content-Language: en
CDNUUID: ecb5d08d-e15b-4b7c-b7ff-b588e08091ab-4904364833
X-Cache: none
Content-Length: 304

root@N1-U20:~/src# curl -I -x socks5://127.0.0.1:7676 apple.com
HTTP/1.1 301 Redirect
Date: Sun, 15 Aug 2021 02:54:57 GMT
Connection: keep-alive
Via: http/1.1 jptyo7-edge-bx-007.ts.apple.com (ApacheTrafficServer/8.1.2)
Server: ATS/8.1.2
Cache-Control: no-store
Location: https://www.apple.com/
Content-Type: text/html
Content-Language: en
CDNUUID: 7e123403-f785-46b5-8418-4625a2453818-13590593004
X-Cache: none
Content-Length: 304

root@N1-U20:~/src# curl -I -x socks5://127.0.0.1:8443 apple.com
curl: (56) Recv failure: Connection reset by peer
```

`glider` say,

```
glider -verbose -listen :8443 -forward socks5://127.0.0.1:7575,socks5://127.0.0.1:7676
2021/08/15 10:55:51 group.go:186: [group] only 1 forwarder found, disable health checking
2021/08/15 10:55:51 server.go:107: [socks5] listening UDP on :8443
2021/08/15 10:55:51 mixed.go:68: [mixed] listening TCP on :8443
2021/08/15 10:56:06 server.go:82: [socks5] 127.0.0.1:51866 <-> 17.253.144.10:80 via 127.0.0.1:7575,127.0.0.1:7676, error in dial: proxy: failed to read greeting from SOCKS5 proxy at 127.0.0.1:7676: EOF
```

If i simple replace proxy2 with a public ip proxy, then both :7575/:7676 be the first proxy will work,

`glider -verbose -listen :8443 -forward socks5://127.0.0.1:7575,socks5://punk:fuckUgfw@oracle.123456.xyz:389`

**Comment by scruel** [comment]
> 
> 
> Hi @scruel , thanks for your report.
> 
> `glider -verbose -listen :1080`
> `glider -verbose -listen :1081`
> `glider -verbose -listen :8443 -forward socks5://127.0.0.1:1080,socks5://127.0.0.1:1081`
> `curl -x socks5://127.0.0.1:8443 apple.com`
> works without problem.
> 
> do you know what it the socks5 server app in your environment?

mitmproxy and shadowsocks

**Comment by scruel** [comment]
>  public ip proxy

I really tried to use public IP(x.x.x.x) as last proxy chain, but still not work:
`glider -verbose -listen :1089 -forward socks5://127.0.0.1:7444,socks5://x.x.x.x:24573`
`glider -verbose -listen :1089 -forward socks5://127.0.0.1:62323,socks5://x.x.x.x:24573`


I got the error, or just timeout for mitmproxy:
`failed to connect: connection forbidden`

**Comment by scruel** [comment]
With two Shadowsocks proxy chain:

`glider -verbose -listen :1089 -forward socks5://127.0.0.1:7444,socks5://127.0.0.1:7888`

Got error:
`[socks5] 127.0.0.1:14092 <-> www.google.com:443 via 127.0.0.1:7444,127.0.0.1:7888, error in dial: proxy: failed to read greeting from SOCKS5 proxy at 127.0.0.1:7888: EOF`

But if I use the forward proxy function supported by Shadowsocks windows client, it works fine when combine the two Shadowsocks proxy:
Client => SSProxy1 => SSProxy2(set SSProxy1 as forward proxy) => Target

glider command should do the same thing, but it didn't work.

**Comment by nadoo** [comment]
> Two Shadowsocks servers proxy chain:
> `glider -verbose -listen :1089 -forward socks5://127.0.0.1:7444,socks5://127.0.0.1:7888`
> 
> Will got PR_CONNECT_RESET_ERROR:
> `[socks5] 127.0.0.1:14092 <-> www.google.com:443 via 127.0.0.1:7444,127.0.0.1:7888, error in dial: proxy: failed to read greeting from SOCKS5 proxy at 127.0.0.1:7888: EOF`
> 

Of course it will not work, because your first socks5 server `socks5://127.0.0.1:7444` is actually a ss client, it will send the target address `127.0.0.1:7888` to ss server, and the target `127.0.0.1` is on your ss server, not on your local side.

You can just chain ss protocol like:
`
glider -verbose -listen :1089 -forward ss://server1,ss://server2
`

**Comment by scruel** [comment]
> 
> 
> > Two Shadowsocks servers proxy chain:
> > `glider -verbose -listen :1089 -forward socks5://127.0.0.1:7444,socks5://127.0.0.1:7888`
> > Will got PR_CONNECT_RESET_ERROR:
> > `[socks5] 127.0.0.1:14092 <-> www.google.com:443 via 127.0.0.1:7444,127.0.0.1:7888, error in dial: proxy: failed to read greeting from SOCKS5 proxy at 127.0.0.1:7888: EOF`
> 
> Of course it will not work, because your first socks5 server `socks5://127.0.0.1:7444` is actually a ss client, it will send the target address `127.0.0.1:7888` to ss server, and the target `127.0.0.1` is on your ss server, not on your local side.
> 
> You can just chain ss protocol like:
> `glider -verbose -listen :1089 -forward ss://server1,ss://server2`

It's just a test, Not need to chain two ss, The limitation of last chain's IP should be the public is quite a trouble thing...

**Comment by nadoo** [comment]
> > > Two Shadowsocks servers proxy chain:
> > > `glider -verbose -listen :1089 -forward socks5://127.0.0.1:7444,socks5://127.0.0.1:7888`
> > > Will got PR_CONNECT_RESET_ERROR:
> > > `[socks5] 127.0.0.1:14092 <-> www.google.com:443 via 127.0.0.1:7444,127.0.0.1:7888, error in dial: proxy: failed to read greeting from SOCKS5 proxy at 127.0.0.1:7888: EOF`
> > 
> > 
> > Of course it will not work, because your first socks5 server `socks5://127.0.0.1:7444` is actually a ss client, it will send the target address `127.0.0.1:7888` to ss server, and the target `127.0.0.1` is on your ss server, not on your local side.
> > You can just chain ss protocol like:
> > `glider -verbose -listen :1089 -forward ss://server1,ss://server2`
> 
> It's just a test, Not need to chain two ss, The limitation of last chain's IP should be the public is quite a trouble thing...

Because `127.0.0.1` is on your local computer, so the first remote ss server can not reach it, it's not a bug or limitation, it's normal.

**Comment by nadoo** [comment]
> > > Two Shadowsocks servers proxy chain:
> > > `glider -verbose -listen :1089 -forward socks5://127.0.0.1:7444,socks5://127.0.0.1:7888`
> > > Will got PR_CONNECT_RESET_ERROR:
> > > `[socks5] 127.0.0.1:14092 <-> www.google.com:443 via 127.0.0.1:7444,127.0.0.1:7888, error in dial: proxy: failed to read greeting from SOCKS5 proxy at 127.0.0.1:7888: EOF`
> > 
> > 
> > Of course it will not work, because your first socks5 server `socks5://127.0.0.1:7444` is actually a ss client, it will send the target address `127.0.0.1:7888` to ss server, and the target `127.0.0.1` is on your ss server, not on your local side.
> > You can just chain ss protocol like:
> > `glider -verbose -listen :1089 -forward ss://server1,ss://server2`
> 
> It's just a test, Not need to chain two ss, The limitation of last chain's IP should be the public is quite a trouble thing...

Client -- > ss Client(socks5://127.0.0.1:7444) --> ss Server ---**CAN NOT REACH**---> socks5://127.0.0.1:7888
