### ISSUE TITLE
certificate signed by unknown authority

### ISSUE THREAD

**Issue by abc91513** [nadoo/glider#275]
Client:
   glider -verbose -listen :33333 -forward trojan://12345678@47.74.61.5:33333?skipVerify=false
Server:
   ./glider -verbose -listen "trojan://12345678@:33333?cert=server.crt&key=server.key&fallback=127.0.0.1:80"

Will got error:
Client:
	2021/08/20 09:37:29 server.go:89: [http] 127.0.0.1:57458 <-> dd.browser.360.cn:443 [c] via 47.74.61.5:33333, error in dial: dial tcp :0->47.74.61.5:33333: i/o timeout
	2021/08/20 09:37:29 server.go:111: [http] 127.0.0.1:57462 <-> dd.browser.360.cn:80 via 47.74.61.5:33333, error in dial: x509: certificate signed by unknown authority
	2021/08/20 09:37:29 server.go:111: [http] 127.0.0.1:57464 <-> cloud.browser.360.cn:80 via 47.74.61.5:33333, error in dial: x509: certificate signed by unknown authority
Server:	
	2021/08/20 09:37:25 server.go:89: [trojan] error in tls handshake: remote error: tls: bad certificate
	2021/08/20 09:37:27 server.go:89: [trojan] error in tls handshake: remote error: tls: bad certificate
	2021/08/20 09:37:27 server.go:89: [trojan] error in tls handshake: remote error: tls: bad certificate
	2021/08/20 09:37:30 server.go:89: [trojan] error in tls handshake: remote error: tls: bad certificate
	2021/08/20 09:37:30 server.go:89: [trojan] error in tls handshake: remote error: tls: bad certificate

This certificate is normally used in Trojan go

**Comment by abc91513** [comment]
The certificate used is self signed

**Comment by nadoo** [comment]
> The certificate used is self signed

set `skipVerify=true`:
`glider -verbose -listen :33333 -forward trojan://12345678@47.74.61.5:33333?skipVerify=true`

**Comment by abc91513** [comment]
Set skipverify = true, it can work normally, but there is no way to verify the certificate. Can you verify the self signed certificate? Trojan go can pass the verification

**Comment by abc91513** [comment]
Trojan go is configured as follows

run-type: client
local-addr: 127.0.0.1
local-port: 33333
remote-addr: 47.74.61.5
remote-port: 33333
password:
  - 12345678
ssl:
  cert: c:\server.crt
  sni: abc.com


run-type: server
local-addr: 0.0.0.0
local-port: 33333
remote-addr: 127.0.0.1
remote-port: 80
password:
  - 12345678
ssl:
  cert: /home/server.crt
  key: /home/server.key
  sni: abc.com

**Comment by nadoo** [comment]
I see, what you need is the `Certificate Pinning` feature, I'll add it in the next version.

**Comment by nadoo** [comment]
I see, what you need is the `Certificate Pinning` feature, I'll add it in the next version.

**Comment by nadoo** [comment]
I see, what you need is the `Certificate Pinning` feature, I'll add it in the next version.

**Comment by abc91513** [comment]
OK, thank you.

**Comment by nadoo** [comment]
[glider-v0.15.1-test1.zip](https://github.com/nadoo/glider/files/7019083/glider-v0.15.1-test1.zip)

Hi @abc91513 , you can test the attachment with sth like below:
`glider -verbose -listen :33333 -forward trojan://12345678@47.74.61.5:33333?cert=CERT_FILE_PATH`

**Comment by abc91513** [comment]
@nadoo 
Glider-v0.15.1-test1 is tested. The error is the same as v0.15. My test is as follows:

client

glider -verbose -listen :33333 -forward trojan://12345678 @47.74.61.4:33333? skipVerify=false&cert=server.crt&sni=lab.com

server

./glider -verbose -listen " trojan://12345678 @:33333? cert=server.crt&key=server.key&key=server.key&sni=lab.com&fallback=127.0.0.1:80"

**Comment by nadoo** [comment]
There's no `sni` parameter in glider, it's called `serverName`, can you try again?

**Comment by abc91513** [comment]
@nadoo 
The following method is also not good.

client
   glider -verbose -listen :33333 -forward trojan://12345678 @47.74.61.74:33333?skipVerify=false&cert=server.crt&serverName=lab.com

server
   ./glider -verbose -listen " trojan://12345678 @:33333? cert=server.crt&key=server.key&fallback=127.0.0.1:80"

**Comment by abc91513** [comment]
![image](https://user-images.githubusercontent.com/89192855/130199489-510fde95-a31d-4796-818d-df3c4c469d9d.png)

**Comment by abc91513** [comment]
@nadoo 
  
![image](https://user-images.githubusercontent.com/89192855/130204738-27818465-73b2-4818-ab22-3f96ae2095d3.png)

**Comment by abc91513** [comment]
![image](https://user-images.githubusercontent.com/89192855/130205349-3d28ea37-b972-4bcc-9473-755e8114e52f.png)

**Comment by abc91513** [comment]
![image](https://user-images.githubusercontent.com/89192855/130205961-bc7612bd-e54e-443b-ba1b-22f2eb834173.png)

**Comment by abc91513** [comment]
@nadoo 
glider client        and glider server         fail
glider client        and trojan-go server   fail
trojan-go client   and glider server        sucess

**Comment by nadoo** [comment]
Hi @abc91513 , the last picture is glider client and glider server,  are you sure the cert file you use in glider client is the same as trojan-go? maybe you should add the ca cert content into your cert file as a cert chain to work.

**Comment by abc91513** [comment]
Hi @nadoo The last picture was sent wrong.

![image](https://user-images.githubusercontent.com/89192855/130213567-d8f6982e-0dff-40d3-bcd6-3ade348a7890.png)

**Comment by abc91513** [comment]
client.yaml

run-type: client
local-addr: 127.0.0.1
local-port: 33333
remote-addr: 47.74.61.74
remote-port: 33333
password:
  - 12345678
ssl:
  cert: c:\server.crt
  sni: lab.com

**Comment by abc91513** [comment]
@nadoo 

Using the same certificate and private key, only Trojan go and glider are changed, and the following results are obtained:

glider client and glider server fail

glider client and trojan-go server fail

trojan-go client and glider server sucess

trojan-go client and trojan-go server sucess

**Comment by abc91513** [comment]
@nadoo 
The server uses Trojan go, and the client uses Trojan go and glider respectively. If the SNI parameter is removed from the Trojan go client, the same error will occur on the Trojan go server.

![image](https://user-images.githubusercontent.com/89192855/130217165-367bd7b5-c48c-40f2-8368-99bae163ee80.png)

![image](https://user-images.githubusercontent.com/89192855/130217195-85d66dba-3f55-4f5f-bfd4-b17f28a1bd62.png)

**Comment by abc91513** [comment]
@nadoo 
From the above tests, it is suspected that the serverName parameter of glider client does not meet the sni parameter function of Trojan go.

  报错 笔记双语对照

**Comment by nadoo** [comment]
Hi @abc91513 , thanks for your hardly test. I see you're using windows, maybe you can add quote to your command line:
`glider -verbose -listen :33333 -forward "trojan://12345678@47.74.61.5:33333?cert=c:\server.crt&serverName=lab.com"`

**Comment by abc91513** [comment]
Thank you. The problem was solved according to your method

**Comment by abc91513** [comment]
@nadoo 

There are still problems with TLS over Socks5 and TLS over vless. It is recommended to deal with them

**Comment by nadoo** [comment]
[glider-v0.15.1-test2.zip](https://github.com/nadoo/glider/files/7020975/glider-v0.15.1-test2.zip)

Hi @abc91513 , thanks for your tests! You can use the attachment if you need `Certificate Pinning` feature for all tls clients.

**Comment by abc91513** [comment]
> [glider-v0.15.1-test2.zip](https://github.com/nadoo/glider/files/7020975/glider-v0.15.1-test2.zip)
> 
> Hi @abc91513 , thanks for your tests! You can use the attachment if you need `Certificate Pinning` feature for all tls clients.

Thank you. Socks5 and vless are OK.
