### ISSUE TITLE
Any chance to support google colab VM to creat a Reverse proxy?

### ISSUE THREAD

**Issue by quaggalinux** [nadoo/glider#278]
We can run below python code in google colab web console for expose web service:

from google.colab.output import eval_js
print(eval_js("google.colab.kernel.proxyPort(8000)"))

That means we will listen port 8000.

colab will output URL like：
https://aw6wrk463qm-496ff2e9c6d22116-8000-colab.googleusercontent.com/

But google colab explain it can not support websocket, so we cannot support web Reverse proxy too. 
I downloaded glider and run it in colab web console to listen port 8000 because colab support ! prefix to run all linux command.
And then I run glider in local linux as client, but seems like it cannot communicate with  glider server through 
"aw6wrk463qm-496ff2e9c6d22116-8000-colab.googleusercontent.com:443".

Is there any chance to support google colab VM to creat a Reverse proxy?

**Comment by nadoo** [comment]
Hi @quaggalinux , it depends on the `google.colab.kernel.proxyPort`, does it support websocket?

**Comment by quaggalinux** [comment]
Google colab explain it can not support websocket. I alreay installed Caddy to test websocket but google.colab.kernel.proxyPort cannot support  websocket.
I also test another github project goflyway. Goflyway uses pure HTTP POST requests to relay TCP connections. There is no CONNECT involved nor needed because goflyway is designed mainly for those people who are behind a CONNECT-less HTTP proxy or want to accelerate connections through static CDNs. 
But goflyway cannot support HTTPS, but  Google colab URL only has HTTPS. So goflyway does not work normal in here.

**Comment by nadoo** [comment]
Maybe you can use glider on your local side to handle the tls layer:
'''glider -verbose -listen tcp://:8000 -forward "tls://xxxxxx.com"'''

**Comment by quaggalinux** [comment]
Hi, @nadoo , I used following command in colab server side and local side:

colab server -> /content/glider -verbose -listen http://:8000

local linux -> ./glider -verbose -listen socks5://:8000 -forward "tls://t3zwg2g68hh-496ff2e9c6d22116-8000-colab.googleusercontent.com:443"

I set the chrome browser to use local socks5 proxy. The local linux shows glider received all the chrome request and send to "t3zwg2g68hh-496ff2e9c6d22116-8000-colab.googleusercontent.com" server, but in the server side I can not see glider receive any request from the client.

I alreay try another project gost and the situation same.

I think may be colab can not proxy "connect" command. So, if the glider support pure HTTP POST requests to relay TCP connections feature in the future will be a great.

**Comment by nadoo** [comment]
Hi @quaggalinux , in the previous comment you said `Goflyway uses pure HTTP POST requests to relay TCP connections, But goflyway cannot support HTTPS`, so I suggest you can try glider to handle the tls layer on your local side:

server: 
Goflyway listen on port 8000

client:
use glider to handle tls layer:
```
glider -verbose -listen tcp://:8000 -forward "tls://xxxxxx.com"
```
then use `127.0.0.1:8000` as your Goflyway server address, use Goflyway client to connect it.

It depends on the colab http server, if it strips all the http proxy headers before forwards to Goflyway server, it may not work.

**Comment by quaggalinux** [comment]
I adopt your suggestion to try following command:
server -> /content/goflyway -l=":8000" -k="123"

local two SSH session:
local -> ./glider -verbose -listen tcp://:8000 -forward "tls://kqhx5ag530l-496ff2e9c6d22116-8000-colab.googleusercontent.com:443"
local ->  ./goflyway -l=":38000" -k="123" -up="127.0.0.1:8000"

glider report:
2021/09/11 04:11:25 tcp.go:89: [tcp] 127.0.0.1:54560 <-> kqhx5ag530l-496ff2e9c6d22116-8000-colab.googleusercontent.com:443
2021/09/11 04:11:30 tcp.go:92: [tcp] 127.0.0.1:54560 <-> kqhx5ag530l-496ff2e9c6d22116-8000-colab.googleusercontent.com:443, relay error: read tcp 127.0.0.1:8000->127.0.0.1:54560: read: connection reset by peer

goflyway report:
2021-09-11 04:07:03.933 UTC,client.go:541, ERROR ,"Dial failed: invalid response from dnsleaktest.com:443: HTTP/1.1 404 Not Found
Content-Type: text/html; charset=UTF-8
Referrer-Policy: no-referrer
Content-Length: 1580
Date: Sat, 11 Sep 2021 04:07:03 GMT
Alt-Svc: h3="":443""; ma=2592000,h3-29="":443""; ma=2592000,h3-T051="":443""; ma=2592000,h3-Q050="":443""; ma=2592000,h3-Q046="":443""; ma=2592000,h3-Q043="":443""; ma=2592000,quic="":443""; ma=2592000; v=""46,43""

It seems like that setup can not work.

**Comment by nadoo** [comment]
Your godlyway client log shows that it successfully connected to the colab http server, and received its response. 

Unfortunately the colab http server didn't allow the goflyway's    proxy request and responded 404 to your client.

So I think it's impossible to achieve your goal because of the colab limit.
