### ISSUE TITLE
ipset without dnsmasq problem

### ISSUE THREAD

**Issue by AlexanderZhan** [nadoo/glider#279]
My english is poor,
Hope u can know that what I talk about.

I think that all dns msg will go to proxy,
I want
baidu.com -> 223.5.5.5:53, direct it, bypass to avoid the proxy,
google.com -> 8.8.8.8:53.

**Comment by nadoo** [comment]
It's quite easy
ref: https://github.com/nadoo/glider/tree/master/config/examples/9.transparent_proxy_without_dnsmasq

**glider.conf**
no forwarder set means direct by default
```
verbose=True

# as a redir proxy
listen=redir://:1081

# as a dns forwarding server
dns=:53
dnsserver=223.5.5.5:53

# specify rule files
rules-dir=rules.d
```

**rules.d/proxy.rule**
```
# as a ipset manager
ipset=glider

# your forwarders
forward=http://forwarder1:8080
forward=socks5://forwarder2:1080

# specify a different dns server(if need)
dnsserver=8.8.8.8:53
dnsserver=8.8.4.4:53


domain=google.com
```

then you can `dig @127.0.0.1 baidu.com` to test, only domains in proxy.rule will be resolved via proxy.

**Comment by AlexanderZhan** [comment]
It works,
I have imported the gfwlist to proxy.rule,
Very perfect,

Thx very very muchhhhhhhhhhh.

**Comment by nadoo** [comment]
> It works,
> I have imported the gfwlist to proxy.rule,
> Very perfect,
> 
> Thx very very muchhhhhhhhhhh.

Glad to hear that :smile:
