### ISSUE TITLE
how to setup a glider's vmess server?

### ISSUE THREAD

**Issue by quaggalinux** [nadoo/glider#281]
I want to setup a glider's vmess server.

UUID:68198a99-87ec-46a9-ab11-7ff8e36329ba

alterID:0

AES_128_GCM

vmess listen port: 8080

websocket path: glider

I used below commands:

./glider -listen "ws://:8080/glider,vmess://security:68198a99-87ec-46a9-ab11-7ff8e36329ba@?alterID=0"

or

./glider -listen "ws://@/glider,vmess://security:68198a99-87ec-46a9-ab11-7ff8e36329ba@:8080?alterID=0"

But glider report:   unknown scheme 'vmess'

If glider support vmess server? If yse, which command will work?

**Comment by nadoo** [comment]
sorry, not supported.
