### ISSUE TITLE
Suggestions for Improvement：strategy=lha 

### ISSUE THREAD

**Issue by rampageX** [nadoo/glider#282]
For now, `lha` was judged right behind the interval checked was done, this behavior has some flaws:

Suppose we have multiple nodes A, B, C, D, the A node have the smallest `elapsed` from 1 check, `glider` choice A as `winner` node now. But in fact, node B(or C D) may be faster than node A most of the time. 

This situation often occurs on routes from mainland China to overseas，Shorter the `checkinterval` and Bigger the `checktolerance` may improve the flaws but not perfect.

How about check continuously（let's call `inner-check` here） during `checkinterval`,then next `checkinterval` will use the average `elapsed` value as `winner`. 

For `checkinterval=3600` i mostly used, let `inner-check=60`, we will get the the very fair result from the past 1 hour.

For `glider` first start, old way is fine if we have no result cache to use.

**Comment by nadoo** [comment]
Hi @rampageX , how about adding a configurable number N, which it the count of latest latencies? then the average latency:`avgLatency` can be calculated by:
```Golang
avgLatency = (oldAvgLatency * (N-1) + newLatency) / N
```
In your example, you can set `checkinterval=60` and `N=60` to get the average latency of the latest 60 checks(about 1 hour).  

So it be implement simpler, but how to naming `N` in config file is always hard to me -_-! any ideas?

**Comment by rampageX** [comment]
How about `avglatencysamples`, `<=0` means not use the function, otherwise is number of samples.

**Comment by nadoo** [comment]
ok, `latencysamples` is good to understand, so I'll use `checklatencysamples` as the config name.

**Comment by nadoo** [comment]
There's a dev build binary from github actions: https://github.com/nadoo/glider/actions/runs/1871794484

**Comment by nadoo** [comment]
I'm also thinking about change the default value from `1` to `10` or some other values to get better experience.

**Comment by rampageX** [comment]
> There's a dev build binary from github actions: [nadoo/glider/actions/runs/1871794484](https://github.com/nadoo/glider/actions/runs/1871794484)

Thx, testing!

**Comment by nadoo** [comment]
Closing as v0.16.0 released: https://github.com/nadoo/glider/releases/tag/v0.16.0
