### ISSUE TITLE
exit glider when it fails to listen

### ISSUE THREAD

**Issue by nil0x42** [nadoo/glider#284]
Hi !

Would it not be more reliable to exit glider if a `-listen` fails ?

For the moment, it simply writes: 
```
2021/09/27 20:21:17 server.go:102: [socks5] failed to listen on UDP localhost:8443: listen udp 127.0.0.1:8443: bind: address already in use
```
when log is verbose, but continues execution.

**Comment by nadoo** [comment]
Thanks for your suggestion, I'll consider it later.
