### ISSUE TITLE
need help for websocket config

### ISSUE THREAD

**Issue by quaggalinux** [nadoo/glider#286]
I config a nginx server to reverse proxy glider:

location /glider {
    proxy_pass       http://127.0.0.1:60003;
    proxy_redirect             off;
    proxy_http_version         1.1;
    proxy_set_header Upgrade   $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host      $host;
    }

console run glider:
./glider -verbose -listen ws://127.0.0.1:60003/glider

And then  I visit my web site https://www.mydomain.com/glider
I got the error from console when :
2021/10/03 16:42:58 server.go:117: [ws] 127.0.0.1:38750 <-> 127.0.0.1:60003 via DIRECT, error in dial: dial tcp: missing address

Also, the brower shows a blank screen. Normal is "bad request"

Could you help me to point out the mistakes in my config?

thank you

**Comment by ermazi** [comment]
> something like:
> 
> server: ./glider -verbose -listen ws://127.0.0.1:60003,socks5://
> 
> client: ./glider -verbose -listen :1080 -forward ws://www.my domain.com/glider,socks5://
> 
> Then use 127.0.0.1:1080 as your local proxy server

why, curious about it = =

**Comment by nadoo** [comment]
> 

Any questions? feel free to ask here or create a new issue :)
