### ISSUE TITLE
Any keep alive parameter for ssh forwarder?

### ISSUE THREAD

**Issue by quaggalinux** [nadoo/glider#287]
I want to know if there is any keep alive parameter for ssh forwarder?
for example command in below:
./glider -verbose -listen :1080 -forward ssh://user:password@28.28.28.28:22

DO I need to add any parameter to keep alive or glider has default keep alive？

Thank you

**Comment by nadoo** [comment]
Hi @quaggalinux , there's no keepalive support currently. but with the latest commit, we can use timeout parameter to recreate the underlay connection:
```
glider -verbose -listen :1080 -forward "ssh://user:password@28.28.28.28:22?timeout=5"
```
Additionally, we can set duplicate forwarders to have more underlay connections and use proxy checking to keepalive them:
```
glider -verbose -listen :1080 -forward "ssh://user:password@28.28.28.28:22 -forward "ssh://user:password@28.28.28.28:22 -strategy rr -check http://apple.com -checkinterval 10"
```
Maybe that's enough?  If we must have the keepalive feature for ssh, I'll add it later.

**Comment by nadoo** [comment]
[glider-linux.zip](https://github.com/nadoo/glider/files/7696361/glider-linux.zip)

The attachment is the latest build, you can try it if you need.

**Comment by quaggalinux** [comment]
Thank you for your fantastic work! I will try the attach version.
