### ISSUE TITLE
How can I write V2RAY vless with a disguised website?

### ISSUE THREAD

**Issue by xtangliang** [nadoo/glider#294]
like this issues blow, but it is closed, so I open a new one.
https://github.com/nadoo/glider/issues/170

there is 1 different point , that I use vless.
By following the command @nadoo mentioned, 
> Please try:
forward=ws://sh.bit.co:9130/cctv/hd3u8?host=www.baidu.com,vmess://e3368f62-d28d-4b03-879a-ec98f529d@?alterID=2
It doesnt work, could u plz helping me to check these out. I tried many diffrent ways.

way 1 : not use fake host, it works
way 2: try to use fake host like you mention above, it doesnt work
way 3: try to use serverName instead of host, it doesnt work
way 4: try to use tls://+ws:// instead of wss://, it doesnt work
way 5: try to add skipVerify, it doesnt work
way 6: try to add each host:port in the end, it doesnt work

here are my testing sentences:

AAA: Vless Server domian
BBB: CloudFlare CDN domain
CCC: Fake IP=disguised website

way 1 : not use fake host = local > BBB > AAA > Website, it works.
glider -verbose -listen socks5://:11111 -forward wss://BBB:443,vless://123F155F-449E-4FF1-892C-D46ECE764B50@

want to add Fake IP = local > CCC > BBB > AAA > Website, all below not work
--------host + @ in the end
glider -verbose -listen socks5://:11111 -forward wss://BBB:443?host=CCC,vless://123F155F-449E-4FF1-892C-D46ECE764B50@BBB:443

glider -verbose -listen socks5://:11111 -forward wss://CCC:443?host=BBB,vless://123F155F-449E-4FF1-892C-D46ECE764B50@BBB:443

--------serverName + @ in the end
glider -verbose -listen socks5://:11111 -forward wss://CCC:443?serverName=BBB,vless://123F155F-449E-4FF1-892C-D46ECE764B50@BBB:443

glider -verbose -listen socks5://:11111 -forward wss://BBB:443?serverName=CCC,vless://123F155F-449E-4FF1-892C-D46ECE764B50@BBB:443

--------try tls://+ws:// > wss://
glider -verbose -listen socks5://:11111 -forward tls://BBB:443,ws://@/?host=CCC,vless://123F155F-449E-4FF1-892C-D46ECE764B50@

glider -verbose -listen socks5://:11111 -forward tls://CCC:443,ws://@/?host=BBB,vless://123F155F-449E-4FF1-892C-D46ECE764B50@

glider -verbose -listen socks5://:11111 -forward tls://BBB:443?serverName=CCC,ws://@/,vless://123F155F-449E-4FF1-892C-D46ECE764B50@

glider -verbose -listen socks5://:11111 -forward tls://CCC:443?serverName=BBB,ws://@/,vless://123F155F-449E-4FF1-892C-D46ECE764B50@

--------host + skipVerify + @ in the end
glider -verbose -listen socks5://:11111 -forward wss://BBB:443?host=CCC,vless://123F155F-449E-4FF1-892C-D46ECE764B50@BBB:443

glider -verbose -listen socks5://:11111 -forward wss://CCC:443?host=BBB,vless://123F155F-449E-4FF1-892C-D46ECE764B50@BBB:443

--------serverName + skipVerify + @ in the end
glider -verbose -listen socks5://:11111 -forward wss://CCC:443?serverName=BBB,vless://123F155F-449E-4FF1-892C-D46ECE764B50@BBB:443

glider -verbose -listen socks5://:11111 -forward wss://BBB:443?serverName=CCC,vless://123F155F-449E-4FF1-892C-D46ECE764B50@BBB:443

--------host + skipVerify + AAA in the end
glider -verbose -listen socks5://:11111 -forward tls://BBB:443?skipVerify=true,ws://@/?host=CCC,vless://123F155F-449E-4FF1-892C-D46ECE764B50@AAA.com:443

glider -verbose -listen socks5://:11111 -forward tls://CCC:443?skipVerify=true,ws://@/?host=BBB,vless://123F155F-449E-4FF1-892C-D46ECE764B50@AAA.com:443
--------serverName + skipVerify + AAA in the end
glider -verbose -listen socks5://:11111 -forward tls://BBB:443?skipVerify=true&serverName=CCC,ws://@/,vless://123F155F-449E-4FF1-892C-D46ECE764B50@AAA.com:443

glider -verbose -listen socks5://:11111 -forward tls://CCC:443?skipVerify=true&serverName=BBB,ws://@/,vless://123F155F-449E-4FF1-892C-D46ECE764B50@AAA.com:443
--------host + skipVerify + BBB in the end
glider -verbose -listen socks5://:11111 -forward tls://BBB:443?skipVerify=true,ws://@/?host=CCC,vless://123F155F-449E-4FF1-892C-D46ECE764B50@BBB:443

glider -verbose -listen socks5://:11111 -forward tls://CCC:443?skipVerify=true,ws://@/?host=BBB,vless://123F155F-449E-4FF1-892C-D46ECE764B50@BBB:443
--------serverName + skipVerify + BBB in the end
glider -verbose -listen socks5://:11111 -forward tls://BBB:443?skipVerify=true&serverName=CCC,ws://@/,vless://123F155F-449E-4FF1-892C-D46ECE764B50@BBB:443
--------host + skipVerify + CCC in the end
glider -verbose -listen socks5://:11111 -forward tls://CCC:443?skipVerify=true&serverName=BBB,ws://@/,vless://123F155F-449E-4FF1-892C-D46ECE764B50@BBB:443
--------serverName + skipVerify + CCC in the end
glider -verbose -listen socks5://:11111 -forward tls://BBB:443?skipVerify=true&serverName=CCC,ws://@/,vless://123F155F-449E-4FF1-892C-D46ECE764B50@CCC:443

glider -verbose -listen socks5://:11111 -forward tls://CCC:443?skipVerify=true&serverName=BBB,ws://@/,vless://123F155F-449E-4FF1-892C-D46ECE764B50@CCC:443

some logs:
2021/10/16 16:52:25 server.go:82: [socks5] 127.0.0.1:61393 <-> ip-api.com:80 via CCC:443, error in dial: x509: cannot validate certificate for CCC because it doesn't contain any IP SANs
2021/10/16 16:52:25 server.go:82: [socks5] 127.0.0.1:61397 <-> www.ip-api.com:443 via CCC:443, error in dial: x509: cannot validate certificate for CCC because it doesn't contain any IP SANs

**Comment by nadoo** [comment]
Hi @xtangliang , wss is not a proxy protocol, so we should use it as a protocol chain rather than a proxy chain, so:
```
glider -verbose -listen socks5://:11111 -forward wss://BBB:443?host=CCC,vless://123F155F-449E-4FF1-892C-D46ECE764B50@BBB:443
```
should be:
```
glider -verbose -listen socks5://:11111 -forward wss://BBB:443?host=CCC,vless://123F155F-449E-4FF1-892C-D46ECE764B50@
```


the `host` parameter is used in websocket Host header, and the `serverName` parameter is used as tls SNI, so how to run glider client is according to your server configuration, you can try it. or you can put your server configuration here as a reference.

**Comment by xtangliang** [comment]
it does not work
