### ISSUE TITLE
[Enhancement]: AF_VSOCK Support

### ISSUE THREAD

**Issue by gaby** [nadoo/glider#295]
Are there any plans to add VSOCK support for Glider?

**Comment by gaby** [comment]
Golang libraries to support this enhancement: 

https://github.com/linuxkit/virtsock

https://github.com/mdlayher/vsock

**Comment by gaby** [comment]
@nadoo Thoughts on this? VSOCKS are becoming a big thing for accessing hypervisors and using tools like `gvisor`, `firecracker`, `kata-containers`. Recent linux kernels support VSOCK natively.

**Comment by nadoo** [comment]
Thanks for your info, I'll add vsock support on linux version later.

**Comment by gaby** [comment]
Looking forward!

**Comment by nadoo** [comment]
Now with this [commit](https://github.com/nadoo/glider/actions/runs/2101928892) , we can use vsock like this:

host:
`glider -verbose -listen vsock://:1234,socks5://`

guest:
`glider -verbose -listen :1080 -forward vsock://2:1234,socks5://`

test on guest:
`curl -x http://127.0.0.1:1080 ifconfig.me`

**Comment by gaby** [comment]
@nadoo Thank you! Looking forward to testing this.

**Comment by nadoo** [comment]
> @nadoo Thank you! Looking forward to testing this. 

You can download binary file from the above link.

**Comment by gaby** [comment]
Thank you for this feature!
