### ISSUE TITLE
Enhancement: Add configuration possibilities

### ISSUE THREAD

**Issue by julianxhokaxhiu** [nadoo/glider#3]
I saw that you're using `flag` native package. Can you please consider using https://github.com/namsral/flag instead? Simple drop-in replacement, that would definitely enhance the binary running capabilities.

For eg. I can configure the binary via Environment variabiles and/or configuration files.

As an example of usage, you can see the fork I did time ago, of an existing project where i exactly added this functionality: https://github.com/julianxhokaxhiu/go-any-proxy/commit/b836c569773751d0b6d2182c20a87188fd19ddec

**Comment by nadoo** [comment]
Hi Julian, it's a great package and worked just as it said: "drop in replacement", but when I tried to add a parameter multiple times, sounds like it doesn't support now, as it said here: https://github.com/namsral/flag/blob/master/extras.go#L104

glider simply supports multiple upstream proxy servers using multiple "-f" flags, maybe there is a better way to achieve it, any ideas?

**Comment by julianxhokaxhiu** [comment]
I think you don't need to add it multiple times, you just need to make it a comma separated value ( as it is documented in your README ).

Did I miss the point where it could be used many times? Remember that the configuration is "one-per-process" if you give it as a config file, or "one-per-environment" if using Environment variables.

**Comment by nadoo** [comment]
"-f http://server1:port1,ss://method:pass@server2:port2"

The comma separated value means it's a proxy chain(first server1 then server2 then internet), different from multiple proxies.  😄 I'll think about how to achieve it while keeping it simple.

**Comment by nadoo** [comment]
Hi Julian, I've add simple config file support:
`glider -config xx.conf`

you can see https://github.com/nadoo/glider/blob/master/glider.conf.sample as an example.

**Comment by nadoo** [comment]
based on this simple package:
https://github.com/nadoo/conflag

**Comment by julianxhokaxhiu** [comment]
Thanks! I will check it asap :) Looking at the commit itself seems to be fine.
