### ISSUE TITLE
hope to add chacha20 encryption

### ISSUE THREAD

**Issue by laincat** [nadoo/glider#30]
I can only use this at the moment. . .

**Comment by nadoo** [comment]
Sorry for translating your text to English by Google translate.

Maybe you can use that with the ssr module like:
```
glider -verbose -listen :8443 -forward ssr://chacha20:pass@host:port?protocol=origin
```
not sure whether this working, you can give it a try.

**Comment by laincat** [comment]
not work...
```
glider -verbose -listen :1080 -forward ssr://chacha20:pass@host:port?protocol=origin
2018/07/12 15:37:03 [mixed] listening TCP on :1080
2018/07/12 15:37:03 [socks5-udp] listening UDP on :1080
2018/07/12 15:37:04 [socks5] failed to connect to target: [ssr] unsupported obfs type:
```

**Comment by laincat** [comment]
not work too...
```
glider -verbose -listen :1080 -forward ssr://chacha20:pass@host:port?protocol=auth_sha1_v4&obfs=tls1.2_ticket_auth&obfs_param=bing.com
2018/07/12 15:38:48 [mixed] listening TCP on :1080
2018/07/12 15:38:48 [socks5-udp] listening UDP on :1080
2018/07/12 15:38:49 [socks5] failed to connect to target: [ssr] unsupported obfs type:
```

**Comment by nadoo** [comment]
guess you have a ss server with chacha20 encryption method, use ssr module, set obfs to `plain` and protocol to `origin`
```
glider -verbose -listen :8443 -forward "ssr://chacha20:pass@host:port?protocol=origin&obfs=plain"
```

**Comment by laincat** [comment]
There is work, but unable to connect.

I test：
```
glider -verbose -listen :1080 -forward "ssr://chacha20:pass@host:port?protocol=origin&obfs=plain"
```
```
glider -verbose -listen :1080 -forward ssr://chacha20:pass@host:port?protocol=auth_sha1_v4&obfs=tls1.2_ticket_auth&obfs_param=bing.com
```

**Comment by nadoo** [comment]
glider uses this [lib](https://github.com/sun8911879/shadowsocksR) to support ssr, according to the README file, I think it should be supported.

have you tried double quote `"` around the ssr url like:
```
glider -verbose -listen :1080 -forward "ssr://chacha20:pass@host:port?protocol=auth_sha1_v4&obfs=tls1.2_ticket_auth&obfs_param=bing.com"
```
?

**Comment by laincat** [comment]
Yes,unable to connect...

**Comment by nadoo** [comment]
what is the log of glider?

**Comment by laincat** [comment]
```
glider -verbose -listen :1080 -forward "ssr://chacha20:pass@host:port?protocol=auth_sha1_v4&obfs=tls1.2_ticket_auth&obfs_param=bing.com"
2018/07/13 11:59:46 [mixed] listening TCP on :1080
2018/07/13 11:59:46 [socks5-udp] listening UDP on :1080
2018/07/13 11:59:47 [socks5] 127.0.0.1:52036 <-> 91.108.56.110:443
2018/07/13 11:59:47 [socks5] 127.0.0.1:52038 <-> 91.108.56.110:80
2018/07/13 11:59:47 [socks5] 127.0.0.1:52037 <-> [2001:b28:f23f:f005::a]:443
2018/07/13 11:59:51 [socks5] 127.0.0.1:52044 <-> www.google.com:443
2018/07/13 11:59:51 [socks5] 127.0.0.1:52047 <-> [2001:b28:f23f:f005::a]:443
2018/07/13 11:59:51 [socks5] 127.0.0.1:52046 <-> 91.108.56.110:443
2018/07/13 11:59:51 [socks5] 127.0.0.1:52050 <-> 91.108.56.110:80
2018/07/13 11:59:51 [socks5] 127.0.0.1:52052 <-> twitter.com:443
2018/07/13 11:59:52 [socks5] 127.0.0.1:52054 <-> twitter.com:443
2018/07/13 11:59:54 [socks5] 192.168.200.200:51190 <-> 149.154.171.5:443
2018/07/13 11:59:54 [socks5] 192.168.200.200:51191 <-> 149.154.171.5:443
2018/07/13 11:59:55 [socks5] 127.0.0.1:52058 <-> 149.154.175.50:443
2018/07/13 11:59:55 [socks5] 127.0.0.1:52059 <-> [2001:b28:f23d:f001::a]:443
2018/07/13 11:59:55 [socks5] 127.0.0.1:52062 <-> 149.154.175.50:80
2018/07/13 11:59:56 [socks5] 127.0.0.1:52065 <-> [2001:b28:f23d:f001::a]:443
2018/07/13 11:59:56 [socks5] 127.0.0.1:52064 <-> 149.154.175.50:443
2018/07/13 11:59:56 [socks5] 127.0.0.1:52068 <-> 149.154.175.50:80
2018/07/13 11:59:58 [socks5] 127.0.0.1:52070 <-> 149.154.175.50:443
2018/07/13 11:59:58 [socks5] 127.0.0.1:52071 <-> [2001:b28:f23d:f001::a]:443
2018/07/13 11:59:58 [socks5] 127.0.0.1:52072 <-> 149.154.175.50:80
2018/07/13 11:59:59 [socks5] 127.0.0.1:52076 <-> 91.108.56.110:443
2018/07/13 11:59:59 [socks5] 127.0.0.1:52080 <-> 91.108.56.110:80
2018/07/13 11:59:59 [socks5] 127.0.0.1:52077 <-> [2001:b28:f23f:f005::a]:443
2018/07/13 12:00:02 [socks5] 127.0.0.1:52085 <-> [2001:b28:f23d:f001::a]:443
2018/07/13 12:00:02 [socks5] 127.0.0.1:52084 <-> 149.154.175.50:443
2018/07/13 12:00:02 [socks5] 127.0.0.1:52088 <-> 149.154.175.50:80
```

**Comment by nadoo** [comment]
Maybe the ssr [lib](https://github.com/sun8911879/shadowsocksR) is not compatible with your ssr server. I don't often use ssr, I tested it with a ssr server with `auth_aes128_md5` and `tls1.2_ticket_auth`, and it worked, haven't tried it with other protocols and obfs types. I'll look into it some time later, thanks for your response!

**Comment by laincat** [comment]
Thank you for your work.
glider is a good project.

**Comment by rankjie** [comment]
Ran into the same issue with `chacha20`

Tried `ssr://chacha20:pass@host:port?protocol=origin&obfs=plain`, it connects to the server but the server yields `tcprelay.py:1097 can not parse header when handling connection from`.
(FYI. Glider reports: `read: connection reset by peer`)

Since the original SSR project is gone, I'm testing against the version found here: [https://github.com/shadowsocksr-backup/shadowsocksr/tree/manyuser](https://github.com/shadowsocksr-backup/shadowsocksr/tree/manyuser)

I really hope this works out...

BTW. Is there anyway to contact you @nadoo personally? Or maybe just a page that I can donate to support this project :) 

Thanks for your work 👍

**Comment by nadoo** [comment]
Hi @rankjie , I write glider for my personal use on linux gateway, I'm very happy that it can be used by so many peoples. Any issues or PRs will be appreciated and no donation is needed, thank you very much!

According to your question, what is the config of your ssr server? the protocol is `origin` and obfs is `plain`? if though, maybe I can add `chacha20` support to the ss lib directly.

**Comment by rankjie** [comment]
I'm using the `manyuser` branch with `mudb.json`. Anyway, the config file should almost the same as a normal one.

```
[
  {
        "d": 0,
        "enable": 1,
        "method": "chacha20",
        "obfs": "plain",
        "obfs_param": "",
        "passwd": "abcdefg",
        "port": 12345,
        "protocol": "origin",
        "protocol_param": "",
        "transfer_enable": 9007199254740992,
        "u": 0,
        "user": 1,
        "forbidden_port": ""
    }
]
```

I can use other client Apps such as `sslocal`, `Shadowrocket`/`Surge for iOS` without any issue.

Thanks for your reply, looking forward to any changes.

**Comment by nadoo** [comment]
Now you can try v0.6.8 with `chacha20` support: 
https://github.com/nadoo/glider/releases/tag/v0.6.8

**Comment by nadoo** [comment]
```glider -verbose -listen :8443 -forward ss://chacha20:pass@host:port```

**Comment by nadoo** [comment]
@laincat , chacha20 is supported now, I'll close this issue, feel free to reopen it if there's any problem.
