### ISSUE TITLE
question about the ipset and rule file

### ISSUE THREAD

**Issue by Sirius2016** [nadoo/glider#300]
glider默认走代理(访问谷歌)，ipset列表直连不生效，访问www.baidu.com时也是走代理，正确的情况应该是直连（DIRECT）。
glider.conf
![image](https://user-images.githubusercontent.com/23203953/145188684-c1805f35-86a8-407a-8bac-af59adb061d2.png)

bypass.rule
![image](https://user-images.githubusercontent.com/23203953/145188785-46ea3126-6182-4a9e-a77f-c78c138c5c7f.png)

**Comment by nadoo** [comment]
Hi, you should add `domain=baidu.com` in your rule file.
