### ISSUE TITLE
Does glider support foward socks5 udp to upstream server?

### ISSUE THREAD

**Issue by bak003** [nadoo/glider#304]
eg:
client --> server 1 -> server2 -> internet

```
client:  socks5 client with username/password which connect to server1
server1:  ./glider -listen socks5://:1081 -forward socks5://username:password@<server2 IP>:1081  -verbose
server2:  standard socks5 server which listen on 1081 and auth is username/password
```

test result: tcp pass, udp failed

log:
```
2022/01/05 23:47:06 server.go:150: [socks5u] <server1 IP>:2063 <-> 8.8.8.8:53 via <server2 IP>:1081
2022/01/05 23:47:07 server.go:90: [socks5] <server1 IP>:2076 <-> www.baidu.com:80 via <server2 IP>:1081, relay error: readfrom tcp <server1 IP>:55353-><server2 IP>:1081: splice: connection reset by peer
2022/01/05 23:47:10 server.go:150: [socks5u] <server1 IP>:2064 <-> 208.67.222.222:53 via <server2 IP>:1081
2022/01/05 23:47:13 server.go:150: [socks5u] <server1 IP>:2065 <-> 223.5.5.5:53 via <server2 IP>:1081
```

**Comment by nadoo** [comment]
Yes, udp is supported. 

Let's setup a small udp tunnel via sock5 proxy and test it with dns requests to see whether it worked:

dig --> udp tunnel(127.0.0.1:53) --> socks5 server --> 8.8.8.8:53

- socks5 server:
   `./glider -verbose -listen socks5://:1080`
- udp tunnel via socks5 server (all udp requests will be sent to 8.8.8.8:53 via the above socks5 server):
   `./glider -verbose -listen udp://:53 -forward socks5://127.0.0.1:1080,udp://8.8.8.8:53`

Then we can test it with dig: `dig @127.0.0.1 163.com`, and we can get the result from 8.8.8.8:53.

**Comment by nadoo** [comment]
Yes, udp is supported. 

Let's setup a small udp tunnel via sock5 proxy and test it with dns requests to see whether it worked:

dig --> udp tunnel(127.0.0.1:53) --> socks5 server --> 8.8.8.8:53

- sever2: socks5 server:
   `./glider -verbose -listen socks5://:1080`
- server1: udp tunnel via socks5 server (all udp requests will be sent to 8.8.8.8:53 via the above socks5 server):
   `./glider -verbose -listen udp://:53 -forward socks5://127.0.0.1:1080,udp://8.8.8.8:53`

Then we can test it with dig: `dig @127.0.0.1 apple.com`, and we can get the result from 8.8.8.8:53.

For your question, I think you'd better check your server or client settings and find out the problem.
