### ISSUE TITLE
Does glider forward server use client auth info?

### ISSUE THREAD

**Issue by ztitin** [nadoo/glider#305]
eg:
client --> server 1 -> server 2 -> internet
```
client:  http client with username/password connect to server1
server1:  ./glider -listen http://:8080 -forward http://<server2 IP>:8080  -verbose
```
in this case does glider can use client credential username/password to the forward server2, i think like `cache_peer suqid login=PASSTHRU`

**Comment by nadoo** [comment]
What's the mean of set up a forward loop? 
server1 : `-listen http://:8080 -forward http://<server1 IP>:8080`

**Comment by ztitin** [comment]
> What's the mean of set up a forward loop? server1 : `-listen http://:8080 -forward http://<server1 IP>:8080`

yeah this is my fault, i had change the question case and  i just want to know does server2 can use the credential from the client thanks for you reply

**Comment by nadoo** [comment]
No, but maybe you can setup a tcp forwarder to achieve the goal:
server1: `glider -verbose -listen tcp://:8080 -forward tcp://<server2 IP>:8080`

Or you can setup a local glider server on your client like:
client: `glider -verbose -listen :8443 -forward http://user:pass@server1:8080,http://user:pass@server2:8080`
then use the local proxy server in your browser.

**Comment by ztitin** [comment]
> No, but maybe you can setup a tcp forwarder to achieve the goal: server1: `glider -verbose -listen tcp://:8080 -forward tcp://<server2 IP>:8080`
> 
> Or you can setup a local glider server on your client like: client: `glider -verbose -listen :8443 -forward http://user:pass@server1:8080,http://user:pass@server2:8080` then use the local proxy server in your browser.

i try the first method and the server 2 can not get the auth info from client, for second method because the forward server auth info is dynamic so can't write directly in the command line.

**Comment by nadoo** [comment]
The method 1 is just a tcp port forwarder, the client's http server is http://server1:8080, and it's http auth info **should** be forwarded to server2..

BTW, may I know why you need Server1 here? The Server1 and Server2 uses the same credential? Which one runs glider? Do you have management rights of them?

**Comment by ztitin** [comment]
> The method 1 is just a tcp port forwarder, the client's http server is http://server1:8080, and it's http auth info **should** be forwarded to server2..
> 
> BTW, may I know why you need Server1 here? The Server1 and Server2 uses the same credential? Which one runs glider? Do you have management rights of them?

server1 is using glider. In some case server2 can't get the auth info from client side so i want to add server1 here to forward auth again to the server2 i try to use squid cache_peer can implement this but efficiency is low.

**Comment by nadoo** [comment]
Maybe you should find out the real reason why server2 sometimes can not get the auth info from client.

The http proxy server should remove client's auth info before forwarding it for security reasons, and glider uses a flexible but simple architecture so it's not easy to add the feature like squid, sorry!

**Comment by phantomcraft** [comment]
/\

glider -listen socks5://demo:demo@gliderip:1080 -forward http://user:password@haproxyip:3128

Replace 3128 with the HAProxy port.
