### ISSUE TITLE
Please improve the parse speed of rule config file 

### ISSUE THREAD

**Issue by ricky1203** [nadoo/glider#306]
I have a large rule list with many domain list (about 69k lines) and cidr (about 8k lines), the glider need about 30 seconds to load the config file, Please optimize the config parsing process for modify the domain rule config file frequently
thanks

**Comment by nadoo** [comment]
Thanks for your test! glider uses the Golang's command line parser [flag](https://pkg.go.dev/flag) to parse cli and config files, maybe it's not suitable for loading large files, I'll consider to improve it later.

**Comment by nadoo** [comment]
Hi @ricky1203 , I've made a small change to speed up the rule loading process, you can try the attachment if you need.
[glider-dev-linux-amd64.zip](https://github.com/nadoo/glider/files/7965302/glider-dev-linux-amd64.zip)

**Comment by nadoo** [comment]
[glider-dev-linux-arm64.zip](https://github.com/nadoo/glider/files/8053964/glider-dev-linux-arm64.zip)

**Comment by ricky1203** [comment]
@nadoo great improvement, only take about 2 seconds to parse the whole rule files

**Comment by nadoo** [comment]
Closing as v0.16.0 released: https://github.com/nadoo/glider/releases/tag/v0.16.0
