### ISSUE TITLE
socks6:// in config example (typo?)

### ISSUE THREAD

**Issue by streaps** [nadoo/glider#309]
https://github.com/nadoo/glider/blob/2d16870803df8364c67a0e591b462fb16de4f0a5/config/examples/7.rule_multiple_rule_files/rules.d/home.rule#L6

socks6 looks like a typo? (or are you going to add [socks6](https://datatracker.ietf.org/doc/html/draft-olteanu-intarea-socks-6-11) support?)

**Comment by nadoo** [comment]
It's a typo, socks6 is in draft status and not widely supported, so it's not a high priority to support it.
