### ISSUE TITLE
go get reported 'proxyconnect tcp: EOF' with glider proxy

### ISSUE THREAD

**Issue by ansiz** [nadoo/glider#31]
I'm using glider to proxy HTTP forwards SOCKS5, it works well with most scenarios, I can get correct response with `curl golang.org` and `wget golang.org`, but I can't use `go get` to download golang vendor package from golang.org with the proxy.
```bash
go get golang.org/x/net/html
package golang.org/x/net/html: unrecognized import path "golang.org/x/net/html" (https fetch: Get https://golang.org/x/net/html?go-get=1: proxyconnect tcp: EOF)
```

I'm using shadowsocks-qt as the SOCKS5 proxy,  it works well, here is my glider configuration:
```
listen=:1087
forward=socks5://127.0.0.1:1080
```
can you give me a little clue?Thanks

**Comment by nadoo** [comment]
tested on windows with:
```
set http_proxy=http://127.0.0.1:1087
set https_proxy=http://127.0.0.1:1087
go get -u golang.org/x/net/html
```
it worked well..  

do you always get that error? 
have you set any proxy for git? https://github.com/golang/go/wiki/GoGetProxyConfig

**Comment by ansiz** [comment]
Thanks for your reply.
I did not set any proxy for git and always got this error this morning, but I try again in the same way after you replied, it worked...
I will try to debug this problem if it reappear, maybe it's my problem.
