### ISSUE TITLE
Missing scheme information on script health check

### ISSUE THREAD

**Issue by nil0x42** [nadoo/glider#310]
Hi !
I've started using `check=file://FILE`. But i noticed an annoying limitation:
the scheme of the forwarder is not provided through env.

For example, if i have:

```
forward=https://myhttpsproxy.com:8443
forward=socks5://1.1.1.1:1080
```

My script only receives `1.1.1.1:1080` or `myhttpsproxy.com:8443`, and there is no way for my script to know if it should check an https or socks5 proxy.

Recommendation:
add `FORWARDER_SCHEME` to env

**Comment by nadoo** [comment]
Hi @nil0x42 , as we can set proxy/protocol chain in forwarder like `forward=https://myhttpsproxy.com:8443,socks5://1.1.1.1:1080`, it'll mislead people when just give them schemes.

I'll add the `FORWARDER_URL` to env, so user can handle it in the script.

**Comment by nil0x42** [comment]
great !
