### ISSUE TITLE
Env Variables

### ISSUE THREAD

**Issue by Alukardz** [nadoo/glider#311]
How could I specify and env variable as entry for host, port, username or password in the forwarder flag?

**Comment by nadoo** [comment]
Hi @Alukardz , glider supports multiple forwarders and forwarder chains, so it's not supported cuz it's hard to determine which forwarder will use the environment variables.

**Comment by emptyteeth** [comment]
Maybe we could do this
https://caddyserver.com/docs/caddyfile-tutorial#environment-variables

**Comment by Alukardz** [comment]
> 

Yes, this. In my use case, the proxy I connect to has user:pass, but it's more secure if those are env vars and not saved in the config file.

**Comment by nadoo** [comment]
> > 
> 
> Yes, this. In my use case, the proxy I connect to has user:pass, but it's more secure if those are env vars and not saved in the config file.

It's easy to get values of environment variable, but for a config file, you can control the access by chmod, it's more secure.

**Comment by nadoo** [comment]
Closing as v0.16.0 released: https://github.com/nadoo/glider/releases/tag/v0.16.0
