### ISSUE TITLE
Load balancing based on ping value.

### ISSUE THREAD

**Issue by 669800** [nadoo/glider#316]
```

glider -verbose -listen tcp://:1234 -forward tcp://serverA:1111 -forward tcp://serverB:2222 -check tcp -strategy lha

```

Will it still work if my network operator blocks the ping protocol (ICMP)?

**Comment by 669800** [comment]
> yes, it's tcp ping, does not use icmp.

Will it make me switch to the fastest node in real time?

**Comment by 669800** [comment]
> Yes, but if you just need a tcp load balancer, I suggest you use haproxy instead.

A low-latency server can't be used as a priority node after it dies for a period of time, and glider will always use a high-latency node until it dies before switching to a low-latency node.

**Comment by 669800** [comment]
> try change the config values like: `-checklatencysamples 1 -maxfailures 1 -checkinterval 1`
> 
> 
> 
> again, I suggest to use haproxy if you only need tcp load balance features.

The load balancing scheduling algorithm of glider needs more improvement.

![image](https://user-images.githubusercontent.com/27992255/158794689-4ded1479-b07c-47ed-8e7c-a021756b422a.jpeg)

**Comment by nadoo** [comment]
In `lha` mode, glider will choose the lowest latency node when a new request is made.

the latency value is the average value of latest 10(can be changed by -checklatencysamples) check latencies, and updated in each checking.

so you can change the `checklatencysamples` option to 1 to achieve the goal you want, have you tried it?
`glider -verbose -listen tcp://:1234 -forward tcp://serverA:1111 -forward tcp://serverB:2222 -check tcp -strategy lha -checklatencysamples 1`

**Comment by 669800** [comment]
> In `lha` mode, glider will choose the lowest latency node when a new request is made.
> 
> 
> 
> the latency value is the average value of latest 10(can be changed by -checklatencysamples) check latencies, and updated in each checking.
> 
> 
> 
> so you can change the `checklatencysamples` option to 1 to achieve the goal you want, have you tried it?
> 
> `glider -verbose -listen tcp://:1234 -forward tcp://serverA:1111 -forward tcp://serverB:2222 -check tcp -strategy lha -checklatencysamples 1`

Is it possible to add packet loss check?
