### ISSUE TITLE
vmess no matches foun

### ISSUE THREAD

**Issue by he-jialin** [nadoo/glider#320]
./glider --listen=:1080 forward=vmess://none:a336a542-90bf-36bb-9be4-c6d33d7f08ed@bgpsh.test.com:12001?alterID=0
zsh: no matches found: forward=vmess://none:a336a542-90bf-36bb-9be4-c6d33d7f08ed@bgpsh.test.com:12001?alterID=0

**Comment by nadoo** [comment]
Use`"` in cli:
```
./glider -verbose -listen=:1080 -forward="vmess://none:a336a542-90bf-36bb-9be4-c6d33d7f08ed@bgpsh.test.com:12001"
```

or use a config file: glider.conf
```
verbose
listen=:1080
forward=vmess://none:a336a542-90bf-36bb-9be4-c6d33d7f08ed@bgpsh.test.com:12001
```
```
./glider -config glider.conf
```
