### ISSUE TITLE
can't proxy socks5 via ssh forwarder

### ISSUE THREAD

**Issue by ansoda** [nadoo/glider#324]
hello, my config:

`glider --listen :8443 --forward 'ssh://root@xx.xx.xx.xx:22?key=myprivate&timeout=5'`

error in dial: ssh: unexpected packet in response to channel open: <nil>

can't proxy socks5 via ssh forwarder.
Is there any problem with my use, thank you.

**Comment by nadoo** [comment]
Try other ssh clients and see whether they worked?

**Comment by ansoda** [comment]
Other ssh clients have no problem logging in via username and private key.

**Comment by ansoda** [comment]
I think this bug is easy to reproduce.

**Comment by nadoo** [comment]
> I think this bug is easy to reproduce.

I've tested and no problem here.

**Comment by nadoo** [comment]
> Other ssh clients have no problem logging in via username and private key.

Don't just test login, test socks forwarding.

**Comment by ansoda** [comment]
SSH login and forwarding are normal. But glider proxy reports an error: error in dial: ssh: unexpected packet in response to channel open: <nil>

```
ssh server: OpenSSH_8.2p1 Ubuntu-4, OpenSSL 1.1.1f， Ubuntu-v20.04's default ssh server.
ssh client:   OpenSSH_8.6p1, LibreSSL 3.3.5
tabby ssh client: tabby-v1.0.176

```

**Comment by ansoda** [comment]
Does ssh have header blocking? Because sock5 is mostly short connections, if one of socks5 requests timeout or an error occurs, it will cause all subsequent requests to timeout or error?

**Comment by nadoo** [comment]
setup a local sock5 forwarding proxy server:
```
ssh -f -N -D :8443 root@xx.xx.xx.xx
```

use curl to test the socks5 proxy:
```
curl -x socks5://127.0.0.1:8443 api.ipify.org
```

whether it worked?

**Comment by ansoda** [comment]
This works fine, curl returns the server's ip.

**Comment by nadoo** [comment]
> This works fine, curl returns the server's ip.

Oh no... -_-! I tested on debian11 and all works fine, maybe I should get an ubuntu server.

**Comment by nadoo** [comment]
It always failed or failed after some time?

**Comment by ansoda** [comment]
I compared glider ssh forwarder and standard ssh forwarder
`glider --listen :8443 --forward 'ssh://root@xx.xx.xx.xx:22?key=myprivate&timeout=5'
`
and
`ssh -N -D :8443 root@xx.xx.xx.xx`

request:
`curl -x socks5://127.0.0.1:8443 api.ipify.org` 

In both ways, the curl it works fine, but it takes longer for the glider forwarder to return.
As a result, this is particularly obvious when accessing web pages. The speed of opening web pages through standard ssh forwarder is very fast, while the speed of opening web pages through glider is very slow, or even impossible to open at all.

**Comment by nadoo** [comment]
So it worked with glider now? anything changed?

**Comment by ansoda** [comment]
There is no change. I did not use curl but the browser web page to test. Maybe some urls in the web page return slowly or some urls do not return, causing the page to fail to open. I thought there was a problem. But standard ssh doesn't have this problem.
Simply use curl to access a url, and the glider works fine, but it feels slower than standard ssh.
I wonder if the standard ssh is a long link, and each glider request is caused by a short connection.

**Comment by nadoo** [comment]
Hi @ansoda , thanks for your report!  you can download and try the dev version here if you need: https://github.com/nadoo/glider/actions/runs/2274744274

**Comment by nadoo** [comment]
This issue was closed by the latest commit, feel free to reopen it if there's still any problem.

**Comment by ansoda** [comment]
Thank you so much, you are great, I just tested it and it works fine.
