### ISSUE TITLE
[feature request] DNS over https behind proxy

### ISSUE THREAD

**Issue by t-chab** [nadoo/glider#328]
Hi, and thanks for your great work with glider.

It would be very nice to be able to use glider as a dns forwarder to a doh resolver ([Cloudflare 1.1.1.1](https://1.1.1.1/) for instance) behind an http proxy.

Use case: ease the setup of web access on VMs used for training sessions in a corporate network.

There seems to be an existing golang implementation [here](https://github.com/nextdns/nextdns) but this tools does not have all the nice features of glider.

**Comment by xlighting2017** [comment]
<img width="733" alt="image" src="https://user-images.githubusercontent.com/25970065/172809275-3d5cf228-a444-41fb-8b25-05433e050001.png">


but using a proxy tool as a DNS forwarder seems to be a very big overkill....

**Comment by t-chab** [comment]
I'm not sure to understand, or perhaps I'm miss something in the doc, but it does not seems to have a dns listener on port 53.

Here's what I try to achieve : 

![image](https://user-images.githubusercontent.com/2120966/173025782-dd26402b-f2fb-4efe-b862-9380c54731a8.png)


> but using a proxy tool as a DNS forwarder seems to be a very big overkill....

Yeah, I know, but it's the only way I found to have a remote dns resolution working.

**Comment by nadoo** [comment]
Hi @t-chab , so you can use glider like this:

`glider -config glider.conf`

glider.conf
```
verbose

listen=:8080
forward=http://Server:Port

dns=:53
dnsserver=1.1.1.1
dnsserver=8.8.8.8
```

glider will communicate with 1.1.1.1 with dns over tcp protocol and forward by the corporate proxy (must support http CONNECT method).

**Comment by t-chab** [comment]
Hi @nadoo, and thanks a lot !

Now , if I understand the documentation correctly, and if I want to add local dns resolution for my local domains, I just have to add a _rulefile_ line with the local dns resolver ip, and a custom domain to map _mycompany.com_ to this resolver ?

Something like that : 

```
# glider.conf
verbose

listen=:8080
forward=http://Server:Port

dns=:53
dnsserver=1.1.1.1
dnsserver=8.8.8.8
rulefile=custom.rule
```

```
# custom rule file
dnsserver=192.168.1.254
domain=mycompany.com
```

**Comment by nadoo** [comment]
> Hi @nadoo, and thanks a lot !
> 
> Now , if I understand the documentation correctly, and if I want to add local dns resolution for my local domains, I just have to add a _rulefile_ line with the local dns resolver ip, and a custom domain to map _mycompany.com_ to this resolver ?
> 
> Something like that :
> 
> ```
> # glider.conf
> verbose
> 
> listen=:8080
> forward=http://Server:Port
> 
> dns=:53
> dnsserver=1.1.1.1
> dnsserver=8.8.8.8
> rulefile=custom.rule
> ```
> 
> ```
> # custom rule file
> dnsserver=192.168.1.254
> domain=mycompany.com
> ```

Yes, I think it will work, you can try it.

**Comment by t-chab** [comment]
@nadoo : just tester, it works very well. Thanks a lot for your time and your awesome software :+1:
