### ISSUE TITLE
listen DNS and redirect all traffic to a proxy

### ISSUE THREAD

**Issue by sorriso309** [nadoo/glider#33]
I would like to access a proxy server through a listen DNS

Example:

client with dns 10.0.0.1 in resolv.conf:
wget http://site.com/image.png >> send resquisition to dns resolve "site.com" >> resquisition sent to dns server 10.0.0.1 >> resquisition sent to proxy 10.0.0.1

response:
"site.com" is 123.123.123.123 >> response and file sent to the proxy 10.0.0.1 >> response and file sent to dns 10.0.0.1 >> response and file sent to the client to download "http://site.com/image.png"

**Comment by nadoo** [comment]
Do you want to transfer data over dns request and response? glider doesn't support this feature, maybe you can have a look at: https://github.com/yarrick/iodine

**Comment by sorriso309** [comment]
but with this project I can do the redirection for only one site? I need to redirect all sites.

because I wanted to apply proxy technology to routers through DNS.

**Comment by nadoo** [comment]
Haven't tested that yet, but I think if it can connect tcp server and client via dns protocol, just setup proxies(like glider) both on server and client side, then you can send net request to the proxy client, it will 
 forward request via dns(iodine) to the proxy server, then the proxy server can send the request out, it should work.

**Comment by everyx** [comment]
@sorriso309 Do you mean supports forward and reverse proxy (SNI) feature like [goproxy](https://github.com/snail007/goproxy)?
