### ISSUE TITLE
About DNS resolving problem

### ISSUE THREAD

**Issue by Sak94664** [nadoo/glider#34]
I tried to using it to bypass dns poisoning to access some sites(wikipedia,etc.) without changing my ip.I set up a dnscrypt-proxy on my android device.and I set global remote dns server as 127.0.0.1:5353(where dnscrypt-proxy bind).But when I tried to access wikipedia using configured browser(switchyomega through socks on Firefox),it doesn't resolve the correct ip address(in logs it is resolved 31.13.**.**,but these ip are not accessible in China).

Is it a general issue or some errors in my configuration ?
(compiled using go 1.10.3 arm64 in Termux)

this is my config:

verbose=True
listen=http://127.0.0.1:4573
listen=socks5://127.0.0.1:1085
dnsserver=127.0.0.1:5353

**Comment by nadoo** [comment]
Hi @Sak94664 , glider only uses the dnsserver setting to forward dns request(client -> glider:53->forwarder->dnsserver), not used in the the http/socks5 proxy request. maybe you can change your host's dns to glider's dns listen address(default to ip:53), then it should work. I'll consider about adding the ability to do customized dns request in proxies later.

BTW, glider can achieve your purpose without dnscrypt-proxy, you can set up a rule file like this:

- glider.conf
  ```bash
  verbose=True
  listen=http://127.0.0.1:4573
  listen=socks5://127.0.0.1:1085
  dns=:53
  dnsserver=1.1.1.1:53

  # include a rules folder
  rules-dir=rules.d
  ```

- rules.d/my.rule (put `my.rule` in `rules.d` folder)
  ```bash
  forward=ss://method:pass@host:port

  # specify a different dns server, so all requests(both dns and socks5) to the domains below will be forwarded to 8.8.8.8:53 via the above forwarders, you can get a more suitable ip which near by your forwarder proxy.
  dnsserver=8.8.8.8:53

  domain=wikipedia.org
  domain=google.com
  ```

- test glider's dns
   ```bash
  dig @127.0.0.1 port 53 www.wikipedia.org
   ```

you can see: https://github.com/nadoo/glider/tree/master/config/examples/9.transparent_proxy_without_dnsmasq as an example

**Comment by Sak94664** [comment]
but is there any non-root solution?
as shadowsocks python port can not redirect dns queries to proxy server either.(all of the dns queries are transferred in unencrypted method which can be poisoned by gfw)(dislikes gfw)
now I only know daedalus app using tun device to redirect dns queries to nonroot ports(5353,etc.),but it drains battery a lot.

It will be amazing if it can customize dns requests in proxies :)

**Comment by nadoo** [comment]
you can let glider listening (dns) on port above 1024, then it doesn't need the root privilege.

as the `my.rule` showed, all dns request to `wikipedia.org` will be forward to 8.8.8.8:53 in tcp **via the forwarder `ss://method:pass@host:port`**, that's encrypted and will not be poisoned.

**Comment by nadoo** [comment]
If you only need http or socks5 proxy locally, you can add a remote ss forwarder in your config, then requests from http or socks5 client will be forwarded to the remote ss server, and domains will be resolved on the remote server, it will not be poisoned.

**Comment by Sak94664** [comment]
but is that possible not to use any forwarder?
e.g. gfw only poison 53 port.But if I resolve over port 5353,it won't be poisoned.

changed to this.

glider.conf

    verbose=True
    listen=http://127.0.0.1:4573
    listen=socks5://127.0.0.1:1085
    dnsserver=208.67.222.222:5353
    rules-dir=rules.d


office.rule

    dnsserver=208.67.222.222:5353
    domain=*.torproject.org
    domain=zh.wikipedia.org
    domain=duckduckgo.com
    domain=*.duckduckgo.com

but it is still affected.

**Comment by nadoo** [comment]
If you don't use forwarder, you can use wireshark or tcpdump to see whether glider forwarded dns requests to 208.67.222.222:5353, and see whether that will be poisoned or not.

`domain=duckduckgo.com` will including all subdomains, so *.xxx.com is not needed.(and not supported)

**Comment by Sak94664** [comment]
checked tcpdump.It uses ISP's DNS and returned a poisoned answer(checked dns ip address),visited the domain listed above.

**Comment by nadoo** [comment]
glider.conf
```
verbose=True
dns=:53
dnsserver=208.67.222.222:5353
```
with this config, glider will listen at :53 as a dns server, test it with dig or nslookup, `dig @127.0.0.1 port 53 www.wikipedia.org`, the dns request will surely sent to 208.67.222.222:5353. 

and as said in above post, http or socks5 request will not use dnsserver setting now.

**Comment by nadoo** [comment]
and if you use a forwarder, the http and socks5 request from the client will be forwarded to upstream forwarder, and domain's in the request will be resolved by the upstream forwarder server.

**Comment by Sak94664** [comment]
Now it is ok.with correct answer :)
    2018/07/20 06:31:31 [dns] 127.0.0.1:40709 <-> 208.67.222.222:5353, type: 1, port:                 
    2018/07/20 06:31:32 [dns] 127.0.0.1:37898 <-> 208.67.222.222:5353, type: 1, 53:                   
    2018/07/20 06:31:33 [dns] 127.0.0.1:39132 <-> 208.67.222.222:5353, type: 1, www.wikipedia.org: 198.35.26.96,

**Comment by nadoo** [comment]
OK, I'll add this feature later.

**Comment by nadoo** [comment]
adding the feature needs some time, now you can use glider's rule file like this:

glider.conf
```
verbose=True
listen=http://127.0.0.1:4573
listen=socks5://127.0.0.1:1085
dns=:53
dnsserver=114.114.114.114:5353
rules-dir=rules.d
```

office.rule
```
dnsserver=208.67.222.222:5353
domain=torproject.org
domain=wikipedia.org
domain=duckduckgo.com
```

and **set your host's dns(/etc/resolv.conf) to `127.0.0.1`**, then only the domains listed in office.rule will be sent to 208.67.222.222:5353, others will be sent to 114.114.114.114:5353

**Comment by Sak94664** [comment]
@nadoo Thanks a lot :)
