### ISSUE TITLE
Feature suggestion: scrub IPv6 addresses in DNS response 

### ISSUE THREAD

**Issue by netheril96** [nadoo/glider#341]
When I put glider in the transparent proxy mode, it is easy to set IPv4 gateway and DNS server on each device, but I have found no way to set IPv6 gateway on my phones and TV box.  In this case, if the device chooses to connect to the IPv6 address of google.com (for example), it bypasses the transparent proxy and then gets blackholed. 

I don’t want to disable IPv6 entirely. An alternative solution is for glider to remove AAAA records from DNS responses so that for the domains listed in its config, end user devices always route v4.

**Comment by emptyteeth** [comment]
https://github.com/nadoo/glider/blob/d57d35c062dbe03de54c9c9f6ca542df44edeb92/config/glider.conf.example#L251-L252
