### ISSUE TITLE
Add support for Golang 1.19

### ISSUE THREAD

**Issue by gaby** [nadoo/glider#342]
Any plans to make a release using Golang 1.19?

**Comment by gaby** [comment]
Ping @nadoo what's the status of `glider`, are there plans to keep maintaining it?

**Comment by gaby** [comment]
Still valid

**Comment by nadoo** [comment]
Hi @gaby , sorry for late response, I can release a new version using Go1.20, will this solve your problem?

**Comment by gaby** [comment]
@nadoo Yes, that would be great! Thanks
