### ISSUE TITLE
Create tcp/udp tunnel with one instance?

### ISSUE THREAD

**Issue by Shayan-To** [nadoo/glider#344]
Is it possible to create a tcp/udp tunnel with a single instance of glider? Or I must use separate instances for tcp and udp?

**Comment by phantomcraft** [comment]
As far I use Glider for these years I couldn't do that yet. You should run 2 Glider instances.

But if you're running Glider in a constrained environment such as a router or something like that and are concerned about high memory usage, you can try 3proxy which supports UDP/TCP tunnels on same instance: https://github.com/3proxy/3proxy

Its configuration should be like this:

```
auth iponly
allow **
tcppm -46 -i127.0.0.1 667 [fd00::1]:1111
udppm -64 -i::1 668 127.0.0.1 1112
```
