### ISSUE TITLE
socks and http proxy on the same port?

### ISSUE THREAD

**Issue by Shayan-To** [nadoo/glider#345]
Is it possible to have a socks and an http proxy server running on the same port?

I think I have seen Privoxy do it (though I'm not sure). Can glider do that?

(I'm using glider to turn my socks5 proxy into an http one, so I can use it in more tools and more easily. I was wondering if I can use a single port for it and not change the port every time I want to switch between the protocols. Also, it would make sharing the config with others and firewall configuration easier.)

**Comment by emptyteeth** [comment]
https://github.com/nadoo/glider/blob/master/config/glider.conf.example#L34-L35
