### ISSUE TITLE
Authentication on listeners

### ISSUE THREAD

**Issue by neginsadeghi** [nadoo/glider#348]
Hi, is there any option for authentication in socks/HTTP proxy listener mode? 

I mean a way that only authenticated users could use our proxy :)

**Comment by phantomcraft** [comment]
glider -listen http://user:password@127.0.0.1:3128

glider -listen socks://user:password@127.0.0.1:1080

See also: https://github.com/nadoo/glider/issues/347#issuecomment-1273744693
