### ISSUE TITLE
dnsserver compatibility with overture

### ISSUE THREAD

**Issue by soffchen** [nadoo/glider#35]
glider.conf

```
dnsserver=127.0.0.1:1053
```

and get the following error messages:

```
2018/07/22 21:46:46 [dns] failed to connect to server 127.0.0.1:1053: [http] can not connect remote address: 127.0.0.1:1053. error code: 503
2018/07/22 21:46:46 [dns] error in exchange: [http] can not connect remote address: 127.0.0.1:1053. error code: 503
2018/07/22 21:46:47 [dns] failed to connect to server 127.0.0.1:1053: [http] can not connect remote address: 127.0.0.1:1053. error code: 503
2018/07/22 21:46:47 [dns] error in exchange: [http] can not connect remote address: 127.0.0.1:1053. error code: 503
2018/07/22 21:46:48 [dns] failed to connect to server 127.0.0.1:1053: [http] can not connect remote address: 127.0.0.1:1053. error code: 503
2018/07/22 21:46:48 [dns] error in exchange: [http] can not connect remote address: 127.0.0.1:1053. error code: 503
2018/07/22 21:46:48 [dns] failed to connect to server 127.0.0.1:1053: [http] can not connect remote address: 127.0.0.1:1053. error code: 503
2018/07/22 21:46:48 [dns] error in exchange: [http] can not connect remote address: 127.0.0.1:1053. error code: 503
```

**Comment by soffchen** [comment]
maybe the dnsserver can not be the lan ip? glider tries to connect it via forwarder?

**Comment by nadoo** [comment]
yes, glider connects to dnsserver via forwarders.

**Comment by soffchen** [comment]
better to bypass forwarders when dnsserver set to localhost or lan ip?

**Comment by soffchen** [comment]
current solution: set lan dns to overture, and set its upstream dns server to glider dnstun

**Comment by soffchen** [comment]
no use :( 

dnstun doesn't match domain & ip in rules.

**Comment by nadoo** [comment]
dnstun doesn't do that, you can use `dns` setting:

glider.conf
```bash
dns=:53
dnsserver=127.0.0.1:1053
```

**Comment by soffchen** [comment]
please refer to the issue, glider connects to dnsserver via forwarders, while it has default forwarders :(

**Comment by nadoo** [comment]
May I know why you want to use glider's dns server while you already have overture running?

**Comment by soffchen** [comment]
I need to match domain rule in iptables redirect mode

**Comment by soffchen** [comment]
everything about dns will be finished by glider if it supports dns cache :(

**Comment by nadoo** [comment]
I wonder whether glider's rule and ipset features meet your requirements? only need to add dns cache ability to glider, right?

I'm considering how to improve dns features while keeping it simple...

btw: I found a [project](https://github.com/cn4/gfwlist2glider) which maybe useful.

**Comment by soffchen** [comment]
I think mapping domain to ip and matching rules is more graceful than ipset, and dnsmasq-china-list is more graceful than gfwlist at the same time, especially when we have fast servers to visit sites out of cn.

DNS cache is the only thing missed, I can add dnsmasq-china-list domains to bypass.rule, and set dnsserver to cn dns servers, leaving other sites with default forwarders and dnsserver to dns servers worldwide. I can even add some spec sites to different forwarders with domain, ip, cidr rules.

**Comment by soffchen** [comment]
my latest solution:

```
dns=:2053
dnsserver=1.1.1.1:53
```

and set overture's upstream server out of cn to 2053, which will trigger the domain rule match.

**Comment by soffchen** [comment]
alright, it works like a charm.

**Comment by nadoo** [comment]
Glad to hear that, and thanks for your valuable advice! 

I'll improve dns module later when I finished the websocket support.

ps. I didn't use 3rd party libs for dns/vmess/websocket since I want to learn more about these protocols and I don't want the binary to be huge, but this is also a bit more difficult to add new features.

**Comment by soffchen** [comment]
You may study overture's code about dns cache or much more :)

**Comment by nadoo** [comment]
overture uses https://github.com/miekg/dns , almost all go projects with dns features uses it.

**Comment by soffchen** [comment]
Well done, thank you.
