### ISSUE TITLE
Forward client username/password to HTTP proxy

### ISSUE THREAD

**Issue by entrailz** [nadoo/glider#355]
Similar to #305 

Hi,

I think what I am trying to achieve would come under something like this, so was wondering if its possible?

I have HAProxy setup as a http proxy, it handles authentication and everything, but I also want to let users use a socks proxy, I cannot find a way to do this within HAProxy so came across your software.

I want to be able to forward whatever authentication details are sent to Glider, and forward them with the request to the http proxy, is this possible?

The ideal path is:

Client connects to gliderip:1080, such as curl -x socks5://demo:demo@gliderip:1080
Glider forwards this request to my HAProxy http proxy, passing the username and password so HAProxy can handle the authentication.

Thanks.

**Comment by phantomcraft** [comment]
`glider -listen socks5://demo:demo@gliderip:1080 -forward http://user:password@haproxyip:3128/`

Replace 3128 with the HAProxy port.

**Comment by entrailz** [comment]
I want to forward the user password the end user provides, not a static value sadly.

**Comment by t-chab** [comment]
@entrailz : just wrap the command in a shell script : 

```bash
#!/usr/bin/env bash

read -r -p "Enter user name: " proxy_user
read -r -p "Enter user password: " proxy_pwd

glider_ip="TYPE_HERE_YOUR_GLIDER_IP"
haproxy_ip="TYPE_HERE_YOUR_HA_PROXY_IP"

glider \
    -listen "socks5://${proxy_user}:${proxy_pwd}@${glider_ip}:1080" \
    -forward "http://${proxy_user}:${proxy_pwd}@${haproxy_ip}:3128/"
```
