### ISSUE TITLE
Timeout of 5sec?

### ISSUE THREAD

**Issue by koen-serry** [nadoo/glider#359]
Hi, 

I'm looking at an occasional client timeout when the remote is slow and I came across this code : proxy/conn.go:55
Here I see that there's a timeout of 5sec. 

Do I have it correct that if the remote doesn't answer within 5sec. Glider aborts the request?
If so can I increase it?

**Comment by alpominth** [comment]
Glider has options for that:

```
$ ./glider -h | grep timeout
  -checktimeout int
    	fowarder check timeout(seconds) (default 10)
  -dialtimeout int
    	dial timeout(seconds) (default 3)
  -dnstimeout int
    	timeout value used in multiple dnsservers switch(seconds) (default 3)
  -relaytimeout int
    	relay timeout(seconds)
```

**Comment by koen-serry** [comment]
I was basically tracking these kinds of errors:

`relay error: readfrom tcp x.x.x.x:1080->x.x.x.x:53956: splice: connection reset by peer`

But unsure if it's glider dropping the connection, server or client.
