### ISSUE TITLE
How to start socks5 server and udp forward service via socks5 in one glider process?

### ISSUE THREAD

**Issue by aa51513** [nadoo/glider#373]
I'm trying to add "-dns" param in the config file ,then I got the flowing message : 
```
glider -config glider.conf
flag provided but not defined: -dns
```

I don't know why

**Comment by alpominth** [comment]
It should be like this:

```
dns=127.0.0.1:5353
dnsserver=8.8.8.8:53
```

See https://github.com/nadoo/glider/tree/master/config/examples/9.transparent_proxy_without_dnsmasq
