### ISSUE TITLE
Multiple dnsserver settings support?

### ISSUE THREAD

**Issue by soffchen** [nadoo/glider#38]
It looks like glider use first dnsserver only while it has multiple settings?

**Comment by nadoo** [comment]
yes, will be improved in the future.

**Comment by soffchen** [comment]
not supported yet, right?

**Comment by nadoo** [comment]
The code in master now supports multiple dnsservers, the implementation is simple that we always use the first dnsserver to do resolving, if there's a timeout then the secondary dnsserver used.

as dns server rarely goes down, I think that is enough.

**Comment by kometchtech** [comment]
@nadoo 

When setting up multiple DNS servers, I also want me to prepare a `strategy` option like `rotate` about the case where the first DNS server will be selected.
Of course, DNS servers are less likely to cause problems, but I would like them to be prepared from the standpoint of load countermeasures.

**Comment by nadoo** [comment]
@kometchtech , thanks for your advice, I'll think about it later.
