### ISSUE TITLE
Is it possible to retry a failed request to change the node?

### ISSUE THREAD

**Issue by R1dd1er** [nadoo/glider#395]
Hello, I would like to ask if this tool has the function of retrying failed requests, or if there are any options that can satisfy it. I have read the documentation several times and can't seem to find it.
The problem I encountered is probably like this. I have 100 nodes. I now need to send 1,000 requests through these node agents, but I found that the success rate is less than half, and the rest are failed requests. I guess it should be the node. It is unstable, resulting in lost requests. I am wondering if there are parameters that can change the node and retry the failed request. For example, a failed request is directly polled to the next node to continue trying, and I can set the number of such attempts myself, so It can reduce request loss caused by node instability.

**Comment by entrailz** [comment]
Also wondering if this is possible?

Tagging @nadoo
