### ISSUE TITLE
Is it possible to set up chained proxies (proxy1->proxy2) with default routing through proxy1 and specific domains routed through proxy2?

### ISSUE THREAD

**Issue by 2024baibai** [nadoo/glider#401]
设想的是链式代理是这样：
Clients -->  Listener --> | proxy1 --> proxy2 --> | Internet

链式代理proxy1是动态ip，proxy2是机场代理ip，动态ip需要外网环境才能使用，因此用proxy2作为proxy1的底层代理

然后希望再设置规则，指定的域名走机场代理ip，剩余的走动态ip，达到节省动态ip流量的原理

**Comment by nadoo** [comment]
You can see config [examples](https://github.com/nadoo/glider/tree/master/config/examples) which may help
