### ISSUE TITLE
When will IPv6 be supported as an outbound like v2ray? 

### ISSUE THREAD

**Issue by wjsw1781** [nadoo/glider#415]
v2ray可以开放socks类型的服务 然后把流量达到ipv6的网卡上作为最终出口
![image](https://github.com/user-attachments/assets/0eaa9d02-8a23-4c1d-92f7-424686e3a7c7)

但是glider目前只能ipv4-->IPv4
～～

Translated by ChatGPT: 
V2ray can provide SOCKS-type services and route the traffic to an IPv6 network card as the final outbound. However, Glider currently only supports IPv4 to IPv4.

**Comment by nadoo** [comment]
I don't use ipv6 but I think it's already supported like:
`glider -verbose -listen :8443 -interface IPv6Addr`

**Comment by alpominth** [comment]
@nadoo 

In my tests, Glider can bind to only one IP address, not both IPv4 and IPv6, I believe that support for binding to both IPv4 and 6 address would be great.
