### ISSUE TITLE
tls+ws+vless failed

### ISSUE THREAD

**Issue by x0chaoren0s** [nadoo/glider#417]
glider 0.16.4, windows  and glider 0.16.2, linux
glider config set:
forward=tls://183.178.22.246:11417?skipVerify=true,ws://@/?ed=2048&host=dns68.putata.eu.org,vless://d7dd3a35-b68b-4992-b319-a85b8a1fc8e5@183.178.22.246:11417
error info:
2024/09/17 10:55:52 client.go:35: [vless]: dial to 183.178.22.246:11417 error: remote error: tls: handshake failure
2024/09/17 10:55:52 group.go:263: [check] main: 183.178.22.246:11417(0), FAILED. error: remote error: tls: handshake failure

I'm sure this node is ok, because the following v2ray subscription link is ok in v2rayn and v2rayng:
vless://d7dd3a35-b68b-4992-b319-a85b8a1fc8e5@183.178.22.246:11417?encryption=none&security=tls&type=ws&host=dns68.putata.eu.org&path=%2F%3Fed%3D2048#%F0%9F%94%92%20VL-WS-TLS%20%F0%9F%87%AD%F0%9F%87%B0%20HK-183.178.22.246%3A11417

**Comment by nadoo** [comment]
try `forward=tls://183.178.22.246:11417?serverName=dns68.putata.eu.org`

**Comment by x0chaoren0s** [comment]
> try `forward=tls://183.178.22.246:11417?serverName=dns68.putata.eu.org`

thank you for your respond, but still failed.

when forward=tls://183.178.22.246:11417**?serverName=dns68.putata.eu.org**,ws://@/?ed=2048&host=dns68.putata.eu.org,vless://d7dd3a35-b68b-4992-b319-a85b8a1fc8e5@183.178.22.246:11417
error info:
2024/09/23 11:52:37 client.go:35: [vless]: dial to 183.178.22.246:11417 error: [ws] error in ws handshake, got wrong response: HTTP/1.1 200 OK
2024/09/23 11:52:37 group.go:263: [check] main: 183.178.22.246:11417(0), FAILED. error: [ws] error in ws handshake, got wrong response: HTTP/1.1 200 OK

when forward=tls://183.178.22.246:11417**?serverName=dns68.putata.eu.org&skipVerify=true**,ws://@/?ed=2048&host=dns68.putata.eu.org,vless://d7dd3a35-b68b-4992-b319-a85b8a1fc8e5@183.178.22.246:11417
same error info:
2024/09/23 11:58:09 client.go:35: [vless]: dial to 183.178.22.246:11417 error: [ws] error in ws handshake, got wrong response: HTTP/1.1 200 OK
2024/09/23 11:58:09 group.go:263: [check] main: 183.178.22.246:11417(0), FAILED. error: [ws] error in ws handshake, got wrong response: HTTP/1.1 200 OK

and the mentioned v2ray subscription link is still ok for right now.
