### ISSUE TITLE
domain rule about .cn sites

### ISSUE THREAD

**Issue by soffchen** [nadoo/glider#43]
Is it possible to bypass all .cn domain?
I've tried
```
domain=cn
```
in bypass.rule with dnsserver=119.29.29.29

but it doesn't work.

if it works, how about the dnscache work? and domain->ip rule work?

**Comment by nadoo** [comment]
Yes, it's not work, glider needs at least 2 parts `xx.yy` as a domain rule item.  
https://github.com/nadoo/glider/blob/8d20331096430d6cd4cb1ad730ffdf93cdf3d5fd/rule.go#L97-L106

if that works, it doesn't matter with dnscache, and a cn domain will only be added by domain->ip rule when it was resolved by glider's builtin dns server.

**Comment by nadoo** [comment]
change `for i := length - 2; i >= 0; i-- { ` to `for i := length - 1; i >= 0; i-- { ` will support it.

Dunno whether we need it, maybe you can have a test and tell me the results...

**Comment by nadoo** [comment]
Supported in the new version v0.7.1.
