### ISSUE TITLE
cidr rule not work

### ISSUE THREAD

**Issue by zhaibin18** [nadoo/glider#44]
glider config file
```
verbose=True
listen=:8443
forward=socks5://127.0.0.1:2080
rulefile=/home/root/etc/glider/chn.rule
```
/home/root/etc/glider/chn.rule

`cidr=220.181.112.0/24`

```
 ping www.baidu.com
PING www.baidu.com (220.181.112.244): 56 data bytes
64 bytes from 220.181.112.244: seq=0 ttl=54 time=29.453 ms
```
curl  -x http://127.0.0.1:8443 www.baidu.com

the request will forward to socks5 server but not direct

**Comment by nadoo** [comment]
Hi @zhaibin18, you visit `www.baidu.com` using domain, so you should set `domain=baidu.com`  in rule file for that to work.

**Comment by zhaibin18** [comment]
Can I user both domain and cidr rule?for example first check domain in the rule file,then check cidr next if not match

**Comment by nadoo** [comment]
glider's builtin dns server will handle the domain to ip resolving and update the rules, it works well with the redir proxy when client machines set dns ip to glider's dns server.

however, proxies like socks5/http uses remote dns resolving, so there's no corresponding relations between domain and ip locally.

we can add the ability to resolve domain locally first and then send requests to forwarder, but this may leads to some problems, I'll think about it when I have more spare time.

For now, you can run glider with builtin dns server, and set your os(where glider is running) dns to 127.0.0.1, you can just use the rule `domain=baidu.com` without setting any ip or cidr rules, glider's builtin dns server will add it for you when `www.baidu.com` resolved.

#### 1. glider.conf
```bash
verbose=True
listen=:8443
forward=socks5://127.0.0.1:2080

# let glider to listen on port 53 as a dns server
dns=:53

# set upstream dns server
dnsserver=1.1.1.1:53

rulefile=/home/root/etc/glider/chn.rule
```

#### 3.  /home/root/etc/glider/chn.rule
```bash
# just add baidu.com domain here, no need for it's ip or cidr
domain=baidu.com
# you can add any other cidr or ip rules as you need
cidr=192.168.1.0/24
```

#### 3. set your os dns(where glider is running) to 127.0.0.1

#### 4. run glider
```bash
glider -config glider.conf
```

**Comment by zhaibin18** [comment]
I have a test about your solution,but all dns request go via proxy,I want all site/ip in chn.rule go direct and others go via proxy.

**Comment by nadoo** [comment]
what version of glider do you use?

**Comment by zhaibin18** [comment]
glider v0.6.3

**Comment by zhaibin18** [comment]
I have a test for v0.6.5,all dns request go via proxy,nothing change.

**Comment by nadoo** [comment]
have you add domains which you want to resolve directly into your chn.rule file?

**Comment by zhaibin18** [comment]
the domain part works fine now but the cidr rule still not work.
this is the rule I want use

both domain and cidr in chn.rule

www.xxxx.com----match domain----resolve local----go direct
www.xxxx.com----no match domain----resolve local ----cidr in chn.rule----go direct

others ---- resolve via proxy ,go via proxy.

**Comment by nadoo** [comment]
If you are running glider on a linux gateway, you can use cidr rules with iptables redirect and glider's builtin dns and ipset features, it's quite easy.

If not, then you can wait for the local resolving feature in proxies later, it's a bit more complicated so I can't promise when to support it.
