### ISSUE TITLE
Feature request: HA with preemption

### ISSUE THREAD

**Issue by wellsgz** [nadoo/glider#45]
According to my test, current HA mode will only switch forwarder while a failure of active forwarder being detected.

It would be great if priority can be implemented for forwarder. Such that in HA mode,  if multiple forwarder set to enabled, the one with highest priority will be set as active forwarder. In other way, while a higher priority forwarder resumes from disabled state, it will take preemption over the rest enabled ones.

Use case:

HA setup with general forwarder (unlimited traffic) and a premium forwarder (bill by usage).

General forwarder shall be active whenever it's available.

**Comment by soffchen** [comment]
in one word: like haproxy backup node

**Comment by soffchen** [comment]
```
forward=a
forward=b
forward=c?backup=true
forward=d?backup=true
```

Like this, use c while a & b both down. Fall back to a or b once a or b up again.

**Comment by wellsgz** [comment]
@soffchen backup keyword is OK, but it's even better to have priority for granular control.

**Comment by soffchen** [comment]
just add weight parameter :)

**Comment by nadoo** [comment]
It's a good suggestion, I've considered it before but not implemented it yet.

#### glider now supports forwarder chain by simply use `,` to combine different proxies:
```
forward=socks5://server1:port1,ss://method:pass@server2:port2
```
means connect socks5 proxy first then use the ss proxy to reach destinations.

#### and also, glider uses this scheme to support different layer protocols:
```
forward=tls://host:port[?skipVerify=true],vmess://[security:]uuid@?alterID=num
```
means to make a tls connection first, then send vmess protocol over that connection to reach destinations.

#### we can combine above schemes:
```
forward=socks5://server1:port1,ss://method:pass@server2:port2,tls://host:port[?skipVerify=true],vmess://[security:]uuid@?alterID=num
```
it also works.

#### Now if we want to add a new parameter `weight` to the forwarder, which position is better? socks5 or vmess? or tls(as vmess has no host and port specified)?

**Comment by soffchen** [comment]
The new parameter like `weight` must apply to the full chain, so I think it is better to append the parameter to the end. Maybe `$` or `+` can be used as a splitter? just like:

```
forward=socks5://server1:port1,ss://method:pass@server2:port2+weight=100&...
```

and `&` for further parameters

`$` at the end would be the best choice, but may conflict with vmess parameters.

**Comment by nadoo** [comment]
Now you can try the new forwarder options supported in v0.6.7, https://github.com/nadoo/glider/blob/ac94540ab864d45e442e11edd92f01b5f8649a66/config/glider.conf.example#L58-L77

**Comment by nadoo** [comment]
```
forward=a#priority=100
forward=b#priority=100
forward=c
forward=d

strategy=rr
```
the default priority is 0, so with the above settings, glider will use `a` and `b` in round robin mode, if both `a` and `b` are disabled, then `c` and `d` will be choosed and also in round robin mode.

**Comment by fax001** [comment]
could give more detail about HA/LHA strategy ?

**Comment by xlighting2017** [comment]
> could give more detail about HA/LHA strategy ?

HA:
   when started: 
        check all proxies, and sort them into a list by priority (high to low);
   when a request is going to sent:
       within that list:
           use the first one that is available; mark as "current"
   when the checkduration is reached:
       check on those priority>=current, 
            if it's available, it will be the new "current"

LHA:
   when started: 
        check all proxies, and sort them into a list by priority (high to low);
   when a request is going to sent:
       within that list:
           use the first one that is available & have minimal latency; mark as "current"
   when the checkduration is reached:
       check on those priority>=current, 
            if it's available & have minimal latency(does not mean it has to be lower than current), it will be the new "current"

**Comment by nadoo** [comment]
Thanks @xlighting2017 , very professional.
