### ISSUE TITLE
ws support for mux

### ISSUE THREAD

**Issue by wellsgz** [nadoo/glider#47]
Wonder if mux is supported with ws and any keyword to enable if so.

In my tls+ws+vmess forwarder seems multiple connections are established while accessing a single page.

**Comment by nadoo** [comment]
Hi @wellsgz , websocket mux extension is not supported yet.
It's only a proposed draft, https://tools.ietf.org/html/draft-ietf-hybi-websocket-multiplexing-11

**Comment by soffchen** [comment]
@wellsgz tls+ws+vmess, so crazy...

**Comment by wellsgz** [comment]
@soffchen tls to make it looks like normal traffic, ws for multiplexing and vmess is mandatory for v2ray I guess...

The way I like like v2ray is with Traefik, I can easily build a concentration point with many backend for traffic distribution, and multiplexing will reduce overhead latency cause by 3 way handshake for each session.

**Comment by nadoo** [comment]
Go will support tcp fast open in later versions, and http2.0 already supported mux too, so we can just wait and see what to do next.

**Comment by qqqqqqrrrrhh123a** [comment]
do you know what is error about this question? https://github.com/nadoo/glider/issues/270
