### ISSUE TITLE
Socks5 sent with wrong source IP

### ISSUE THREAD

**Issue by steven-sheehy** [nadoo/glider#48]
I have glider running on a machine with two IPs bound to the same interface. 10.0.22.170 is the VIP and 10.0.22.173 is its actual IP. When I start glider with the VIP, I expect the proxied server to show the source IP as the VIP, not the actual IP.

```bash
$ ip addr show ens192
2: ens192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:91:02:a9 brd ff:ff:ff:ff:ff:ff
    inet 10.0.22.173/23 brd 10.0.23.255 scope global ens192
       valid_lft forever preferred_lft forever
    inet 10.0.22.170/32 scope global ens192
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fe91:2a9/64 scope link
       valid_lft forever preferred_lft forever
$
$ ./glider -listen socks5://10.0.22.170:1081 -verbose
2018/08/09 16:57:12 [socks5-udp] listening UDP on 10.0.22.170:1081
2018/08/09 16:57:12 [socks5] listening TCP on 10.0.22.170:1081
2018/08/09 16:57:22 [socks5] 10.0.22.171:35036 <-> 10.0.22.107:443
```

I run curl from another machine:
```bash
$ curl --proxy socks5://10.0.22.170:1081 https://10.0.22.107
```

And the logs on the proxied server 10.0.22.107:
```
10.0.22.173 - - [09/Aug/2018:11:57:22 -0500] "GET / HTTP/2.0" 200 1727 "-" "curl/7.58.0"
```

**Comment by nadoo** [comment]
You can specify the outbound ip using ip route command:
`ip route add 10.0.22.107 via 10.0.22.170`

**Comment by steven-sheehy** [comment]
That's a workaround for a single IP. The 10.0.22.107 is just one example of an infinite amount that the people can connect to. It's not feasible to add route entries before every server you need to connect to especially if those servers are not known ahead of time.

**Comment by nadoo** [comment]
Then what about other programs on your server? If you need all programs to go out through vip, then you should change the default route, not all programs support  customizing outbound ip features.

It’s not a bug of glider, like your question, if you start glider with 127.0.0.1 with:
glider -verbose -listen socks5://127.0.0.1:1080
then should it send requests via 127.0.0.1? How?

Nevertheless, I’ve considered to add the ability to specify custom interface or ip of the forwarder, then it should be easy to control it by glider.

**Comment by nadoo** [comment]
Please try v0.6.7 with the new `interface` setting(or new forwarder option `interface`), we can specify the source ip or interface now.
 https://github.com/nadoo/glider/releases

**Comment by steven-sheehy** [comment]
@nadoo I can confirm it now shows the correct IP on the server with `glider -listen socks5://:1081 -interface $VIP`. Thank you so much for your amazing work!
