### ISSUE TITLE
Command-line only usage doesn't work since 0.2.1

### ISSUE THREAD

**Issue by felixonmars** [nadoo/glider#5]
It seems to be trying to open a nonexist config file and failed:

```
$ glider -listen :8443 -verbose
ERROR: open : no such file or directory
```

**Comment by nadoo** [comment]
Hi @felixonmars, sorry for that. There was a bug in the package conflag, I've uploaded a new version v0.3.2 and it should work now.

**Comment by felixonmars** [comment]
Confirmed the fix. Thank you!
