### ISSUE TITLE
Any ideas to support TCP fast open

### ISSUE THREAD

**Issue by dongxinb** [nadoo/glider#50]
Thank you for your awesome job!
Since GO 1.11 is released several days ago and it supports ListenConfig for socket, would you like to add TFO support for glider in the near future?

Thank you!

**Comment by nadoo** [comment]
Yes, I want to add tfo support too, I’m very busy these days, hope to look into it later.

**Comment by nadoo** [comment]
https://github.com/golang/go/issues/4842
It's still not widely used after 2 years, so let's close this issue now.
