### ISSUE TITLE
systemd failed to start when rulefile with relative path specified in config

### ISSUE THREAD

**Issue by chenxsan** [nadoo/glider#52]
When I have `rulefile` in my main config:

```
rulefile=bypass.rule
```
systemd would fail to start.

I have to specify the absolute path:

```
rulefile=/etc/glider/bypass.rule
```
Could it be fixed? If not, I can submit a pull request to add a note to the [systemd page](https://github.com/nadoo/glider/tree/master/systemd).

**Comment by nadoo** [comment]
Hi @chenxsan , please try v0.6.8 and see whether it works like you want.

**Comment by chenxsan** [comment]
Thanks, it works with relative path now.
