### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by kratoskang** [nadoo/glider#55]
软件版本是 0.6.7，用 x86 debian 做软路由。 
请问会是什么原因？

# 错误信息
2018/08/31 20:45:20 [dns] listening UDP on :5353
2027 2018/08/31 20:45:20 [dns]-tcp listening TCP on :5353
2028 2018/08/31 20:45:20 listening TCP on :8080
2029 2018/08/31 20:45:20 [socks5] listening TCP on :1080
2030 2018/08/31 20:45:20 [mixed] listening TCP on :8443
2031 2018/08/31 20:45:20 [socks5-udp] listening UDP on :1080
2032 2018/08/31 20:45:20 [redir] listening TCP on :12345
2033 2018/08/31 20:45:20 [socks5-udp] listening UDP on :8443
2034 2018/08/31 20:45:21 [dns] failed to read response length: EOF
2035 2018/08/31 20:45:21 [dns] failed to exchange with server 208.67.220.220:5353: EOF
2036 2018/08/31 20:45:21 [dns] failed to read response length: EOF
2037 2018/08/31 20:45:21 [dns] failed to exchange with server 8.8.8.8:53: EOF
2038 2018/08/31 20:45:21 [dns] error in exchange: EOF
2039 2018/08/31 20:45:25 [redir] 192.168.8.4:49919 <-> 172.217.14.78:443
2040 panic: runtime error: slice bounds out of range
2041
2042 goroutine 43 [running]:
2043 github.com/nadoo/glider/dns.(*Message).UnmarshalRR(0xc420120880, 0x25, 0xc420126370, 0x1f4, 0xc420118180, 0x19)
2044     E:/work/codes/go/src/github.com/nadoo/glider/dns/message.go:384 +0x449
2045 github.com/nadoo/glider/dns.UnmarshalMessage(0xc4201de242, 0x200, 0x200, 0x13, 0xc42012a460, 0x13)
2046     E:/work/codes/go/src/github.com/nadoo/glider/dns/message.go:143 +0x232
2047 github.com/nadoo/glider/dns.(*Client).Exchange(0xc42005a240, 0xc4201de240, 0x202, 0x202, 0xc42012a460, 0x13, 0x0, 0x0, 0x0, 0x0, ...)
2048     E:/work/codes/go/src/github.com/nadoo/glider/dns/client.go:60 +0x80
2049 github.com/nadoo/glider/dns.(*Server).ListenAndServeUDP.func1(0xc42000a7c0, 0xc4201de240, 0x202, 0x202, 0x200, 0x6a3560, 0xc42011a450, 0x6a5500, 0xc42000c088)
2050     E:/work/codes/go/src/github.com/nadoo/glider/dns/server.go:72 +0xb2
2051 created by github.com/nadoo/glider/dns.(*Server).ListenAndServeUDP
2052     E:/work/codes/go/src/github.com/nadoo/glider/dns/server.go:71 +0x38e

# 配置文件这要设定如下(透明网关) 
listen=redir://:12345

forward=ssr://aes-256-cfb:xxxxx@127.0.0.1:11111?protocol=auth_aes128_md5&obfs=tls1.2_ticket_auth

dns=:5353

dnsserver=8.8.8.8:53
dnsserver=208.67.220.220:5353

**Comment by nadoo** [comment]
Hi @kratoskang , do you have any `interface` settings in your config?

**Comment by kratoskang** [comment]
@nadoo no interface settings .

**Comment by nadoo** [comment]
Is it always panic every time you started glider? Or it happens occasionally?

**Comment by kratoskang** [comment]
always panic every time after I start glider 3 or 4 seconds later.

**Comment by nadoo** [comment]
Try to set up a normal proxy with that forwarder without dns:
`glider -verbose -listen :8443 -forward "ssr://aes-256-cfb:xxxxx@127.0.0.1:11111?protocol=auth_aes128_md5&obfs=tls1.2_ticket_auth"`
then set the browser's proxy to ip:8443, will it panic again?

**Comment by kratoskang** [comment]
> Try to set up a normal proxy with that forwarder without dns:
glider -verbose -listen :8443 -forward "ssr://aes-256-cfb:xxxxx@127.0.0.1:11111?protocol=auth_aes128_md5&obfs=tls1.2_ticket_auth"
then set the browser's proxy to ip:8443, will it panic again?
-------------------------------------------------------------
It will not panic forwarder without dns

**Comment by nadoo** [comment]
OK, maybe glider received an invalid dns udp packet, I've add a length check to avoid that panic.

**Comment by kratoskang** [comment]
When will you release new version?

**Comment by nadoo** [comment]
Please try this attachment and see whether it was solved or not: [glider-0.6.8.zip](https://github.com/nadoo/glider/files/2343289/glider-0.6.8.zip)

**Comment by kratoskang** [comment]
@nadoo It has been working for one week and no problem, I think we can close it now.
