### ISSUE TITLE
More encryption methods for ss

### ISSUE THREAD

**Issue by zhaibin18** [nadoo/glider#56]
There is a [fork](https://github.com/ayanamist/go-shadowsocks2/) from go-ss2, and the [commit ](https://github.com/ayanamist/go-shadowsocks2/commit/01a569b336915f3db4fab962620affa44740570f) add more encryption methods such as rc4-md5, so can you please use this lib for more encryption methods?

**Comment by nadoo** [comment]
https://github.com/nadoo/go-shadowsocks2/commits/master , added chacha20 and XCHACHA20-IETF-POLY1305 support.
