### ISSUE TITLE
error "too many open files"

### ISSUE THREAD

**Issue by wellsgz** [nadoo/glider#58]
Facing issue with occasionally transaction lagging, from glider log it shows "too many open files".

My system has ulimit being set to 500000. I search around and found a similar issue from other app also develop with Go, not sure if it's the same case.

https://github.com/containous/traefik/issues/1322

Sep 08 16:56:27 glider[2580]: 2018/09/08 16:56:27 [redir] failed to get target address: file tcp 192.168.8.10:8443->192.168.8.118:7865: fcntl: too many open files
Sep 08 16:56:27 glider[2580]: 2018/09/08 16:56:27 [redir] failed to accept: accept tcp [::]:8443: accept4: too many open files
Sep 08 16:56:27 glider[2580]: 2018/09/08 16:56:27 [redir] failed to accept: accept tcp [::]:8443: accept4: too many open files
Sep 08 16:56:27 glider[2580]: 2018/09/08 16:56:27 [redir] failed to accept: accept tcp [::]:8443: accept4: too many open files
Sep 08 16:56:27 glider[2580]: 2018/09/08 16:56:27 [redir] failed to accept: accept tcp [::]:8443: accept4: too many open files

**Comment by wellsgz** [comment]
btw, there is indeed large amount of TIME_WAIT conns at the moment:

netstat -an | grep TIME_WAIT | grep 127.0.0.1 | wc -l
1064

**Comment by soffchen** [comment]
```
cat /proc/`pidof -s glider`/limits
```

show your REAL limits

**Comment by wellsgz** [comment]
@soffchen 

You're right, for the process nofile=1024

Limit                     Soft Limit           Hard Limit           Units
[...Snip]
Max processes             3703                 3703                 processes
Max open files            1024                 4096                 files
[..Snip]

By adding LimitNOFILE to systemd service file will increase the limit each time process starts instead of use prlimit to increase it manually each time.

@nadoo Maybe the the limit can be increase a little bit for default service value.

**Comment by soffchen** [comment]
102400 in default settings :) 

https://github.com/nadoo/glider/tree/master/systemd

**Comment by wellsgz** [comment]
@soffchen my bad, omits the changing systemd setting part 🤪🤪🤪
