### ISSUE TITLE
Request for enhancements: custom rule implementation using plugin

### ISSUE THREAD

**Issue by vnalla** [nadoo/glider#60]
Hi,

Is it possible to enhance implementation for the following:

1) Custom rule implementation that can add additional restrictions or information to route the requests. For example: allowed destination ports or IP & Port combination in addition to existing configuration. I think it is possible if the rule implementation is  modified similar to the proxy implementation. 

2) To add a dynamic plugin without touching the base proxy code, either for custom rule and/or any proxy server such that request flow can be intercepted so that it can be either allowed or blocked (kind of firewall rules)

thanks

**Comment by vnalla** [comment]
We are planning to use glider and in our use case there is a need to intercept the request flow at the entry proxy and allow or disallow the call flow based on the certain criteria. There are two ways to intercept the call flow:
1)	Intercept in the rule dialer’s Dial method. This will intercept all the types of traffic that enters the glider proxy and only target IP and port number are available for the interceptor code
2)	Intercept the request flow in proxy/http/http.go and proxy/socks5/socks5.go, before the .dialer.Dial call is made, at that point both the source IP, source port, target IP and target port are available for the interceptor code. This will only intercept HTTP or SOCKS5 traffic that enters the glider proxy and do not intercept all other traffic. This is what we need in our use case.
Here is the high-level plan to implement this enhance the glide proxy code. Please let me know if there is a better way to do it, so that I can plan on a pull request and submit the code for review.
1)	Add the following configuration options
a.	intercept – True/False indicates whether to intercept the call flow or not
b.	pluginfile – pluginfile name to load. The actual intercept code depends on other internal functionally. Therefore, it shall be implemented as golang plugin, so that this custom code does not have to be interfered with actual proxy code
c.	pluginconfigfile – configuration file used by the plugin code
2)	Add the plugin load code to common/plugin/loadplugin.go. The plugin code exposes two methods, and it will also have the intercept flag which is exposed via struct variable  
a.	Intercept(sourceAddress, targetAddress) error {} – This functional is called to intercept the call flow. If the returned error in nil the call will be allowed to go through
b.	Start() error – This method is called from main.go to initialize the plugin interceptor code.
3)	Update the main.go to call “Start” method of the plugin
4)	Update proxy/http/http.go and proxy/socks5/socks5.go to call the Intercept method of the plugin if “Intercept” Boolean flag is true.

**Comment by nadoo** [comment]
Hi @vnalla , sorry that glider does not meet your requirement currently, as you want to intercept the flow of proxy, have you ever tried [shuttle](https://github.com/sipt/shuttle)? which can modify the request and response data, maybe it will be a better choice now.

Anyway, if you think glider is a better choice, it will be appreciated if you send PR to glider, feel free to do it and I can merge and improve it later.
