### ISSUE TITLE
How to use KCP in VMESS?

### ISSUE THREAD

**Issue by everyx** [nadoo/glider#63]
How can I use KCP in vmess:// ?

**Comment by nadoo** [comment]
For original KCP protocol, you can use [kcptun](https://github.com/xtaci/kcptun) together with glider.  If you mean the mKCP protocol from v2ray, that's not supported now.

**Comment by everyx** [comment]
> For original KCP protocol, you can use [kcptun](https://github.com/xtaci/kcptun) together with glider. If you mean the mKCP protocol from v2ray, that's not supported now.

Does Glider has any plan to implementm KCP protocol support?

**Comment by nadoo** [comment]
@everyx , yes, I will add it when I have some time.

**Comment by nadoo** [comment]
The code with the latest commit supports kcp now, you can try it if you know how to compile it.

**Comment by nadoo** [comment]
scheme:
`kcp://[crypt:key@][host]:port[?dataShards=NUM&parityShards=NUM]`

server:
`glider -verbose -listen kcp://:1000,http://`
client:
`glider -verbose -listen :8443 -forward kcp://:1000,http://`

**Comment by nadoo** [comment]
It's stock KCP protocol, not mKCP from v2ray.
