### ISSUE TITLE
add https listener

### ISSUE THREAD

**Issue by changx** [nadoo/glider#68]
using plaintext http proxy as upstream server is insecure on public network, it would be better if glider support https listener.

here is the PR for https listener   https://github.com/nadoo/glider/pull/67#issue-222695309

thank you :)

**Comment by nadoo** [comment]
Hi @changx , many thanks to your PR. :)

Do you use https proxy on internet? I thought http proxy server mode always used in local network, so authentication was not supported either.

Anyway, if we want a https proxy server, should we implement it like the chained dialer? so we can use it as the following scheme:
```
glider -listen tls://443?cert=xxx_bundle.pem&key=xxx_key.pem,http://
```
so we can setup a socks5 server with tls like:
```
glider -listen tls://443?cert=xxx_bundle.pem&key=xxx_key.pem,socks5://
```
also like ss with tls:
```
glider -listen tls://443?cert=xxx_bundle.pem&key=xxx_key.pem,ss://method:pass@
```

**Comment by changx** [comment]
yes sure , it's the best way to implement tls support.

And yes all my upstreams are ssl proxies, they are working pretty fast and stable, on standard tcp port 443

**Comment by changx** [comment]
hi @nadoo  , pls check the latest pr, tls:// transport layer for listeners.
