### ISSUE TITLE
possible dead loop in ipset and rules?

### ISSUE THREAD

**Issue by xlighting2017** [nadoo/glider#69]
### **setup**(basically, whitelist mode):

1. use dnsmasq to receive all client request, and different .conf to resolve domains:
- chnroute use dedicate .conf
- forwarder use dedicate .conf
- all the rest, go to Glider DNS.

2. use ipset/iptable to redirect traffic:
- chnroute RETURN
- others, REDIRECT to Glider

3. in Glider:
- glider.conf
  - forwarder:  domain name only, like  xxx.abc.com, _which will resolve to an address NOT in chnroute_
  - strategy: lha
  - ipset=glider
  - rule-dir=rules.d
- dedicate rules.d/direct.rule
  - no forwarder in this file
  - dnsserver=114:53
  - domain=abc.com

### problem:
after Glider starts, it will
  1.  try to resolve xxx.abc.com, using "remote DNS server";  (according to the readme of ipset)

  2.  to use “remote DNS server", it need to connect to forwarder first

  3. to connect to the forwarder, it will hit iptables REDIRECT

seems this will create a dead loop, and you can see a lot of "too many open files"(something like that)

I've tried following "workaround", but no luck:

   1. insert an ipset match glider RETURN rule, before the REDIRECT one;

   2. comment out the "ipset=glider" in glider.conf 

I know ideally, I should manually add the resolve result of xxx.abc.com to the RETURN/chnroute ipset, but I think gilder should be a better manager, because the manual way is start/one-time solution while glider will do it at run-time/automatically.

**Comment by nadoo** [comment]
Hi @xlighting2017 , 

when resolving the forwarder's domain name, glider will directly connect to the dnsserver:
https://github.com/nadoo/glider/blob/14b072832daabcbade76b93852bad92d065f72f3/dns/client.go#L132-L134

**Comment by xlighting2017** [comment]
Hi @nadoo , thanks for the reply.
however, the problem is not "resovle failed",  I see in the logs, the dialer/forwarder dns name is resolved.
but the next connection/dial is failing, due to the REDIRECT rule...

I can provide sample conf file for you to reproduce, let me know how to reach/send such files to you  :)

**Comment by nadoo** [comment]
Hi @xlighting2017 , in current version, glider will not operate ipset when there's no forwarder set in rule file:
https://github.com/nadoo/glider/blob/14b072832daabcbade76b93852bad92d065f72f3/ipset/ipset_linux.go#L110-L113

but I think if glider can add the resolved results to a separate ipset, like:
#### rules.d/direct.rule
```
# set a separate ipset here, all ip/cidr and resolved ip of domains list below will be added to this ipset
ipset=direct

dnsserver=114:53
domain=abc.com
```
then you can change your iptables to avoid redirecting by using the ipset `direct`.

Do you think this will help? if so, I can implement it in the next version. :)

**Comment by xlighting2017** [comment]
@nadoo, that will be great.

one more thing after you implement it:
can I re-use an existing ipset name here, like  "ipset = chnroute"   <-- so that I can save 1 line for the iptables
or Glider will flush/create/remove that ipset when start/stop ?

**Comment by nadoo** [comment]
Glider flushs the ipset at startup, dnsmasq also flushs ipset at startup. 

I always use glider without dnsmasq, can we put chnroute items in glider's rule file so that glider can manage the `chnroute` ipset itself?

**Comment by nadoo** [comment]
you can use list file which only has the match items like: https://github.com/nadoo/glider/tree/master/config/examples/9.transparent_proxy_without_dnsmasq/rules.d
include it in the .rule file: 
```
include=chnroute.list
include=dns-china.list
```

for ad host blocking, do you mean resolve some domain result to 127.0.0.1? if so, glider supports it by using custom dns records like:
```
dnsrecord=www.example.com/1.2.3.4
dnsrecord=www.example.com/2606:2800:220:1:248:1893:25c8:1946
```

**Comment by xlighting2017** [comment]
> you can use list file which only has the match items like: https://github.com/nadoo/glider/tree/master/config/examples/9.transparent_proxy_without_dnsmasq/rules.d
> include it in the .rule file:
> 
> ```
> include=chnroute.list
> include=dns-china.list
> ```
> for ad host blocking, do you mean resolve some domain result to 127.0.0.1? if so, glider supports it by using custom dns records like:
> 
> ```
> dnsrecord=www.example.com/1.2.3.4
> dnsrecord=www.example.com/2606:2800:220:1:248:1893:25c8:1946
> ```

it seems dnsrecord must be in the glider.conf, not in rule/list?  my ad hosts has 8000+ items...

**Comment by nadoo** [comment]
Yes, now this setting can only be added in the main config file... dunno what will happen when there are more than 8000 items..

**Comment by nadoo** [comment]
Hi @xlighting2017 , domain's ip will be added when the builtin dns server resolves it.

**Comment by xlighting2017** [comment]
> Hi @xlighting2017 , domain's ip will be added when the builtin dns server resolves it.

will that be another loop? in my setup, the server is a FQDN/domain name,  for the buildin dns to resolve it, it has to be forwarded through the server?

in the sserver.rule, I also set
```
no any forwarder;
dns=114.114.114.114:53
```
, but that did not help..

**Comment by nadoo** [comment]
https://github.com/nadoo/glider/blob/6ba9e1f5e852fa602b450dd049ffe114214d62e1/dns/client.go#L131-L134

It will not be a loop.

**Comment by nadoo** [comment]
Do you mean in a rule file, your forwarder's is like `a.example.com`, and you set `example.com`(uplevel domain of forwarder) in the domain list and want it to be resolved and added to ipset?

**Comment by xlighting2017** [comment]
> Do you mean in a rule file, your forwarder's address is like `a.example.com`, and you set `example.com`(uplevel domain of forwarder) in the domain list and want it to be resolved and added to ipset?

my server is like  `xx.yy.example.com`, in glider.conf,   while in rules, I set `domain= example.com`, I thought it will save a lot of time from adding xx.yy one-by-one ...

**Comment by nadoo** [comment]
> > Do you mean in a rule file, your forwarder's address is like `a.example.com`, and you set `example.com`(uplevel domain of forwarder) in the domain list and want it to be resolved and added to ipset?
> 
> my server is like `xx.yy.example.com`, in glider.conf, while in rules, I set `domain= example.com`, I thought it will save a lot of time from adding xx.yy one-by-one ...

Then what is the purpose of adding `domain=example.com` in a rule file? In there any other forwarder setting in that rule file?

**Comment by nadoo** [comment]
And in the rule file, have you added another domain like `domain=apple.com`, then after restart glider, if you query `apple.com` like `dig www.apple.com @glider_dns_address`, glider will add the resolved ip to ipset.

**Comment by xlighting2017** [comment]
I see the problem.. I'm using dnsmasq with glider, 
and I set server names to be resolved by dnsmasq, therefore, the domain rules in .rule file are not working....

anyway, to use whitelist mode with dnsmasq, here is the correct setup:

1. use dnsmasq to receive all client request, and different .conf to resolve domains:

    - accelerate-china-dns use dedicate .conf
    - forwarder's domain , **go to Glider DNS**
    - all the rest, go to Glider DNS.

2. in Glider:
    - glider.conf
    forwarder: domain name / IP
    rule-dir=rules.d

3. dedicate rules.d/forwarder.rule
    - no forwarder in this file
    dnsserver=114:53
    - ipset= _servers_
    domain=forwarder's domain, like xxx.xyz
    ip=forwarder's IP

4. use ipset/iptable to redirect traffic:
    - ipset chnroute RETURN
    - ipset _servers_ RETURN
    - others, REDIRECT to Glider

why I'm still using dnsmasq?
1. the .cn match in glider is not working -- #43 
2. dnsrecord in glider.conf is hard to maintain--- dnsmasq is using a separate .conf
3. it will be a little tricky to run my openwrt/LEDE without dnsmasq(it also acting as a DHCP server)

**Comment by nadoo** [comment]
v0.7.1 has been released:
1. root domain supported.
2. now we can include more sub config files;
