### ISSUE TITLE
Compilation on MIPS

### ISSUE THREAD

**Issue by platkaw** [nadoo/glider#7]
I am trying to compile glider to a MIPS platform running OpenWRT but having an error with the redir option:

`# glider
./redir_linux.go:26:8: undefined: redir
`

Removing all the references to the 'redir' option makes the compilation work.

`$ file glider
glider: ELF 32-bit MSB executable, MIPS, MIPS32 version 1 (SYSV), statically linked, stripped
`

**Comment by nadoo** [comment]
Hi @platkaw , the latest commit 503a5c5 should fix the problem.

Glider is under development and there are some experimental codes, I'll improve it when I get more spare time.

**Comment by platkaw** [comment]
Compiled successfully and working without issues. Thank you!
