### ISSUE TITLE
ipset always empty

### ISSUE THREAD

**Issue by daxingplay** [nadoo/glider#73]
## My server enviroment

* Ubuntu 16.04
* glider 0.6.8 from [release](https://github.com/nadoo/glider/releases/download/v0.6.8/glider-v0.6.8-linux-amd64.zip)

## My Step

I followed the guide from [transparent proxy without dnsmasq](https://github.com/nadoo/glider/blob/master/config/examples/9.transparent_proxy_without_dnsmasq) and created an ipset called `glider`. I also created the same iptable rules as shown in the guide.

My configurations were as follows:

glider.conf:
```
verbose=True
forward=aaa.xxx.com
forward=bbb.xxx.com
dns=8.8.8.8:53
strategy=lha
ipset=glider
rule-dir=rules.d
```

rules.d/xxx.rule:
```
dns=114.114.114.114
domain=taobao.com
```

## Problem

When I started my glider server, I can tell from the logs that all dns queries work fine and I tried dig some domains without any problems. However, no entries were added to ipset. I tried `sudo ipset list glider` on my server, the output showed:

```
Name: glider
Type: hash:net
Revision: 1
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 384
References: 2
Members:
```

Yes, there were no members shown in my ipset. And of course, no redir log entry showed in glider output. I tried browse some website not in xxx.rule, and cannot be opened.

I tried remove the iptables rules and redirect all traffic to glider without ipset, the website can be open then.

So how can I make my ipset work? Did I miss something? Thanks.

**Comment by daxingplay** [comment]
I read the notes in the example configuration again:
```
add resolved ips for domains in rule files by dns forwarding server 
```

Does it mean only domains in rule files will be added to ipset?

But I'm still confused that if so, the domains (eg: taobao.com) in my rule files were still not shown in ipset.

**Comment by nadoo** [comment]
Hi @daxingplay , in current version, destinations will only be added to ipset when the following 2 conditions both matched:
1. destinations(domains/ips/cidrs) listed in a rule file;
2. at least one forwarder listed in the same rule file;

so in your condition, just like #69, maybe we can change the behavior of ipset management in the next version.

BTW, you can use glider without dnsmasq in a different way(which I always used on my router):

### glider.conf:
```
verbose=True
listen=redir://:1081

dns=:53
dnsserver=114.114.114.114:53

ipset=glider

rule-dir=rules.d
```

### rules.d/gfwlist.rule:
```
forward=aaa.xxx.com
forward=bbb.xxx.com

strategy=lha
dnsserver=8.8.8.8:53
dnsserver=8.8.4.4:53

include=gfwlist.list
```

### rules.d/gfwlist.list:
you can download it [here](https://raw.githubusercontent.com/cn4/gfwlist2glider/master/gfwlist.list)

then all destinations listed in gfwlist.list will be added to ipset glider, with the iptables rule `iptables -t nat -I PREROUTING -p tcp -m set --match-set glider dst -j REDIRECT --to-ports 1081`, only gfwlist destinations will be redirected to glider(then requested via forwarders).

ps. the config `dns` means a local dns server address, and `dnsserver` means a remote dns server address.

**Comment by daxingplay** [comment]
Thanks for your reply, @nadoo . I now understand why my ipset is empty. As you said, current ipset management works better for `gfwlist` rule while I use chnroute method same as the author of #69 . I'll try your approach then. And I will also vote for the feature of better ipset management in the next version :)

Thanks again. I really appreciate your excellent work on glider.
