### ISSUE TITLE
HTTP listener is modifying the header in wrong way

### ISSUE THREAD

**Issue by rankjie** [nadoo/glider#76]
e.g.
The server's original response has 2 `Set-Cookie` in the header.
![c3b7ec53-c83d-422a-a498-7715c4eec75c](https://user-images.githubusercontent.com/772235/48783516-e2668880-ece0-11e8-9044-0f3475f7737b.png)

Glider will concatenate the two `Set-Cookie`  without add `;` in between, this is causing problems for certain websites.
![deaef0a1-6a10-484d-a885-aab686539749](https://user-images.githubusercontent.com/772235/48783607-1f327f80-ece1-11e8-82ed-86e06a967bd5.png)

I suggest keeping the headers the way it was, not to change the actual content.

**Comment by rankjie** [comment]
I believe the cause is the `writeHeaders` function in `proxy/http/http.go`.

**Comment by nadoo** [comment]
Hi @rankjie , you can try v0.6.9 and see whether this issue fixed.

**Comment by nadoo** [comment]
Feel free to reopen this issue when the problem still exists.
