### ISSUE TITLE
ICAP support

### ISSUE THREAD

**Issue by onrik** [nadoo/glider#78]

**Comment by nadoo** [comment]
Hi @onrik, do you mean https://wiki.squid-cache.org/Features/ICAP ?

**Comment by onrik** [comment]
@nadoo yes.

**Comment by nadoo** [comment]
Hi @onrik , if you want a proxy server for a corporation, I think squid is the best choice.

**Comment by onrik** [comment]
I agree that squid good choice for a corporation. But when you developing some software with ICAP integration you need simple proxy with fast installation and i think glider is the best candidate for it.
