### ISSUE TITLE
[Feature Request] Support simple-obfs in glider

### ISSUE THREAD

**Issue by xlighting2017** [nadoo/glider#79]
seems the current ss schema does not support simple-obfs, which will prevent us using AEAD+OBFS servers...

there are some existing Go implementation of simple-obfs, like [this](https://github.com/Dreamacro/clash/tree/master/component/simple-obfs)

**Comment by xlighting2017** [comment]
@nadoo Thanks for the update
 `forward=simple-obfs://1.1.1.1:443?type=tls&host=apple.com,ss://`

seems 1.1.1.1:443 can be changed to anything, but the key config is "tls" and "apple.com" , no?

**Comment by nadoo** [comment]
gliderf -verbose -listen:8443 -forward="simple-obfs://1.1.1.1:443?type=tls&host=apple.com,ss://AEAD_CHACHA20_POLY1305:pass@"

'1.1.1.1:443' is your server address, 'type' and 'host' is obfs parameters.

**Comment by xlighting2017** [comment]
got it. Thanks, 
will try after you release, and provide feedback here

**Comment by xlighting2017** [comment]
hmmm, with 0.6.10, it works when type=http, but not when type=tls
`
[redir] relay error: chacha20poly1305: message authentication failed
`

**Comment by nadoo** [comment]
I tested with the latest obfs-server and it worked here. What is your server’s config?

**Comment by xlighting2017** [comment]
how can I send you the config? pleas let me know
I'm using something like:
`
forward=simple-obfs://A.B.C.D:Port?type=tls&host=8a25812193.wns.windows.com,ss://AEAD_CHACHA20_POLY1305:PASSWORD@
`

**Comment by nadoo** [comment]
Please give me the following info about your server for debugging:
1. obfs-server version? (did you compile it with the latest commit [here](https://github.com/shadowsocks/simple-obfs)? )
2. ss-server version? or do you use glider as ss-server?
3. If you use ss-server, are you running obfs-server as standalone mode? or as a ss-server plugin?

**Comment by xlighting2017** [comment]
I don't have control over the server side since I'm using services from other people.... I can only confirm that
1. when set server obfs to TLS, other clients, like Surge, is working fine;
2. when set server obfs to HTTP, and keep all other settings, like host/password, glider works fine too;
3. it happens on all servers from 2 different service providers

**Comment by xlighting2017** [comment]
hmmm, check this:
https://github.com/Dreamacro/clash/commit/da391356dd2996f30b58d58af0cfab4ea52b2d25

it seems the Client Hello is constructed differently? for example, 
`random := make([]byte, 28)`
V.S.
`random := make([]byte, 32)`

**Comment by xlighting2017** [comment]
the attached version works! 
so I presume it's the timestamp 
-- although RFC indicate we can use 32 random, the SSR is requiring the timestamp to be accurate...

thanks for the help!

**Comment by nadoo** [comment]
https://tools.ietf.org/id/draft-mathewson-no-gmtunixtime-00.txt
As the above article side, it's not encouraged to send current time in handshake.

After google, I found that almost all tls server implementations do not check the time diff, and I also tested with golang tls client and the Chrome browser, they do not send current time either, so I think the ssr's tls obfs implementation has a noticeable signature with the time processing, in other words, it could be identify easily.

**Comment by nadoo** [comment]
Can not reproduce here, but I'll add a timeout for dialing later. Note that glider will double the check interval when a server disabled.

**Comment by xlighting2017** [comment]
test ok with 0.6.11
