### ISSUE TITLE
Special character(s) in password leads to "not supported cipher" error

### ISSUE THREAD

**Issue by 70akaline** [nadoo/glider#82]
When I use the configuration:
```./glider -listen :147619  -forward=ss://AEAD_CHACHA20_POLY1305:MYPASS@MYIP:MYPORT -verbose```
The log gives as:
```2018/12/22` 02:55:12 [ss] PickCipher for '', error: cipher not supported```
Either ```AEAD_CHACHA20_POLY1305``` or ```chacha20-ietf-poly1305```, this bug is able to repeat on my server(Ubuntu 18.04) and on my desktop (MacOS)
Should I also report this bug with go2-ss?

**Comment by nadoo** [comment]
Can't reproduce here, may be your shell has some special treatment with character `@`?
command line without `@`, like:
`glider -listen :8443 -forward=ss://AEAD_CHACHA20_POLY1305:MYPASSMYIP:MYPORT -verbose`
will give the result:
`[ss] PickCipher for '', error: cipher not supported`

**Comment by nadoo** [comment]
`#` is a special character in url, may be you can try escaping it to `%23`, like:
`glider -listen :8443 -forward=ss://AEAD_CHACHA20_POLY1305:MYPASSInclude%23xxx@MYIP:MYPORT -verbose`

**Comment by 70akaline** [comment]
> `#` is a special character in url, may be you can try escaping it to `%23`, like:
> `glider -listen :8443 -forward=ss://AEAD_CHACHA20_POLY1305:MYPASSInclude%23xxx@MYIP:MYPORT -verbose`

Many thanks, this works. But will this bug will be fixed in further version, or just regard as a feature?

**Comment by nadoo** [comment]
Hi @70akaline , since glider relies on the url lib to parse proxy settings, so it's not a bug, I'll add some instructions in help message. Thanks for your feedback!

**Comment by 70akaline** [comment]
> Hi @70akaline , since glider relies on the url lib to parse proxy settings, so it's not a bug, I'll add some instructions in help message. Thanks for your feedback!

OK, thanks for your help.
