### ISSUE TITLE
[Feature Request]trigger forwarder disable when multiple redir error occurs

### ISSUE THREAD

**Issue by xlighting2017** [nadoo/glider#83]
my setup(redir) shows that 
when the server fails, it will stop forwarding packets(to the next hop, but glider<-->server is OK), and glider will have below errors:
[dns] failed to read response length: read tcp 10.130.137.173:59549->xxxxx:nnn : i/o timeout
[redir] relay error: EOF

will the above error trigger an increase to the maxfailures ?

if no, can we have such error trigger the "forwarder disable"? 
because in this case, we have to wait until next check to know the fwder is broken...

**Comment by xlighting2017** [comment]
not exactly,  
#70 is a "dial error" which for sure will trigger fwder disable,  it just won't stop trying even if all fwders are disabled(in your case, no route to dst)

my error here, AFAIK, does not trigger fwder disable -- dial is OK, but data return is zero or wrong (for example, on Server, use iptables to reject incoming packets)

**Comment by nadoo** [comment]
Hi @xlighting2017 , currently the `forwarder max failures` only counts dial errors, I think we need a refactoring to achieve the purpose of increasing failures count when read or write errors occured.

**Comment by xlighting2017** [comment]
Hi @nadoo, can we have some plan for this?  
it will be great if we can implement some check like HTTPing or the ssl-hello-chk in HAProxy...

my ISP has some issue that the Fwder may "connect/dial OK with the Fwder", but fail to "connect the dst server" or "ssl handshake to the dst server"

**Comment by xlighting2017** [comment]
Hi @nadoo,  I have a test scenario for this:
 on the server, first, allow the traffic to pass through, 

 then use `iptables drop`  to discard DNS packets, 

 therefore, the glider will dial OK, but can not access any website due to DNS failure;

  in such a scenario, the glider will keep trying until the next `checkinterval` is reached(or never recover?)

**Comment by xlighting2017** [comment]
Hi @nadoo, any plan to move forward? 
there is a PR worth trying :)

**Comment by nadoo** [comment]
Hi @xlighting2017 , thanks! 

The code looks great, but when dns exchange failed, should we distinguish between the proxy server problem and the dns server problem?

**Comment by xlighting2017** [comment]
> Hi @xlighting2017 , thanks!
> 
> The code looks great, but when dns exchange failed, should we distinguish between the proxy server problem and the dns server problem?

hmmm...  I believe there is already a mechanism to use multiple DNS servers to avoid "one of them failed"?

in that case, an error of "all DNS server failed" should be used as the trigger?

**Comment by nadoo** [comment]
> > Hi @xlighting2017 , thanks!
> > The code looks great, but when dns exchange failed, should we distinguish between the proxy server problem and the dns server problem?
> 
> hmmm... I believe there is already a mechanism to use multiple DNS servers to avoid "one of them failed"?
> 
> in that case, an error of "all DNS server failed" should be used as the trigger?


forwarder: 
we count failures to determine a forwarder is invalid, when reaches max failures, it will be set to disabled; 
TODO: increase failure count like #133

dns server: 
maybe we can also add a failure count like forwarder, when it reaches max failures, we set it to disabled and switch to the backup dns server.

**Comment by xlighting2017** [comment]
errrr, my original problem, is the forwarder fails to forward DNS packets(not dial failure, but forwarding failure), 
in that case,  switch to backup DNS will also fail.

here is the setup:
> on the server, first, allow the traffic to pass through,
> then use ```iptables drop``` to discard DNS packets,
> therefore, the glider will dial OK, but can not access any website due to DNS failure;


so my suggestion is to "use DNS failure of all servers, as an indicator of forwarder failure", because that will be more sensitive than the regular "interval check"

**Comment by nadoo** [comment]
@xlighting2017 ok, I'll try to merge the PR and have some tests.
