### ISSUE TITLE
Support for http/socks5 server authecation.

### ISSUE THREAD

**Issue by leon332157** [nadoo/glider#84]
@nadoo Is there any implemented or plan for authentication with http(s) or socks5, or even mixed? Because I want to open the port to the internet but it's not safe to do so without an authentication process. Many thanks!

**Comment by nadoo** [comment]
Hi @leon332157 , http/socks5 server mode doesn't support authentication now, why not use ss? or ss over tls? it has authentication support and is more secure.

**Comment by leon332157** [comment]
Well, if I expose the proxy server to public internet without a firewall, anyone can use it. And the last time I did this, it got blacklisted. So I was wondering if auth can be added. 👍

**Comment by whoizit** [comment]
I can't setup private proxy in yggdrasil network without this feature

**Comment by whoizit** [comment]
we can use ss without encryption ss://dummy:pass@:8443 for auth
https://github.com/nadoo/glider/issues/106

**Comment by whoizit** [comment]
oh, no, seems like pass ignored if dummy

**Comment by whoizit** [comment]
socks5 auth changes works for me
