### ISSUE TITLE
Is that legal that I use the executable file in my app?

### ISSUE THREAD

**Issue by Fndroid** [nadoo/glider#87]
Hello, glider is a awesome project, it's helpful to chain our proxies.

I noticed that glider is now using GPLv3 and I want to know is that legal that I use the executable file(.exe) in my Windows Electron APP(not opensource yet)?

Thanks again.

**Comment by nadoo** [comment]
Yes, the license can be changed and you can use it without any problem.

**Comment by Fndroid** [comment]
Thank you for your awesome project and reply!
