### ISSUE TITLE
simple-obfs is deprecated

### ISSUE THREAD

**Issue by whoizit** [nadoo/glider#90]
simple-obfs marked as depricated https://github.com/shadowsocks/simple-obfs

instead they do https://github.com/shadowsocks/v2ray-plugin

with **ss over ws** and **ss over quic** obfuscation, written on Go

**Comment by nadoo** [comment]
ss over ws already supported

**Comment by whoizit** [comment]
is it possible emulate this behaviour, for ws-https? https://github.com/shadowsocks/v2ray-plugin#shadowsocks-over-websocket-https

**Comment by nadoo** [comment]
You can try:
```
forward=tls://host:port,ws://,ss://method:pass@
```
