### ISSUE TITLE
remote write error: write udp [::]:[PORT]: invalid argument

### ISSUE THREAD

**Issue by MrPointer** [nadoo/glider#91]
Hello, just stumbled upon this nice proxy tool which I need for UDP packets, yet I receive the unfortunate error message described in the title after successfully "proxying" a single packet.

Scenario:
Using 3 network devices, setup a simply ridiculous proxy scenario where a host **A** send a _UDP_ packet to host **B** through a **Proxy Server**, i.e. **A** knows **Proxy**, which knows **B**.
It would looks something like this: `A ----- Proxy ----- B`

I've used [Packet Sender](https://packetsender.com/) to generate _UDP_ packets on host **A** and receive them as well on host **B**.
The proxy of course is **glider** (latest release, v0.6.11), listening on a single port using the `udptun` schema. 
After a single successful relay, all other packets are dropped with the error: 

> remote write error: write udp [::]:[PORT]: invalid argument

Where [PORT] is an arbitrary port number which doesn't really mean much (at least not intuitively)

I've tested it on **Windows 10 x64** as this is my requirement.

**Comment by nadoo** [comment]
Hi @MrPointer, can't reproduce the issue here, what is the command line you use to start glider? 
like `glider -verbose -listen udptun://:53=8.8.8.8:53` ?

**Comment by MrPointer** [comment]
@nadoo Right, forgot to describe the command I used 😕 
I used a similar one to the one you've suggested: `glider -verbose -listen udptun://:12500=10.0.0.8:5006` (Just different port numbers and IP addresses).

It's also important to note that I tested it on 2 different LANs with no success on either - Same problem.

**Comment by nadoo** [comment]
There's a bug in udptun, you can try the following binary and see whether it works:
[glider-v0.7.0.zip](https://github.com/nadoo/glider/files/2957483/glider-v0.7.0.zip)

**Comment by MrPointer** [comment]
@nadoo Glad to report the issue has been resolved! Thank you! 👍

**Comment by nadoo** [comment]
Thanks for the report! :P
