### ISSUE TITLE
Enhancement: add doc about new features: reject/include

### ISSUE THREAD

**Issue by xlighting2017** [nadoo/glider#94]
Hi nadoo:
  thanks for the new release.
  I see the reject is added as an new type of fwder, so we can use a  `reject.rule` acting like adhosts?
```
forward=reject
domain=doubleclick.net
```

how about the new `include` , any example?

**Comment by nadoo** [comment]
You can see the last 2 commits for example.

**Comment by xlighting2017** [comment]
got it, thanks!
