### ISSUE TITLE
[BUG] checkwebsite and proxy get error code: 403 when using tls(nginx+squid) upstream proxy

### ISSUE THREAD

**Issue by LazyZhu** [nadoo/glider#95]
The tls upstream proxy is nginx+squid, https and http are handled separately: https with connect and http nginx reverse proxy.

 curl -x 127.0.0.1:8433  https://www.google.com
 curl -x 127.0.0.1:8433  http://www.google.com

**Comment by nadoo** [comment]
1. Are you using a http2 proxy?
2. What is the forward settings in glider like?
3. With your 2 test commands: `curl -x 127.0.0.1:8433 https://www.google.com`, `curl -x 127.0.0.1:8433 http://www.google.com`, which one get error code? the error code is returned by nginx or squid?
4. Any log of these program?

**Comment by LazyZhu** [comment]
1. Yes, it's  a http2 proxy.
2. glider-v0.7.0-windows-amd64 forward settings:

~~~
forward=tls://server-a.com:1234?skipVerify=true,http://#priority=50
forward=tls://server-b.com:1234?skipVerify=true,http://#priority=50
forward=tls://server-c.com:1234?skipVerify=true,http://#priority=50
forward=tls://server-d.com:1234?skipVerify=true,http://#priority=50
forward=tls://server-e.com:1234?skipVerify=true,http://#priority=50
forward
strategy=lha
checkwebsite=www.google.cn
checkinterval=60
~~~

3,4.
`curl -x 127.0.0.1:8433 https://www.google.com` tested ok with webpage and glider log:
~~~
2019/03/22 08:27:06 [http] 127.0.0.1:53855 <-> www.google.com:443 [c]
~~~

`curl -x 127.0.0.1:8433 http://www.google.com` tested with blank and glider log:
~~~
2019/03/22 08:28:01 [http] 127.0.0.1:53990 <-> www.google.com:80, error in dial: [http] can not connect remote address: www.google.com:80. error code: 403
~~~

The check log:
~~~
2019/03/22 08:26:49 [check] server-a.com:1234(50) -> www.google.cn:80, DISABLED. error in dial: [http] can not connect remote address: www.google.cn:80. error code: 403
2019/03/22 08:26:49 [check] server-b.com:1234(50) -> www.google.cn:80, DISABLED. error in dial: [http] can not connect remote address: www.google.cn:80. error code: 403
2019/03/22 08:26:49 [check] server-c.com:1234(50) -> www.google.cn:80, DISABLED. error in dial: [http] can not connect remote address: www.google.cn:80. error code: 403
2019/03/22 08:26:49 [check] server-d.com:1234(50) -> www.google.cn:80, DISABLED. error in dial: [http] can not connect remote address: www.google.cn:80. error code: 403
2019/03/22 08:26:49 [check] server-e.com:1234(50) -> www.google.cn:80, DISABLED. error in dial: [http] can not connect remote address: www.google.cn:80. error code: 403
~~~

**Comment by LazyZhu** [comment]
I tried another proxy tool called [clash](https://github.com/Dreamacro/clash) berore, but has the same issue. But there's unmerged pull related with this which can help you understand the issue: https://github.com/Dreamacro/clash/pull/112 .

**Comment by nadoo** [comment]
I see, thanks for your report, will be fixed in this weekend.
