### ISSUE TITLE
Is forwarder being used?

### ISSUE THREAD

**Issue by jschwartzenberg** [nadoo/glider#98]
When I try whether my configured forwarder works, I just get output like:
```
[http] [::1]:41514 <-> portquiz:80 [c], error in dial: [http] can not connect remote address: portquiz:80. error code: 400
```

Is my forwarder not being used? How can I check whether it's being used or not?

**Comment by rankjie** [comment]
I couldn't tell either.
That's why I made this pull request.  https://github.com/nadoo/glider/pull/92

**Comment by nadoo** [comment]
Thanks, PR merged.
